package types

import "cosmossdk.io/errors"

var (
	ErrLIPNotFound               = errors.Register(ModuleName, 2, "LIP not found")
	ErrInvalidStatus             = errors.Register(ModuleName, 3, "invalid LIP status transition")
	ErrAlreadyVoted              = errors.Register(ModuleName, 4, "voter has already voted on this LIP")
	ErrNotProposer               = errors.Register(ModuleName, 5, "only the proposer can perform this action")
	ErrTerminalState             = errors.Register(ModuleName, 6, "LIP is in a terminal state")
	ErrInsufficientStake         = errors.Register(ModuleName, 7, "insufficient stake")
	ErrVotingPeriodEnded         = errors.Register(ModuleName, 8, "voting period has ended")
	ErrNotInVotingStage          = errors.Register(ModuleName, 9, "LIP is not in voting stage")
	ErrInvalidCategory           = errors.Register(ModuleName, 10, "invalid LIP category")
	ErrUnauthorized              = errors.Register(ModuleName, 11, "unauthorized")
	ErrInvalidParams             = errors.Register(ModuleName, 12, "invalid parameters")
	ErrVoteNotFound              = errors.Register(ModuleName, 13, "vote not found")
	ErrQuorumNotMet              = errors.Register(ModuleName, 14, "quorum not met")
	ErrInvalidAddress            = errors.Register(ModuleName, 15, "invalid address")
	ErrModuleNotFound            = errors.Register(ModuleName, 16, "module not found in param router")
	ErrNotDesignatedVoter        = errors.Register(ModuleName, 17, "not a designated research fund voter")
	ErrResearchProposalNotFound  = errors.Register(ModuleName, 18, "research spend proposal not found")
	ErrDiscussionPeriodActive    = errors.Register(ModuleName, 19, "cannot vote during discussion period")
	ErrResearchAlreadyVoted      = errors.Register(ModuleName, 20, "voter has already voted")
	ErrResearchVotersNotSet      = errors.Register(ModuleName, 21, "research fund voters not configured")
	ErrInsufficientApprovals     = errors.Register(ModuleName, 22, "insufficient approvals for research spend")
	ErrNotResearchFundVoter      = errors.Register(ModuleName, 23, "not an authorized research fund voter for current phase")
	ErrPhaseFullGovernance       = errors.Register(ModuleName, 24, "research fund is in full governance phase; use standard LIP process")
	ErrSeatElectionNotFound      = errors.Register(ModuleName, 25, "seat election proposal not found")
	ErrSeatAlreadyHeld           = errors.Register(ModuleName, 26, "candidate already holds a community seat")
	ErrNotGuardianTier           = errors.Register(ModuleName, 27, "candidate is not Guardian tier")
	ErrInsufficientGovHistory    = errors.Register(ModuleName, 28, "candidate has not voted on enough LIPs")
	ErrSeatNominationExpired     = errors.Register(ModuleName, 29, "nomination acceptance deadline has passed")
	ErrNotNominatedCandidate     = errors.Register(ModuleName, 30, "sender is not the nominated candidate")
	ErrSeatElectionNotVoting     = errors.Register(ModuleName, 31, "seat election is not in voting stage")
	ErrSeatElectionAlreadyVoted  = errors.Register(ModuleName, 32, "voter has already voted on this seat election")
	ErrInvalidSeatIndex          = errors.Register(ModuleName, 33, "seat index is invalid for current phase")
	ErrSeatNominationNotAccepted = errors.Register(ModuleName, 34, "nomination has not been accepted by candidate")
	ErrInvalidPhaseTarget        = errors.Register(ModuleName, 35, "target phase must be current + 1")
	ErrRollbackCooldownActive    = errors.Register(ModuleName, 36, "rollback cooldown active, cannot propose transition")
	ErrExitConditionsNotMet      = errors.Register(ModuleName, 37, "not all exit conditions are met")
	ErrCannotRollbackGenesis     = errors.Register(ModuleName, 38, "cannot rollback below genesis phase")
	ErrNoRollbackJustification   = errors.Register(ModuleName, 39, "rollback requires gridlock or emergency halt evidence")
	ErrPhaseTransitionNotFound   = errors.Register(ModuleName, 40, "phase transition proposal not found")
	ErrPhaseTransitionNotVoting  = errors.Register(ModuleName, 41, "phase transition proposal is not in voting stage")
	ErrPhaseTransitionVoted      = errors.Register(ModuleName, 42, "already voted on this phase transition proposal")
	ErrPendingTransitionExists   = errors.Register(ModuleName, 43, "a pending phase transition already exists")
	ErrEmergencyRemovalNoGrounds = errors.Register(ModuleName, 44, "emergency removal requires valid grounds (jailed or 3+ slashes)")
	ErrUpgradePlanRequired       = errors.Register(ModuleName, 45, "upgrade LIP requires a locked upgrade plan before voting")
	ErrUpgradePlanLocked         = errors.Register(ModuleName, 46, "upgrade plan cannot be attached or changed after voting begins")
	ErrUpgradeHeightTooSoon      = errors.Register(ModuleName, 47, "upgrade height must be after voting completes")
	ErrUpgradeScheduleFailed     = errors.Register(ModuleName, 48, "approved upgrade could not be scheduled")
	ErrEmergencyTransitionHold   = errors.Register(ModuleName, 49, "custom governance transitions are held for post-incident review")
)
