// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/gov/v1/genesis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the governance module parameters.
type Params struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VotingPeriodBlocks       uint64                 `protobuf:"varint,1,opt,name=voting_period_blocks,json=votingPeriodBlocks,proto3" json:"voting_period_blocks,omitempty"`             // blocks for voting stage (default 102816)
	DiscussionPeriodBlocks   uint64                 `protobuf:"varint,2,opt,name=discussion_period_blocks,json=discussionPeriodBlocks,proto3" json:"discussion_period_blocks,omitempty"` // blocks for last_call stage (default 68544)
	QuorumThresholdBps       uint64                 `protobuf:"varint,3,opt,name=quorum_threshold_bps,json=quorumThresholdBps,proto3" json:"quorum_threshold_bps,omitempty"`             // on 1,000,000 scale (default 334000 = 33.4%)
	SupportThresholdBps      uint64                 `protobuf:"varint,4,opt,name=support_threshold_bps,json=supportThresholdBps,proto3" json:"support_threshold_bps,omitempty"`          // on 1,000,000 scale (default 500000 = 50%)
	MinLipStake              string                 `protobuf:"bytes,5,opt,name=min_lip_stake,json=minLipStake,proto3" json:"min_lip_stake,omitempty"`                                   // uzrn minimum to submit a LIP
	MinVoteStake             string                 `protobuf:"bytes,6,opt,name=min_vote_stake,json=minVoteStake,proto3" json:"min_vote_stake,omitempty"`                                // uzrn minimum bonded stake to vote
	CategoryConfigs          []*CategoryConfig      `protobuf:"bytes,7,rep,name=category_configs,json=categoryConfigs,proto3" json:"category_configs,omitempty"`
	ResearchFundVoters       *ResearchFundVoters    `protobuf:"bytes,8,opt,name=research_fund_voters,json=researchFundVoters,proto3" json:"research_fund_voters,omitempty"`
	ResearchDiscussionBlocks uint64                 `protobuf:"varint,9,opt,name=research_discussion_blocks,json=researchDiscussionBlocks,proto3" json:"research_discussion_blocks,omitempty"` // discussion period for research proposals
	ResearchVotingBlocks     uint64                 `protobuf:"varint,10,opt,name=research_voting_blocks,json=researchVotingBlocks,proto3" json:"research_voting_blocks,omitempty"`            // voting period for research proposals
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetVotingPeriodBlocks() uint64 {
	if x != nil {
		return x.VotingPeriodBlocks
	}
	return 0
}

func (x *Params) GetDiscussionPeriodBlocks() uint64 {
	if x != nil {
		return x.DiscussionPeriodBlocks
	}
	return 0
}

func (x *Params) GetQuorumThresholdBps() uint64 {
	if x != nil {
		return x.QuorumThresholdBps
	}
	return 0
}

func (x *Params) GetSupportThresholdBps() uint64 {
	if x != nil {
		return x.SupportThresholdBps
	}
	return 0
}

func (x *Params) GetMinLipStake() string {
	if x != nil {
		return x.MinLipStake
	}
	return ""
}

func (x *Params) GetMinVoteStake() string {
	if x != nil {
		return x.MinVoteStake
	}
	return ""
}

func (x *Params) GetCategoryConfigs() []*CategoryConfig {
	if x != nil {
		return x.CategoryConfigs
	}
	return nil
}

func (x *Params) GetResearchFundVoters() *ResearchFundVoters {
	if x != nil {
		return x.ResearchFundVoters
	}
	return nil
}

func (x *Params) GetResearchDiscussionBlocks() uint64 {
	if x != nil {
		return x.ResearchDiscussionBlocks
	}
	return 0
}

func (x *Params) GetResearchVotingBlocks() uint64 {
	if x != nil {
		return x.ResearchVotingBlocks
	}
	return 0
}

// CategoryConfig defines per-category stake and review requirements.
type CategoryConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Category         string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`                                           // "parameter", "upgrade", "text", "research_spend"
	RequiredStakeBps string                 `protobuf:"bytes,2,opt,name=required_stake_bps,json=requiredStakeBps,proto3" json:"required_stake_bps,omitempty"` // uzrn required to advance from draft to review
	ReviewBlocks     uint64                 `protobuf:"varint,3,opt,name=review_blocks,json=reviewBlocks,proto3" json:"review_blocks,omitempty"`              // blocks required in review stage before last_call
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CategoryConfig) Reset() {
	*x = CategoryConfig{}
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryConfig) ProtoMessage() {}

func (x *CategoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryConfig.ProtoReflect.Descriptor instead.
func (*CategoryConfig) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryConfig) GetRequiredStakeBps() string {
	if x != nil {
		return x.RequiredStakeBps
	}
	return ""
}

func (x *CategoryConfig) GetReviewBlocks() uint64 {
	if x != nil {
		return x.ReviewBlocks
	}
	return 0
}

// GenesisState defines the governance module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Lips          []*LIP                 `protobuf:"bytes,2,rep,name=lips,proto3" json:"lips,omitempty"`
	Votes         []*Vote                `protobuf:"bytes,3,rep,name=votes,proto3" json:"votes,omitempty"`
	NextLipNumber uint64                 `protobuf:"varint,4,opt,name=next_lip_number,json=nextLipNumber,proto3" json:"next_lip_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_genesis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_genesis_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetLips() []*LIP {
	if x != nil {
		return x.Lips
	}
	return nil
}

func (x *GenesisState) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *GenesisState) GetNextLipNumber() uint64 {
	if x != nil {
		return x.NextLipNumber
	}
	return 0
}

var File_zerone_gov_v1_genesis_proto protoreflect.FileDescriptor

const file_zerone_gov_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"\x1bzerone/gov/v1/genesis.proto\x12\rzerone.gov.v1\x1a\x19zerone/gov/v1/types.proto\"\xb7\x04\n" +
	"\x06Params\x120\n" +
	"\x14voting_period_blocks\x18\x01 \x01(\x04R\x12votingPeriodBlocks\x128\n" +
	"\x18discussion_period_blocks\x18\x02 \x01(\x04R\x16discussionPeriodBlocks\x120\n" +
	"\x14quorum_threshold_bps\x18\x03 \x01(\x04R\x12quorumThresholdBps\x122\n" +
	"\x15support_threshold_bps\x18\x04 \x01(\x04R\x13supportThresholdBps\x12\"\n" +
	"\rmin_lip_stake\x18\x05 \x01(\tR\vminLipStake\x12$\n" +
	"\x0emin_vote_stake\x18\x06 \x01(\tR\fminVoteStake\x12H\n" +
	"\x10category_configs\x18\a \x03(\v2\x1d.zerone.gov.v1.CategoryConfigR\x0fcategoryConfigs\x12S\n" +
	"\x14research_fund_voters\x18\b \x01(\v2!.zerone.gov.v1.ResearchFundVotersR\x12researchFundVoters\x12<\n" +
	"\x1aresearch_discussion_blocks\x18\t \x01(\x04R\x18researchDiscussionBlocks\x124\n" +
	"\x16research_voting_blocks\x18\n" +
	" \x01(\x04R\x14researchVotingBlocks\"\x7f\n" +
	"\x0eCategoryConfig\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12,\n" +
	"\x12required_stake_bps\x18\x02 \x01(\tR\x10requiredStakeBps\x12#\n" +
	"\rreview_blocks\x18\x03 \x01(\x04R\freviewBlocks\"\xb8\x01\n" +
	"\fGenesisState\x12-\n" +
	"\x06params\x18\x01 \x01(\v2\x15.zerone.gov.v1.ParamsR\x06params\x12&\n" +
	"\x04lips\x18\x02 \x03(\v2\x12.zerone.gov.v1.LIPR\x04lips\x12)\n" +
	"\x05votes\x18\x03 \x03(\v2\x13.zerone.gov.v1.VoteR\x05votes\x12&\n" +
	"\x0fnext_lip_number\x18\x04 \x01(\x04R\rnextLipNumberB,Z*github.com/zerone-chain/zerone/x/gov/typesb\x06proto3"

var (
	file_zerone_gov_v1_genesis_proto_rawDescOnce sync.Once
	file_zerone_gov_v1_genesis_proto_rawDescData []byte
)

func file_zerone_gov_v1_genesis_proto_rawDescGZIP() []byte {
	file_zerone_gov_v1_genesis_proto_rawDescOnce.Do(func() {
		file_zerone_gov_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_gov_v1_genesis_proto_rawDesc), len(file_zerone_gov_v1_genesis_proto_rawDesc)))
	})
	return file_zerone_gov_v1_genesis_proto_rawDescData
}

var file_zerone_gov_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zerone_gov_v1_genesis_proto_goTypes = []any{
	(*Params)(nil),             // 0: zerone.gov.v1.Params
	(*CategoryConfig)(nil),     // 1: zerone.gov.v1.CategoryConfig
	(*GenesisState)(nil),       // 2: zerone.gov.v1.GenesisState
	(*ResearchFundVoters)(nil), // 3: zerone.gov.v1.ResearchFundVoters
	(*LIP)(nil),                // 4: zerone.gov.v1.LIP
	(*Vote)(nil),               // 5: zerone.gov.v1.Vote
}
var file_zerone_gov_v1_genesis_proto_depIdxs = []int32{
	1, // 0: zerone.gov.v1.Params.category_configs:type_name -> zerone.gov.v1.CategoryConfig
	3, // 1: zerone.gov.v1.Params.research_fund_voters:type_name -> zerone.gov.v1.ResearchFundVoters
	0, // 2: zerone.gov.v1.GenesisState.params:type_name -> zerone.gov.v1.Params
	4, // 3: zerone.gov.v1.GenesisState.lips:type_name -> zerone.gov.v1.LIP
	5, // 4: zerone.gov.v1.GenesisState.votes:type_name -> zerone.gov.v1.Vote
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_zerone_gov_v1_genesis_proto_init() }
func file_zerone_gov_v1_genesis_proto_init() {
	if File_zerone_gov_v1_genesis_proto != nil {
		return
	}
	file_zerone_gov_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_gov_v1_genesis_proto_rawDesc), len(file_zerone_gov_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_gov_v1_genesis_proto_goTypes,
		DependencyIndexes: file_zerone_gov_v1_genesis_proto_depIdxs,
		MessageInfos:      file_zerone_gov_v1_genesis_proto_msgTypes,
	}.Build()
	File_zerone_gov_v1_genesis_proto = out.File
	file_zerone_gov_v1_genesis_proto_goTypes = nil
	file_zerone_gov_v1_genesis_proto_depIdxs = nil
}
