// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/gov/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryLIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LipId         string                 `protobuf:"bytes,1,opt,name=lip_id,json=lipId,proto3" json:"lip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLIPRequest) Reset() {
	*x = QueryLIPRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLIPRequest) ProtoMessage() {}

func (x *QueryLIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLIPRequest.ProtoReflect.Descriptor instead.
func (*QueryLIPRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryLIPRequest) GetLipId() string {
	if x != nil {
		return x.LipId
	}
	return ""
}

type QueryLIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lip           *LIP                   `protobuf:"bytes,1,opt,name=lip,proto3" json:"lip,omitempty"`
	Votes         []*Vote                `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLIPResponse) Reset() {
	*x = QueryLIPResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLIPResponse) ProtoMessage() {}

func (x *QueryLIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLIPResponse.ProtoReflect.Descriptor instead.
func (*QueryLIPResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLIPResponse) GetLip() *LIP {
	if x != nil {
		return x.Lip
	}
	return nil
}

func (x *QueryLIPResponse) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type QueryLIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`     // filter by stage (optional)
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // filter by category (optional)
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLIPsRequest) Reset() {
	*x = QueryLIPsRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLIPsRequest) ProtoMessage() {}

func (x *QueryLIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLIPsRequest.ProtoReflect.Descriptor instead.
func (*QueryLIPsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryLIPsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryLIPsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QueryLIPsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLIPsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryLIPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lips          []*LIP                 `protobuf:"bytes,1,rep,name=lips,proto3" json:"lips,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLIPsResponse) Reset() {
	*x = QueryLIPsResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLIPsResponse) ProtoMessage() {}

func (x *QueryLIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLIPsResponse.ProtoReflect.Descriptor instead.
func (*QueryLIPsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLIPsResponse) GetLips() []*LIP {
	if x != nil {
		return x.Lips
	}
	return nil
}

func (x *QueryLIPsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QueryVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LipId         string                 `protobuf:"bytes,1,opt,name=lip_id,json=lipId,proto3" json:"lip_id,omitempty"`
	Voter         string                 `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteRequest) Reset() {
	*x = QueryVoteRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteRequest) ProtoMessage() {}

func (x *QueryVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteRequest.ProtoReflect.Descriptor instead.
func (*QueryVoteRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryVoteRequest) GetLipId() string {
	if x != nil {
		return x.LipId
	}
	return ""
}

func (x *QueryVoteRequest) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

type QueryVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          *Vote                  `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteResponse) Reset() {
	*x = QueryVoteResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteResponse) ProtoMessage() {}

func (x *QueryVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteResponse.ProtoReflect.Descriptor instead.
func (*QueryVoteResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVoteResponse) GetVote() *Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type QueryVotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LipId         string                 `protobuf:"bytes,1,opt,name=lip_id,json=lipId,proto3" json:"lip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVotesRequest) Reset() {
	*x = QueryVotesRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVotesRequest) ProtoMessage() {}

func (x *QueryVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVotesRequest.ProtoReflect.Descriptor instead.
func (*QueryVotesRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryVotesRequest) GetLipId() string {
	if x != nil {
		return x.LipId
	}
	return ""
}

type QueryVotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Votes         []*Vote                `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVotesResponse) Reset() {
	*x = QueryVotesResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVotesResponse) ProtoMessage() {}

func (x *QueryVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVotesResponse.ProtoReflect.Descriptor instead.
func (*QueryVotesResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryVotesResponse) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type QueryTallyResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LipId         string                 `protobuf:"bytes,1,opt,name=lip_id,json=lipId,proto3" json:"lip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultRequest) Reset() {
	*x = QueryTallyResultRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultRequest) ProtoMessage() {}

func (x *QueryTallyResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultRequest.ProtoReflect.Descriptor instead.
func (*QueryTallyResultRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTallyResultRequest) GetLipId() string {
	if x != nil {
		return x.LipId
	}
	return ""
}

type QueryTallyResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YesStake      string                 `protobuf:"bytes,1,opt,name=yes_stake,json=yesStake,proto3" json:"yes_stake,omitempty"`
	NoStake       string                 `protobuf:"bytes,2,opt,name=no_stake,json=noStake,proto3" json:"no_stake,omitempty"`
	AbstainStake  string                 `protobuf:"bytes,3,opt,name=abstain_stake,json=abstainStake,proto3" json:"abstain_stake,omitempty"`
	QuorumMet     bool                   `protobuf:"varint,4,opt,name=quorum_met,json=quorumMet,proto3" json:"quorum_met,omitempty"`
	Passed        bool                   `protobuf:"varint,5,opt,name=passed,proto3" json:"passed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultResponse) Reset() {
	*x = QueryTallyResultResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultResponse) ProtoMessage() {}

func (x *QueryTallyResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultResponse.ProtoReflect.Descriptor instead.
func (*QueryTallyResultResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryTallyResultResponse) GetYesStake() string {
	if x != nil {
		return x.YesStake
	}
	return ""
}

func (x *QueryTallyResultResponse) GetNoStake() string {
	if x != nil {
		return x.NoStake
	}
	return ""
}

func (x *QueryTallyResultResponse) GetAbstainStake() string {
	if x != nil {
		return x.AbstainStake
	}
	return ""
}

func (x *QueryTallyResultResponse) GetQuorumMet() bool {
	if x != nil {
		return x.QuorumMet
	}
	return false
}

func (x *QueryTallyResultResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{10}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryResearchSpendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    uint64                 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchSpendRequest) Reset() {
	*x = QueryResearchSpendRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchSpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchSpendRequest) ProtoMessage() {}

func (x *QueryResearchSpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchSpendRequest.ProtoReflect.Descriptor instead.
func (*QueryResearchSpendRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResearchSpendRequest) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type QueryResearchSpendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *ResearchSpendProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchSpendResponse) Reset() {
	*x = QueryResearchSpendResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchSpendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchSpendResponse) ProtoMessage() {}

func (x *QueryResearchSpendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchSpendResponse.ProtoReflect.Descriptor instead.
func (*QueryResearchSpendResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryResearchSpendResponse) GetProposal() *ResearchSpendProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type QueryResearchSpendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchSpendsRequest) Reset() {
	*x = QueryResearchSpendsRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchSpendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchSpendsRequest) ProtoMessage() {}

func (x *QueryResearchSpendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchSpendsRequest.ProtoReflect.Descriptor instead.
func (*QueryResearchSpendsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResearchSpendsRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *QueryResearchSpendsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryResearchSpendsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryResearchSpendsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Proposals     []*ResearchSpendProposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	Total         uint64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchSpendsResponse) Reset() {
	*x = QueryResearchSpendsResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchSpendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchSpendsResponse) ProtoMessage() {}

func (x *QueryResearchSpendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchSpendsResponse.ProtoReflect.Descriptor instead.
func (*QueryResearchSpendsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryResearchSpendsResponse) GetProposals() []*ResearchSpendProposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *QueryResearchSpendsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QueryResearchVotersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchVotersRequest) Reset() {
	*x = QueryResearchVotersRequest{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchVotersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchVotersRequest) ProtoMessage() {}

func (x *QueryResearchVotersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchVotersRequest.ProtoReflect.Descriptor instead.
func (*QueryResearchVotersRequest) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{16}
}

type QueryResearchVotersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        *ResearchFundVoters    `protobuf:"bytes,1,opt,name=voters,proto3" json:"voters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResearchVotersResponse) Reset() {
	*x = QueryResearchVotersResponse{}
	mi := &file_zerone_gov_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResearchVotersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResearchVotersResponse) ProtoMessage() {}

func (x *QueryResearchVotersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_gov_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResearchVotersResponse.ProtoReflect.Descriptor instead.
func (*QueryResearchVotersResponse) Descriptor() ([]byte, []int) {
	return file_zerone_gov_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryResearchVotersResponse) GetVoters() *ResearchFundVoters {
	if x != nil {
		return x.Voters
	}
	return nil
}

var File_zerone_gov_v1_query_proto protoreflect.FileDescriptor

const file_zerone_gov_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x19zerone/gov/v1/query.proto\x12\rzerone.gov.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19zerone/gov/v1/types.proto\x1a\x1bzerone/gov/v1/genesis.proto\"(\n" +
	"\x0fQueryLIPRequest\x12\x15\n" +
	"\x06lip_id\x18\x01 \x01(\tR\x05lipId\"c\n" +
	"\x10QueryLIPResponse\x12$\n" +
	"\x03lip\x18\x01 \x01(\v2\x12.zerone.gov.v1.LIPR\x03lip\x12)\n" +
	"\x05votes\x18\x02 \x03(\v2\x13.zerone.gov.v1.VoteR\x05votes\"t\n" +
	"\x10QueryLIPsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\"Q\n" +
	"\x11QueryLIPsResponse\x12&\n" +
	"\x04lips\x18\x01 \x03(\v2\x12.zerone.gov.v1.LIPR\x04lips\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"?\n" +
	"\x10QueryVoteRequest\x12\x15\n" +
	"\x06lip_id\x18\x01 \x01(\tR\x05lipId\x12\x14\n" +
	"\x05voter\x18\x02 \x01(\tR\x05voter\"<\n" +
	"\x11QueryVoteResponse\x12'\n" +
	"\x04vote\x18\x01 \x01(\v2\x13.zerone.gov.v1.VoteR\x04vote\"*\n" +
	"\x11QueryVotesRequest\x12\x15\n" +
	"\x06lip_id\x18\x01 \x01(\tR\x05lipId\"?\n" +
	"\x12QueryVotesResponse\x12)\n" +
	"\x05votes\x18\x01 \x03(\v2\x13.zerone.gov.v1.VoteR\x05votes\"0\n" +
	"\x17QueryTallyResultRequest\x12\x15\n" +
	"\x06lip_id\x18\x01 \x01(\tR\x05lipId\"\xae\x01\n" +
	"\x18QueryTallyResultResponse\x12\x1b\n" +
	"\tyes_stake\x18\x01 \x01(\tR\byesStake\x12\x19\n" +
	"\bno_stake\x18\x02 \x01(\tR\anoStake\x12#\n" +
	"\rabstain_stake\x18\x03 \x01(\tR\fabstainStake\x12\x1d\n" +
	"\n" +
	"quorum_met\x18\x04 \x01(\bR\tquorumMet\x12\x16\n" +
	"\x06passed\x18\x05 \x01(\bR\x06passed\"\x14\n" +
	"\x12QueryParamsRequest\"D\n" +
	"\x13QueryParamsResponse\x12-\n" +
	"\x06params\x18\x01 \x01(\v2\x15.zerone.gov.v1.ParamsR\x06params\"<\n" +
	"\x19QueryResearchSpendRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x04R\n" +
	"proposalId\"^\n" +
	"\x1aQueryResearchSpendResponse\x12@\n" +
	"\bproposal\x18\x01 \x01(\v2$.zerone.gov.v1.ResearchSpendProposalR\bproposal\"`\n" +
	"\x1aQueryResearchSpendsRequest\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"w\n" +
	"\x1bQueryResearchSpendsResponse\x12B\n" +
	"\tproposals\x18\x01 \x03(\v2$.zerone.gov.v1.ResearchSpendProposalR\tproposals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"\x1c\n" +
	"\x1aQueryResearchVotersRequest\"X\n" +
	"\x1bQueryResearchVotersResponse\x129\n" +
	"\x06voters\x18\x01 \x01(\v2!.zerone.gov.v1.ResearchFundVotersR\x06voters2\x8e\t\n" +
	"\x05Query\x12k\n" +
	"\x03LIP\x12\x1e.zerone.gov.v1.QueryLIPRequest\x1a\x1f.zerone.gov.v1.QueryLIPResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/zerone/gov/v1/lip/{lip_id}\x12f\n" +
	"\x04LIPs\x12\x1f.zerone.gov.v1.QueryLIPsRequest\x1a .zerone.gov.v1.QueryLIPsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/zerone/gov/v1/lips\x12{\n" +
	"\x04Vote\x12\x1f.zerone.gov.v1.QueryVoteRequest\x1a .zerone.gov.v1.QueryVoteResponse\"0\x82\xd3\xe4\x93\x02*\x12(/zerone/gov/v1/lip/{lip_id}/vote/{voter}\x12w\n" +
	"\x05Votes\x12 .zerone.gov.v1.QueryVotesRequest\x1a!.zerone.gov.v1.QueryVotesResponse\")\x82\xd3\xe4\x93\x02#\x12!/zerone/gov/v1/lip/{lip_id}/votes\x12\x89\x01\n" +
	"\vTallyResult\x12&.zerone.gov.v1.QueryTallyResultRequest\x1a'.zerone.gov.v1.QueryTallyResultResponse\")\x82\xd3\xe4\x93\x02#\x12!/zerone/gov/v1/lip/{lip_id}/tally\x12n\n" +
	"\x06Params\x12!.zerone.gov.v1.QueryParamsRequest\x1a\".zerone.gov.v1.QueryParamsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/zerone/gov/v1/params\x12\x99\x01\n" +
	"\rResearchSpend\x12(.zerone.gov.v1.QueryResearchSpendRequest\x1a).zerone.gov.v1.QueryResearchSpendResponse\"3\x82\xd3\xe4\x93\x02-\x12+/zerone/gov/v1/research_spend/{proposal_id}\x12\x8f\x01\n" +
	"\x0eResearchSpends\x12).zerone.gov.v1.QueryResearchSpendsRequest\x1a*.zerone.gov.v1.QueryResearchSpendsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/zerone/gov/v1/research_spends\x12\x8f\x01\n" +
	"\x0eResearchVoters\x12).zerone.gov.v1.QueryResearchVotersRequest\x1a*.zerone.gov.v1.QueryResearchVotersResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/zerone/gov/v1/research_votersB,Z*github.com/zerone-chain/zerone/x/gov/typesb\x06proto3"

var (
	file_zerone_gov_v1_query_proto_rawDescOnce sync.Once
	file_zerone_gov_v1_query_proto_rawDescData []byte
)

func file_zerone_gov_v1_query_proto_rawDescGZIP() []byte {
	file_zerone_gov_v1_query_proto_rawDescOnce.Do(func() {
		file_zerone_gov_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_gov_v1_query_proto_rawDesc), len(file_zerone_gov_v1_query_proto_rawDesc)))
	})
	return file_zerone_gov_v1_query_proto_rawDescData
}

var file_zerone_gov_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_zerone_gov_v1_query_proto_goTypes = []any{
	(*QueryLIPRequest)(nil),             // 0: zerone.gov.v1.QueryLIPRequest
	(*QueryLIPResponse)(nil),            // 1: zerone.gov.v1.QueryLIPResponse
	(*QueryLIPsRequest)(nil),            // 2: zerone.gov.v1.QueryLIPsRequest
	(*QueryLIPsResponse)(nil),           // 3: zerone.gov.v1.QueryLIPsResponse
	(*QueryVoteRequest)(nil),            // 4: zerone.gov.v1.QueryVoteRequest
	(*QueryVoteResponse)(nil),           // 5: zerone.gov.v1.QueryVoteResponse
	(*QueryVotesRequest)(nil),           // 6: zerone.gov.v1.QueryVotesRequest
	(*QueryVotesResponse)(nil),          // 7: zerone.gov.v1.QueryVotesResponse
	(*QueryTallyResultRequest)(nil),     // 8: zerone.gov.v1.QueryTallyResultRequest
	(*QueryTallyResultResponse)(nil),    // 9: zerone.gov.v1.QueryTallyResultResponse
	(*QueryParamsRequest)(nil),          // 10: zerone.gov.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),         // 11: zerone.gov.v1.QueryParamsResponse
	(*QueryResearchSpendRequest)(nil),   // 12: zerone.gov.v1.QueryResearchSpendRequest
	(*QueryResearchSpendResponse)(nil),  // 13: zerone.gov.v1.QueryResearchSpendResponse
	(*QueryResearchSpendsRequest)(nil),  // 14: zerone.gov.v1.QueryResearchSpendsRequest
	(*QueryResearchSpendsResponse)(nil), // 15: zerone.gov.v1.QueryResearchSpendsResponse
	(*QueryResearchVotersRequest)(nil),  // 16: zerone.gov.v1.QueryResearchVotersRequest
	(*QueryResearchVotersResponse)(nil), // 17: zerone.gov.v1.QueryResearchVotersResponse
	(*LIP)(nil),                         // 18: zerone.gov.v1.LIP
	(*Vote)(nil),                        // 19: zerone.gov.v1.Vote
	(*Params)(nil),                      // 20: zerone.gov.v1.Params
	(*ResearchSpendProposal)(nil),       // 21: zerone.gov.v1.ResearchSpendProposal
	(*ResearchFundVoters)(nil),          // 22: zerone.gov.v1.ResearchFundVoters
}
var file_zerone_gov_v1_query_proto_depIdxs = []int32{
	18, // 0: zerone.gov.v1.QueryLIPResponse.lip:type_name -> zerone.gov.v1.LIP
	19, // 1: zerone.gov.v1.QueryLIPResponse.votes:type_name -> zerone.gov.v1.Vote
	18, // 2: zerone.gov.v1.QueryLIPsResponse.lips:type_name -> zerone.gov.v1.LIP
	19, // 3: zerone.gov.v1.QueryVoteResponse.vote:type_name -> zerone.gov.v1.Vote
	19, // 4: zerone.gov.v1.QueryVotesResponse.votes:type_name -> zerone.gov.v1.Vote
	20, // 5: zerone.gov.v1.QueryParamsResponse.params:type_name -> zerone.gov.v1.Params
	21, // 6: zerone.gov.v1.QueryResearchSpendResponse.proposal:type_name -> zerone.gov.v1.ResearchSpendProposal
	21, // 7: zerone.gov.v1.QueryResearchSpendsResponse.proposals:type_name -> zerone.gov.v1.ResearchSpendProposal
	22, // 8: zerone.gov.v1.QueryResearchVotersResponse.voters:type_name -> zerone.gov.v1.ResearchFundVoters
	0,  // 9: zerone.gov.v1.Query.LIP:input_type -> zerone.gov.v1.QueryLIPRequest
	2,  // 10: zerone.gov.v1.Query.LIPs:input_type -> zerone.gov.v1.QueryLIPsRequest
	4,  // 11: zerone.gov.v1.Query.Vote:input_type -> zerone.gov.v1.QueryVoteRequest
	6,  // 12: zerone.gov.v1.Query.Votes:input_type -> zerone.gov.v1.QueryVotesRequest
	8,  // 13: zerone.gov.v1.Query.TallyResult:input_type -> zerone.gov.v1.QueryTallyResultRequest
	10, // 14: zerone.gov.v1.Query.Params:input_type -> zerone.gov.v1.QueryParamsRequest
	12, // 15: zerone.gov.v1.Query.ResearchSpend:input_type -> zerone.gov.v1.QueryResearchSpendRequest
	14, // 16: zerone.gov.v1.Query.ResearchSpends:input_type -> zerone.gov.v1.QueryResearchSpendsRequest
	16, // 17: zerone.gov.v1.Query.ResearchVoters:input_type -> zerone.gov.v1.QueryResearchVotersRequest
	1,  // 18: zerone.gov.v1.Query.LIP:output_type -> zerone.gov.v1.QueryLIPResponse
	3,  // 19: zerone.gov.v1.Query.LIPs:output_type -> zerone.gov.v1.QueryLIPsResponse
	5,  // 20: zerone.gov.v1.Query.Vote:output_type -> zerone.gov.v1.QueryVoteResponse
	7,  // 21: zerone.gov.v1.Query.Votes:output_type -> zerone.gov.v1.QueryVotesResponse
	9,  // 22: zerone.gov.v1.Query.TallyResult:output_type -> zerone.gov.v1.QueryTallyResultResponse
	11, // 23: zerone.gov.v1.Query.Params:output_type -> zerone.gov.v1.QueryParamsResponse
	13, // 24: zerone.gov.v1.Query.ResearchSpend:output_type -> zerone.gov.v1.QueryResearchSpendResponse
	15, // 25: zerone.gov.v1.Query.ResearchSpends:output_type -> zerone.gov.v1.QueryResearchSpendsResponse
	17, // 26: zerone.gov.v1.Query.ResearchVoters:output_type -> zerone.gov.v1.QueryResearchVotersResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_zerone_gov_v1_query_proto_init() }
func file_zerone_gov_v1_query_proto_init() {
	if File_zerone_gov_v1_query_proto != nil {
		return
	}
	file_zerone_gov_v1_types_proto_init()
	file_zerone_gov_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_gov_v1_query_proto_rawDesc), len(file_zerone_gov_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_gov_v1_query_proto_goTypes,
		DependencyIndexes: file_zerone_gov_v1_query_proto_depIdxs,
		MessageInfos:      file_zerone_gov_v1_query_proto_msgTypes,
	}.Build()
	File_zerone_gov_v1_query_proto = out.File
	file_zerone_gov_v1_query_proto_goTypes = nil
	file_zerone_gov_v1_query_proto_depIdxs = nil
}
