// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/evidence_mgmt/v1/state.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceType int32

const (
	EvidenceType_EVIDENCE_TYPE_UNSPECIFIED EvidenceType = 0
	EvidenceType_EVIDENCE_TYPE_DOCUMENT    EvidenceType = 1
	EvidenceType_EVIDENCE_TYPE_ATTESTATION EvidenceType = 2
	EvidenceType_EVIDENCE_TYPE_MEASUREMENT EvidenceType = 3
	EvidenceType_EVIDENCE_TYPE_COMPUTATION EvidenceType = 4
)

// Enum value maps for EvidenceType.
var (
	EvidenceType_name = map[int32]string{
		0: "EVIDENCE_TYPE_UNSPECIFIED",
		1: "EVIDENCE_TYPE_DOCUMENT",
		2: "EVIDENCE_TYPE_ATTESTATION",
		3: "EVIDENCE_TYPE_MEASUREMENT",
		4: "EVIDENCE_TYPE_COMPUTATION",
	}
	EvidenceType_value = map[string]int32{
		"EVIDENCE_TYPE_UNSPECIFIED": 0,
		"EVIDENCE_TYPE_DOCUMENT":    1,
		"EVIDENCE_TYPE_ATTESTATION": 2,
		"EVIDENCE_TYPE_MEASUREMENT": 3,
		"EVIDENCE_TYPE_COMPUTATION": 4,
	}
)

func (x EvidenceType) Enum() *EvidenceType {
	p := new(EvidenceType)
	*p = x
	return p
}

func (x EvidenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_zerone_evidence_mgmt_v1_state_proto_enumTypes[0].Descriptor()
}

func (EvidenceType) Type() protoreflect.EnumType {
	return &file_zerone_evidence_mgmt_v1_state_proto_enumTypes[0]
}

func (x EvidenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceType.Descriptor instead.
func (EvidenceType) EnumDescriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{0}
}

type EvidenceStatus int32

const (
	EvidenceStatus_EVIDENCE_STATUS_UNSPECIFIED EvidenceStatus = 0
	EvidenceStatus_EVIDENCE_STATUS_SUBMITTED   EvidenceStatus = 1
	EvidenceStatus_EVIDENCE_STATUS_VERIFIED    EvidenceStatus = 2
	EvidenceStatus_EVIDENCE_STATUS_CHALLENGED  EvidenceStatus = 3
	EvidenceStatus_EVIDENCE_STATUS_REJECTED    EvidenceStatus = 4
)

// Enum value maps for EvidenceStatus.
var (
	EvidenceStatus_name = map[int32]string{
		0: "EVIDENCE_STATUS_UNSPECIFIED",
		1: "EVIDENCE_STATUS_SUBMITTED",
		2: "EVIDENCE_STATUS_VERIFIED",
		3: "EVIDENCE_STATUS_CHALLENGED",
		4: "EVIDENCE_STATUS_REJECTED",
	}
	EvidenceStatus_value = map[string]int32{
		"EVIDENCE_STATUS_UNSPECIFIED": 0,
		"EVIDENCE_STATUS_SUBMITTED":   1,
		"EVIDENCE_STATUS_VERIFIED":    2,
		"EVIDENCE_STATUS_CHALLENGED":  3,
		"EVIDENCE_STATUS_REJECTED":    4,
	}
)

func (x EvidenceStatus) Enum() *EvidenceStatus {
	p := new(EvidenceStatus)
	*p = x
	return p
}

func (x EvidenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zerone_evidence_mgmt_v1_state_proto_enumTypes[1].Descriptor()
}

func (EvidenceStatus) Type() protoreflect.EnumType {
	return &file_zerone_evidence_mgmt_v1_state_proto_enumTypes[1]
}

func (x EvidenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceStatus.Descriptor instead.
func (EvidenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{1}
}

type Evidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Submitter      string                 `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"` // bech32
	EvidenceType   EvidenceType           `protobuf:"varint,3,opt,name=evidence_type,json=evidenceType,proto3,enum=zerone.evidence_mgmt.v1.EvidenceType" json:"evidence_type,omitempty"`
	ContentHash    string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // SHA256 of evidence content
	Metadata       string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                          // JSON metadata
	ChainOfCustody []*ChainOfCustodyEntry `protobuf:"bytes,6,rep,name=chain_of_custody,json=chainOfCustody,proto3" json:"chain_of_custody,omitempty"`
	Status         EvidenceStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=zerone.evidence_mgmt.v1.EvidenceStatus" json:"status,omitempty"`
	CreatedAtBlock uint64                 `protobuf:"varint,8,opt,name=created_at_block,json=createdAtBlock,proto3" json:"created_at_block,omitempty"`
	UpdatedAtBlock uint64                 `protobuf:"varint,9,opt,name=updated_at_block,json=updatedAtBlock,proto3" json:"updated_at_block,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *Evidence) GetEvidenceType() EvidenceType {
	if x != nil {
		return x.EvidenceType
	}
	return EvidenceType_EVIDENCE_TYPE_UNSPECIFIED
}

func (x *Evidence) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Evidence) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Evidence) GetChainOfCustody() []*ChainOfCustodyEntry {
	if x != nil {
		return x.ChainOfCustody
	}
	return nil
}

func (x *Evidence) GetStatus() EvidenceStatus {
	if x != nil {
		return x.Status
	}
	return EvidenceStatus_EVIDENCE_STATUS_UNSPECIFIED
}

func (x *Evidence) GetCreatedAtBlock() uint64 {
	if x != nil {
		return x.CreatedAtBlock
	}
	return 0
}

func (x *Evidence) GetUpdatedAtBlock() uint64 {
	if x != nil {
		return x.UpdatedAtBlock
	}
	return 0
}

type ChainOfCustodyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Custodian     string                 `protobuf:"bytes,1,opt,name=custodian,proto3" json:"custodian,omitempty"`  // bech32
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`        // "submit", "transfer", "verify", "challenge"
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // block height
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainOfCustodyEntry) Reset() {
	*x = ChainOfCustodyEntry{}
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainOfCustodyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainOfCustodyEntry) ProtoMessage() {}

func (x *ChainOfCustodyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainOfCustodyEntry.ProtoReflect.Descriptor instead.
func (*ChainOfCustodyEntry) Descriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *ChainOfCustodyEntry) GetCustodian() string {
	if x != nil {
		return x.Custodian
	}
	return ""
}

func (x *ChainOfCustodyEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ChainOfCustodyEntry) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChainOfCustodyEntry) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type VerificationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EvidenceId    string                 `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	Verifier      string                 `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`      // bech32
	Outcome       bool                   `protobuf:"varint,4,opt,name=outcome,proto3" json:"outcome,omitempty"`       // true = verified, false = rejected
	Confidence    uint32                 `protobuf:"varint,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0-1000000 (1M scale)
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`          // verification method description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerificationResult) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *VerificationResult) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *VerificationResult) GetOutcome() bool {
	if x != nil {
		return x.Outcome
	}
	return false
}

func (x *VerificationResult) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VerificationResult) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Params struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MinVerifierTier       uint32                 `protobuf:"varint,1,opt,name=min_verifier_tier,json=minVerifierTier,proto3" json:"min_verifier_tier,omitempty"`                   // default: 2
	VerificationQuorum    uint32                 `protobuf:"varint,2,opt,name=verification_quorum,json=verificationQuorum,proto3" json:"verification_quorum,omitempty"`            // default: 3
	ChallengeBond         string                 `protobuf:"bytes,3,opt,name=challenge_bond,json=challengeBond,proto3" json:"challenge_bond,omitempty"`                            // default: "500000" uzrn
	ChallengeWindowBlocks uint64                 `protobuf:"varint,4,opt,name=challenge_window_blocks,json=challengeWindowBlocks,proto3" json:"challenge_window_blocks,omitempty"` // default: 50000
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_evidence_mgmt_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *Params) GetMinVerifierTier() uint32 {
	if x != nil {
		return x.MinVerifierTier
	}
	return 0
}

func (x *Params) GetVerificationQuorum() uint32 {
	if x != nil {
		return x.VerificationQuorum
	}
	return 0
}

func (x *Params) GetChallengeBond() string {
	if x != nil {
		return x.ChallengeBond
	}
	return ""
}

func (x *Params) GetChallengeWindowBlocks() uint64 {
	if x != nil {
		return x.ChallengeWindowBlocks
	}
	return 0
}

var File_zerone_evidence_mgmt_v1_state_proto protoreflect.FileDescriptor

const file_zerone_evidence_mgmt_v1_state_proto_rawDesc = "" +
	"\n" +
	"#zerone/evidence_mgmt/v1/state.proto\x12\x17zerone.evidence_mgmt.v1\"\xb0\x03\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tsubmitter\x18\x02 \x01(\tR\tsubmitter\x12J\n" +
	"\revidence_type\x18\x03 \x01(\x0e2%.zerone.evidence_mgmt.v1.EvidenceTypeR\fevidenceType\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\x12V\n" +
	"\x10chain_of_custody\x18\x06 \x03(\v2,.zerone.evidence_mgmt.v1.ChainOfCustodyEntryR\x0echainOfCustody\x12?\n" +
	"\x06status\x18\a \x01(\x0e2'.zerone.evidence_mgmt.v1.EvidenceStatusR\x06status\x12(\n" +
	"\x10created_at_block\x18\b \x01(\x04R\x0ecreatedAtBlock\x12(\n" +
	"\x10updated_at_block\x18\t \x01(\x04R\x0eupdatedAtBlock\"\x7f\n" +
	"\x13ChainOfCustodyEntry\x12\x1c\n" +
	"\tcustodian\x18\x01 \x01(\tR\tcustodian\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"\xb3\x01\n" +
	"\x12VerificationResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vevidence_id\x18\x02 \x01(\tR\n" +
	"evidenceId\x12\x1a\n" +
	"\bverifier\x18\x03 \x01(\tR\bverifier\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\bR\aoutcome\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\rR\n" +
	"confidence\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\"\xc4\x01\n" +
	"\x06Params\x12*\n" +
	"\x11min_verifier_tier\x18\x01 \x01(\rR\x0fminVerifierTier\x12/\n" +
	"\x13verification_quorum\x18\x02 \x01(\rR\x12verificationQuorum\x12%\n" +
	"\x0echallenge_bond\x18\x03 \x01(\tR\rchallengeBond\x126\n" +
	"\x17challenge_window_blocks\x18\x04 \x01(\x04R\x15challengeWindowBlocks*\xa6\x01\n" +
	"\fEvidenceType\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVIDENCE_TYPE_DOCUMENT\x10\x01\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_ATTESTATION\x10\x02\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_MEASUREMENT\x10\x03\x12\x1d\n" +
	"\x19EVIDENCE_TYPE_COMPUTATION\x10\x04*\xac\x01\n" +
	"\x0eEvidenceStatus\x12\x1f\n" +
	"\x1bEVIDENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EVIDENCE_STATUS_SUBMITTED\x10\x01\x12\x1c\n" +
	"\x18EVIDENCE_STATUS_VERIFIED\x10\x02\x12\x1e\n" +
	"\x1aEVIDENCE_STATUS_CHALLENGED\x10\x03\x12\x1c\n" +
	"\x18EVIDENCE_STATUS_REJECTED\x10\x04B6Z4github.com/zerone-chain/zerone/x/evidence_mgmt/typesb\x06proto3"

var (
	file_zerone_evidence_mgmt_v1_state_proto_rawDescOnce sync.Once
	file_zerone_evidence_mgmt_v1_state_proto_rawDescData []byte
)

func file_zerone_evidence_mgmt_v1_state_proto_rawDescGZIP() []byte {
	file_zerone_evidence_mgmt_v1_state_proto_rawDescOnce.Do(func() {
		file_zerone_evidence_mgmt_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_evidence_mgmt_v1_state_proto_rawDesc), len(file_zerone_evidence_mgmt_v1_state_proto_rawDesc)))
	})
	return file_zerone_evidence_mgmt_v1_state_proto_rawDescData
}

var file_zerone_evidence_mgmt_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zerone_evidence_mgmt_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zerone_evidence_mgmt_v1_state_proto_goTypes = []any{
	(EvidenceType)(0),           // 0: zerone.evidence_mgmt.v1.EvidenceType
	(EvidenceStatus)(0),         // 1: zerone.evidence_mgmt.v1.EvidenceStatus
	(*Evidence)(nil),            // 2: zerone.evidence_mgmt.v1.Evidence
	(*ChainOfCustodyEntry)(nil), // 3: zerone.evidence_mgmt.v1.ChainOfCustodyEntry
	(*VerificationResult)(nil),  // 4: zerone.evidence_mgmt.v1.VerificationResult
	(*Params)(nil),              // 5: zerone.evidence_mgmt.v1.Params
}
var file_zerone_evidence_mgmt_v1_state_proto_depIdxs = []int32{
	0, // 0: zerone.evidence_mgmt.v1.Evidence.evidence_type:type_name -> zerone.evidence_mgmt.v1.EvidenceType
	3, // 1: zerone.evidence_mgmt.v1.Evidence.chain_of_custody:type_name -> zerone.evidence_mgmt.v1.ChainOfCustodyEntry
	1, // 2: zerone.evidence_mgmt.v1.Evidence.status:type_name -> zerone.evidence_mgmt.v1.EvidenceStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zerone_evidence_mgmt_v1_state_proto_init() }
func file_zerone_evidence_mgmt_v1_state_proto_init() {
	if File_zerone_evidence_mgmt_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_evidence_mgmt_v1_state_proto_rawDesc), len(file_zerone_evidence_mgmt_v1_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_evidence_mgmt_v1_state_proto_goTypes,
		DependencyIndexes: file_zerone_evidence_mgmt_v1_state_proto_depIdxs,
		EnumInfos:         file_zerone_evidence_mgmt_v1_state_proto_enumTypes,
		MessageInfos:      file_zerone_evidence_mgmt_v1_state_proto_msgTypes,
	}.Build()
	File_zerone_evidence_mgmt_v1_state_proto = out.File
	file_zerone_evidence_mgmt_v1_state_proto_goTypes = nil
	file_zerone_evidence_mgmt_v1_state_proto_depIdxs = nil
}
