// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/dialectic/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VoterPosition is one validator's stance in a verification round,
// classified relative to the round's final verdict.
type VoterPosition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Voter              string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`                                                        // bech32
	Vote               string                 `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`                                                          // "accept" / "reject" / "malformed"
	AlignedWithVerdict bool                   `protobuf:"varint,3,opt,name=aligned_with_verdict,json=alignedWithVerdict,proto3" json:"aligned_with_verdict,omitempty"` // true if vote == verdict
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VoterPosition) Reset() {
	*x = VoterPosition{}
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoterPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterPosition) ProtoMessage() {}

func (x *VoterPosition) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterPosition.ProtoReflect.Descriptor instead.
func (*VoterPosition) Descriptor() ([]byte, []int) {
	return file_zerone_dialectic_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *VoterPosition) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *VoterPosition) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *VoterPosition) GetAlignedWithVerdict() bool {
	if x != nil {
		return x.AlignedWithVerdict
	}
	return false
}

// DialecticSignature is the structural shape of how a fact arrived
// at its current state — not just "was it accepted" but "with what
// disagreement structure." Two facts both ACCEPTED can have very
// different signatures: 5-0 vs 5-4. Downstream consumers (training
// pipelines, analysts) treat them differently.
type DialecticSignature struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FactId  string                 `protobuf:"bytes,1,opt,name=fact_id,json=factId,proto3" json:"fact_id,omitempty"`
	RoundId string                 `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	// Vote tally.
	TotalVoters    uint32 `protobuf:"varint,3,opt,name=total_voters,json=totalVoters,proto3" json:"total_voters,omitempty"`
	AcceptCount    uint32 `protobuf:"varint,4,opt,name=accept_count,json=acceptCount,proto3" json:"accept_count,omitempty"`
	RejectCount    uint32 `protobuf:"varint,5,opt,name=reject_count,json=rejectCount,proto3" json:"reject_count,omitempty"`
	MalformedCount uint32 `protobuf:"varint,6,opt,name=malformed_count,json=malformedCount,proto3" json:"malformed_count,omitempty"`
	// Verdict that won. "accept" / "reject" / "malformed" /
	// "unspecified" if the round produced no verdict.
	Verdict string `protobuf:"bytes,7,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// Winning-side fraction in basis points (1,000,000 = unanimous).
	// < 700k indicates contested-but-resolved territory.
	AgreementBps uint64 `protobuf:"varint,8,opt,name=agreement_bps,json=agreementBps,proto3" json:"agreement_bps,omitempty"`
	// Voters whose vote did NOT align with the verdict.
	MinoritySize uint32 `protobuf:"varint,9,opt,name=minority_size,json=minoritySize,proto3" json:"minority_size,omitempty"`
	// Per-voter breakdown. Sorted by voter for determinism.
	VoterPositions []*VoterPosition `protobuf:"bytes,10,rep,name=voter_positions,json=voterPositions,proto3" json:"voter_positions,omitempty"`
	// Computed stress label for quick interpretation:
	//
	//	"UNANIMOUS"   — agreement_bps == 1,000,000
	//	"STRONG"      — >= 0.85 agreement
	//	"CONTESTED"   — 0.55..0.85
	//	"BARE"        — < 0.55 (barely passed)
	//	"NO_VERDICT"  — round did not resolve
	StressLabel   string `protobuf:"bytes,11,opt,name=stress_label,json=stressLabel,proto3" json:"stress_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialecticSignature) Reset() {
	*x = DialecticSignature{}
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialecticSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialecticSignature) ProtoMessage() {}

func (x *DialecticSignature) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialecticSignature.ProtoReflect.Descriptor instead.
func (*DialecticSignature) Descriptor() ([]byte, []int) {
	return file_zerone_dialectic_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *DialecticSignature) GetFactId() string {
	if x != nil {
		return x.FactId
	}
	return ""
}

func (x *DialecticSignature) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *DialecticSignature) GetTotalVoters() uint32 {
	if x != nil {
		return x.TotalVoters
	}
	return 0
}

func (x *DialecticSignature) GetAcceptCount() uint32 {
	if x != nil {
		return x.AcceptCount
	}
	return 0
}

func (x *DialecticSignature) GetRejectCount() uint32 {
	if x != nil {
		return x.RejectCount
	}
	return 0
}

func (x *DialecticSignature) GetMalformedCount() uint32 {
	if x != nil {
		return x.MalformedCount
	}
	return 0
}

func (x *DialecticSignature) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *DialecticSignature) GetAgreementBps() uint64 {
	if x != nil {
		return x.AgreementBps
	}
	return 0
}

func (x *DialecticSignature) GetMinoritySize() uint32 {
	if x != nil {
		return x.MinoritySize
	}
	return 0
}

func (x *DialecticSignature) GetVoterPositions() []*VoterPosition {
	if x != nil {
		return x.VoterPositions
	}
	return nil
}

func (x *DialecticSignature) GetStressLabel() string {
	if x != nil {
		return x.StressLabel
	}
	return ""
}

// DomainDialectic rolls up per-domain disagreement statistics.
// Computed at query time over all facts in the domain.
type DomainDialectic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Domain            string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	FactsExamined     uint64                 `protobuf:"varint,2,opt,name=facts_examined,json=factsExamined,proto3" json:"facts_examined,omitempty"`
	UnanimousFacts    uint64                 `protobuf:"varint,3,opt,name=unanimous_facts,json=unanimousFacts,proto3" json:"unanimous_facts,omitempty"`
	ContestedFacts    uint64                 `protobuf:"varint,4,opt,name=contested_facts,json=contestedFacts,proto3" json:"contested_facts,omitempty"`            // agreement_bps < 850k
	BareMajorityFacts uint64                 `protobuf:"varint,5,opt,name=bare_majority_facts,json=bareMajorityFacts,proto3" json:"bare_majority_facts,omitempty"` // agreement_bps < 550k
	// Average agreement BPS across all facts examined. 0 if no facts.
	AvgAgreementBps uint64 `protobuf:"varint,6,opt,name=avg_agreement_bps,json=avgAgreementBps,proto3" json:"avg_agreement_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainDialectic) Reset() {
	*x = DomainDialectic{}
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainDialectic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainDialectic) ProtoMessage() {}

func (x *DomainDialectic) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainDialectic.ProtoReflect.Descriptor instead.
func (*DomainDialectic) Descriptor() ([]byte, []int) {
	return file_zerone_dialectic_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *DomainDialectic) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainDialectic) GetFactsExamined() uint64 {
	if x != nil {
		return x.FactsExamined
	}
	return 0
}

func (x *DomainDialectic) GetUnanimousFacts() uint64 {
	if x != nil {
		return x.UnanimousFacts
	}
	return 0
}

func (x *DomainDialectic) GetContestedFacts() uint64 {
	if x != nil {
		return x.ContestedFacts
	}
	return 0
}

func (x *DomainDialectic) GetBareMajorityFacts() uint64 {
	if x != nil {
		return x.BareMajorityFacts
	}
	return 0
}

func (x *DomainDialectic) GetAvgAgreementBps() uint64 {
	if x != nil {
		return x.AvgAgreementBps
	}
	return 0
}

// AgentPairwiseDisagreement: how often two agents have disagreed
// when they both voted on the same round. The chain doesn't pass
// judgment — high disagreement might mean two agents see the world
// differently in productive ways. The signature is data for
// downstream analysis.
type AgentPairwiseDisagreement struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentA              string                 `protobuf:"bytes,1,opt,name=agent_a,json=agentA,proto3" json:"agent_a,omitempty"`
	AgentB              string                 `protobuf:"bytes,2,opt,name=agent_b,json=agentB,proto3" json:"agent_b,omitempty"`
	RoundsBothVoted     uint32                 `protobuf:"varint,3,opt,name=rounds_both_voted,json=roundsBothVoted,proto3" json:"rounds_both_voted,omitempty"`
	Disagreements       uint32                 `protobuf:"varint,4,opt,name=disagreements,proto3" json:"disagreements,omitempty"`
	DisagreementRateBps uint64                 `protobuf:"varint,5,opt,name=disagreement_rate_bps,json=disagreementRateBps,proto3" json:"disagreement_rate_bps,omitempty"` // disagreements / rounds_both_voted × 1M
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentPairwiseDisagreement) Reset() {
	*x = AgentPairwiseDisagreement{}
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPairwiseDisagreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPairwiseDisagreement) ProtoMessage() {}

func (x *AgentPairwiseDisagreement) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_dialectic_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPairwiseDisagreement.ProtoReflect.Descriptor instead.
func (*AgentPairwiseDisagreement) Descriptor() ([]byte, []int) {
	return file_zerone_dialectic_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *AgentPairwiseDisagreement) GetAgentA() string {
	if x != nil {
		return x.AgentA
	}
	return ""
}

func (x *AgentPairwiseDisagreement) GetAgentB() string {
	if x != nil {
		return x.AgentB
	}
	return ""
}

func (x *AgentPairwiseDisagreement) GetRoundsBothVoted() uint32 {
	if x != nil {
		return x.RoundsBothVoted
	}
	return 0
}

func (x *AgentPairwiseDisagreement) GetDisagreements() uint32 {
	if x != nil {
		return x.Disagreements
	}
	return 0
}

func (x *AgentPairwiseDisagreement) GetDisagreementRateBps() uint64 {
	if x != nil {
		return x.DisagreementRateBps
	}
	return 0
}

var File_zerone_dialectic_v1_types_proto protoreflect.FileDescriptor

const file_zerone_dialectic_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1fzerone/dialectic/v1/types.proto\x12\x13zerone.dialectic.v1\"k\n" +
	"\rVoterPosition\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\x12\x12\n" +
	"\x04vote\x18\x02 \x01(\tR\x04vote\x120\n" +
	"\x14aligned_with_verdict\x18\x03 \x01(\bR\x12alignedWithVerdict\"\xae\x03\n" +
	"\x12DialecticSignature\x12\x17\n" +
	"\afact_id\x18\x01 \x01(\tR\x06factId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\tR\aroundId\x12!\n" +
	"\ftotal_voters\x18\x03 \x01(\rR\vtotalVoters\x12!\n" +
	"\faccept_count\x18\x04 \x01(\rR\vacceptCount\x12!\n" +
	"\freject_count\x18\x05 \x01(\rR\vrejectCount\x12'\n" +
	"\x0fmalformed_count\x18\x06 \x01(\rR\x0emalformedCount\x12\x18\n" +
	"\averdict\x18\a \x01(\tR\averdict\x12#\n" +
	"\ragreement_bps\x18\b \x01(\x04R\fagreementBps\x12#\n" +
	"\rminority_size\x18\t \x01(\rR\fminoritySize\x12K\n" +
	"\x0fvoter_positions\x18\n" +
	" \x03(\v2\".zerone.dialectic.v1.VoterPositionR\x0evoterPositions\x12!\n" +
	"\fstress_label\x18\v \x01(\tR\vstressLabel\"\xfe\x01\n" +
	"\x0fDomainDialectic\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12%\n" +
	"\x0efacts_examined\x18\x02 \x01(\x04R\rfactsExamined\x12'\n" +
	"\x0funanimous_facts\x18\x03 \x01(\x04R\x0eunanimousFacts\x12'\n" +
	"\x0fcontested_facts\x18\x04 \x01(\x04R\x0econtestedFacts\x12.\n" +
	"\x13bare_majority_facts\x18\x05 \x01(\x04R\x11bareMajorityFacts\x12*\n" +
	"\x11avg_agreement_bps\x18\x06 \x01(\x04R\x0favgAgreementBps\"\xd3\x01\n" +
	"\x19AgentPairwiseDisagreement\x12\x17\n" +
	"\aagent_a\x18\x01 \x01(\tR\x06agentA\x12\x17\n" +
	"\aagent_b\x18\x02 \x01(\tR\x06agentB\x12*\n" +
	"\x11rounds_both_voted\x18\x03 \x01(\rR\x0froundsBothVoted\x12$\n" +
	"\rdisagreements\x18\x04 \x01(\rR\rdisagreements\x122\n" +
	"\x15disagreement_rate_bps\x18\x05 \x01(\x04R\x13disagreementRateBpsB2Z0github.com/zerone-chain/zerone/x/dialectic/typesb\x06proto3"

var (
	file_zerone_dialectic_v1_types_proto_rawDescOnce sync.Once
	file_zerone_dialectic_v1_types_proto_rawDescData []byte
)

func file_zerone_dialectic_v1_types_proto_rawDescGZIP() []byte {
	file_zerone_dialectic_v1_types_proto_rawDescOnce.Do(func() {
		file_zerone_dialectic_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_dialectic_v1_types_proto_rawDesc), len(file_zerone_dialectic_v1_types_proto_rawDesc)))
	})
	return file_zerone_dialectic_v1_types_proto_rawDescData
}

var file_zerone_dialectic_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zerone_dialectic_v1_types_proto_goTypes = []any{
	(*VoterPosition)(nil),             // 0: zerone.dialectic.v1.VoterPosition
	(*DialecticSignature)(nil),        // 1: zerone.dialectic.v1.DialecticSignature
	(*DomainDialectic)(nil),           // 2: zerone.dialectic.v1.DomainDialectic
	(*AgentPairwiseDisagreement)(nil), // 3: zerone.dialectic.v1.AgentPairwiseDisagreement
}
var file_zerone_dialectic_v1_types_proto_depIdxs = []int32{
	0, // 0: zerone.dialectic.v1.DialecticSignature.voter_positions:type_name -> zerone.dialectic.v1.VoterPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_dialectic_v1_types_proto_init() }
func file_zerone_dialectic_v1_types_proto_init() {
	if File_zerone_dialectic_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_dialectic_v1_types_proto_rawDesc), len(file_zerone_dialectic_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_dialectic_v1_types_proto_goTypes,
		DependencyIndexes: file_zerone_dialectic_v1_types_proto_depIdxs,
		MessageInfos:      file_zerone_dialectic_v1_types_proto_msgTypes,
	}.Build()
	File_zerone_dialectic_v1_types_proto = out.File
	file_zerone_dialectic_v1_types_proto_goTypes = nil
	file_zerone_dialectic_v1_types_proto_depIdxs = nil
}
