// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/partnerships/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Partnership_FullMethodName           = "/zerone.partnerships.v1.Query/Partnership"
	Query_PartnershipsByAddress_FullMethodName = "/zerone.partnerships.v1.Query/PartnershipsByAddress"
	Query_PendingOps_FullMethodName            = "/zerone.partnerships.v1.Query/PendingOps"
	Query_FormationPool_FullMethodName         = "/zerone.partnerships.v1.Query/FormationPool"
	Query_Params_FullMethodName                = "/zerone.partnerships.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Partnership(ctx context.Context, in *QueryPartnershipRequest, opts ...grpc.CallOption) (*QueryPartnershipResponse, error)
	PartnershipsByAddress(ctx context.Context, in *QueryByAddressRequest, opts ...grpc.CallOption) (*QueryByAddressResponse, error)
	PendingOps(ctx context.Context, in *QueryPendingOpsRequest, opts ...grpc.CallOption) (*QueryPendingOpsResponse, error)
	FormationPool(ctx context.Context, in *QueryFormationPoolRequest, opts ...grpc.CallOption) (*QueryFormationPoolResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Partnership(ctx context.Context, in *QueryPartnershipRequest, opts ...grpc.CallOption) (*QueryPartnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPartnershipResponse)
	err := c.cc.Invoke(ctx, Query_Partnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PartnershipsByAddress(ctx context.Context, in *QueryByAddressRequest, opts ...grpc.CallOption) (*QueryByAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryByAddressResponse)
	err := c.cc.Invoke(ctx, Query_PartnershipsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingOps(ctx context.Context, in *QueryPendingOpsRequest, opts ...grpc.CallOption) (*QueryPendingOpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPendingOpsResponse)
	err := c.cc.Invoke(ctx, Query_PendingOps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FormationPool(ctx context.Context, in *QueryFormationPoolRequest, opts ...grpc.CallOption) (*QueryFormationPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFormationPoolResponse)
	err := c.cc.Invoke(ctx, Query_FormationPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	Partnership(context.Context, *QueryPartnershipRequest) (*QueryPartnershipResponse, error)
	PartnershipsByAddress(context.Context, *QueryByAddressRequest) (*QueryByAddressResponse, error)
	PendingOps(context.Context, *QueryPendingOpsRequest) (*QueryPendingOpsResponse, error)
	FormationPool(context.Context, *QueryFormationPoolRequest) (*QueryFormationPoolResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Partnership(context.Context, *QueryPartnershipRequest) (*QueryPartnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Partnership not implemented")
}
func (UnimplementedQueryServer) PartnershipsByAddress(context.Context, *QueryByAddressRequest) (*QueryByAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PartnershipsByAddress not implemented")
}
func (UnimplementedQueryServer) PendingOps(context.Context, *QueryPendingOpsRequest) (*QueryPendingOpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PendingOps not implemented")
}
func (UnimplementedQueryServer) FormationPool(context.Context, *QueryFormationPoolRequest) (*QueryFormationPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FormationPool not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Partnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPartnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Partnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Partnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Partnership(ctx, req.(*QueryPartnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PartnershipsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PartnershipsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PartnershipsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PartnershipsByAddress(ctx, req.(*QueryByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingOps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingOpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingOps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingOps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingOps(ctx, req.(*QueryPendingOpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FormationPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFormationPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FormationPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FormationPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FormationPool(ctx, req.(*QueryFormationPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.partnerships.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Partnership",
			Handler:    _Query_Partnership_Handler,
		},
		{
			MethodName: "PartnershipsByAddress",
			Handler:    _Query_PartnershipsByAddress_Handler,
		},
		{
			MethodName: "PendingOps",
			Handler:    _Query_PendingOps_Handler,
		},
		{
			MethodName: "FormationPool",
			Handler:    _Query_FormationPool_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/partnerships/v1/query.proto",
}
