// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/partnerships/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitiatedBy   string                 `protobuf:"bytes,1,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	InitiatedAt   uint64                 `protobuf:"varint,2,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	CooldownEnd   uint64                 `protobuf:"varint,3,opt,name=cooldown_end,json=cooldownEnd,proto3" json:"cooldown_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitState) Reset() {
	*x = ExitState{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitState) ProtoMessage() {}

func (x *ExitState) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitState.ProtoReflect.Descriptor instead.
func (*ExitState) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ExitState) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *ExitState) GetInitiatedAt() uint64 {
	if x != nil {
		return x.InitiatedAt
	}
	return 0
}

func (x *ExitState) GetCooldownEnd() uint64 {
	if x != nil {
		return x.CooldownEnd
	}
	return 0
}

type Partnership struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HumanAddr        string                 `protobuf:"bytes,2,opt,name=human_addr,json=humanAddr,proto3" json:"human_addr,omitempty"`
	AgentAddr        string                 `protobuf:"bytes,3,opt,name=agent_addr,json=agentAddr,proto3" json:"agent_addr,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Tier             uint32                 `protobuf:"varint,5,opt,name=tier,proto3" json:"tier,omitempty"`
	LockTier         uint32                 `protobuf:"varint,6,opt,name=lock_tier,json=lockTier,proto3" json:"lock_tier,omitempty"`
	LockExpiresAt    uint64                 `protobuf:"varint,7,opt,name=lock_expires_at,json=lockExpiresAt,proto3" json:"lock_expires_at,omitempty"`
	SplitHumanBps    uint64                 `protobuf:"varint,8,opt,name=split_human_bps,json=splitHumanBps,proto3" json:"split_human_bps,omitempty"`
	SplitAgentBps    uint64                 `protobuf:"varint,9,opt,name=split_agent_bps,json=splitAgentBps,proto3" json:"split_agent_bps,omitempty"`
	CommonPotBalance string                 `protobuf:"bytes,10,opt,name=common_pot_balance,json=commonPotBalance,proto3" json:"common_pot_balance,omitempty"`
	TotalEarned      string                 `protobuf:"bytes,11,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"`
	CooperationScore uint64                 `protobuf:"varint,12,opt,name=cooperation_score,json=cooperationScore,proto3" json:"cooperation_score,omitempty"`
	FormedAtBlock    uint64                 `protobuf:"varint,13,opt,name=formed_at_block,json=formedAtBlock,proto3" json:"formed_at_block,omitempty"`
	ExitState        *ExitState             `protobuf:"bytes,14,opt,name=exit_state,json=exitState,proto3" json:"exit_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Partnership) Reset() {
	*x = Partnership{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partnership) ProtoMessage() {}

func (x *Partnership) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partnership.ProtoReflect.Descriptor instead.
func (*Partnership) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Partnership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Partnership) GetHumanAddr() string {
	if x != nil {
		return x.HumanAddr
	}
	return ""
}

func (x *Partnership) GetAgentAddr() string {
	if x != nil {
		return x.AgentAddr
	}
	return ""
}

func (x *Partnership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Partnership) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Partnership) GetLockTier() uint32 {
	if x != nil {
		return x.LockTier
	}
	return 0
}

func (x *Partnership) GetLockExpiresAt() uint64 {
	if x != nil {
		return x.LockExpiresAt
	}
	return 0
}

func (x *Partnership) GetSplitHumanBps() uint64 {
	if x != nil {
		return x.SplitHumanBps
	}
	return 0
}

func (x *Partnership) GetSplitAgentBps() uint64 {
	if x != nil {
		return x.SplitAgentBps
	}
	return 0
}

func (x *Partnership) GetCommonPotBalance() string {
	if x != nil {
		return x.CommonPotBalance
	}
	return ""
}

func (x *Partnership) GetTotalEarned() string {
	if x != nil {
		return x.TotalEarned
	}
	return ""
}

func (x *Partnership) GetCooperationScore() uint64 {
	if x != nil {
		return x.CooperationScore
	}
	return 0
}

func (x *Partnership) GetFormedAtBlock() uint64 {
	if x != nil {
		return x.FormedAtBlock
	}
	return 0
}

func (x *Partnership) GetExitState() *ExitState {
	if x != nil {
		return x.ExitState
	}
	return nil
}

type DeliberationState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AmountTier        string                 `protobuf:"bytes,1,opt,name=amount_tier,json=amountTier,proto3" json:"amount_tier,omitempty"`
	FloorEndsAt       uint64                 `protobuf:"varint,2,opt,name=floor_ends_at,json=floorEndsAt,proto3" json:"floor_ends_at,omitempty"`
	WindowEndsAt      uint64                 `protobuf:"varint,3,opt,name=window_ends_at,json=windowEndsAt,proto3" json:"window_ends_at,omitempty"`
	Rationale         string                 `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	CounterProposalOf string                 `protobuf:"bytes,5,opt,name=counter_proposal_of,json=counterProposalOf,proto3" json:"counter_proposal_of,omitempty"`
	ChainDepth        uint32                 `protobuf:"varint,6,opt,name=chain_depth,json=chainDepth,proto3" json:"chain_depth,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeliberationState) Reset() {
	*x = DeliberationState{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliberationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliberationState) ProtoMessage() {}

func (x *DeliberationState) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliberationState.ProtoReflect.Descriptor instead.
func (*DeliberationState) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *DeliberationState) GetAmountTier() string {
	if x != nil {
		return x.AmountTier
	}
	return ""
}

func (x *DeliberationState) GetFloorEndsAt() uint64 {
	if x != nil {
		return x.FloorEndsAt
	}
	return 0
}

func (x *DeliberationState) GetWindowEndsAt() uint64 {
	if x != nil {
		return x.WindowEndsAt
	}
	return 0
}

func (x *DeliberationState) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *DeliberationState) GetCounterProposalOf() string {
	if x != nil {
		return x.CounterProposalOf
	}
	return ""
}

func (x *DeliberationState) GetChainDepth() uint32 {
	if x != nil {
		return x.ChainDepth
	}
	return 0
}

type ConsensusOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PartnershipId string                 `protobuf:"bytes,2,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	OpType        string                 `protobuf:"bytes,3,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	ProposedBy    string                 `protobuf:"bytes,4,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Deliberation  *DeliberationState     `protobuf:"bytes,7,opt,name=deliberation,proto3" json:"deliberation,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusOperation) Reset() {
	*x = ConsensusOperation{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusOperation) ProtoMessage() {}

func (x *ConsensusOperation) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusOperation.ProtoReflect.Descriptor instead.
func (*ConsensusOperation) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsensusOperation) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *ConsensusOperation) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *ConsensusOperation) GetProposedBy() string {
	if x != nil {
		return x.ProposedBy
	}
	return ""
}

func (x *ConsensusOperation) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConsensusOperation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConsensusOperation) GetDeliberation() *DeliberationState {
	if x != nil {
		return x.Deliberation
	}
	return nil
}

func (x *ConsensusOperation) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SafetyFreeze struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId        string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	FrozenBy             string                 `protobuf:"bytes,2,opt,name=frozen_by,json=frozenBy,proto3" json:"frozen_by,omitempty"`
	FrozenAt             uint64                 `protobuf:"varint,3,opt,name=frozen_at,json=frozenAt,proto3" json:"frozen_at,omitempty"`
	ExpiresAt            uint64                 `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FreezeCountThisEpoch uint32                 `protobuf:"varint,5,opt,name=freeze_count_this_epoch,json=freezeCountThisEpoch,proto3" json:"freeze_count_this_epoch,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SafetyFreeze) Reset() {
	*x = SafetyFreeze{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetyFreeze) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyFreeze) ProtoMessage() {}

func (x *SafetyFreeze) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyFreeze.ProtoReflect.Descriptor instead.
func (*SafetyFreeze) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *SafetyFreeze) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *SafetyFreeze) GetFrozenBy() string {
	if x != nil {
		return x.FrozenBy
	}
	return ""
}

func (x *SafetyFreeze) GetFrozenAt() uint64 {
	if x != nil {
		return x.FrozenAt
	}
	return 0
}

func (x *SafetyFreeze) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SafetyFreeze) GetFreezeCountThisEpoch() uint32 {
	if x != nil {
		return x.FreezeCountThisEpoch
	}
	return 0
}

type CoercionSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	PartnershipId string                 `protobuf:"bytes,2,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	RaisedBy      string                 `protobuf:"bytes,3,opt,name=raised_by,json=raisedBy,proto3" json:"raised_by,omitempty"`
	RaisedAt      uint64                 `protobuf:"varint,4,opt,name=raised_at,json=raisedAt,proto3" json:"raised_at,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Resolved      bool                   `protobuf:"varint,6,opt,name=resolved,proto3" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoercionSignal) Reset() {
	*x = CoercionSignal{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoercionSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoercionSignal) ProtoMessage() {}

func (x *CoercionSignal) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoercionSignal.ProtoReflect.Descriptor instead.
func (*CoercionSignal) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *CoercionSignal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *CoercionSignal) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *CoercionSignal) GetRaisedBy() string {
	if x != nil {
		return x.RaisedBy
	}
	return ""
}

func (x *CoercionSignal) GetRaisedAt() uint64 {
	if x != nil {
		return x.RaisedAt
	}
	return 0
}

func (x *CoercionSignal) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CoercionSignal) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

type RejectionCooldown struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId  string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	RejectionCount uint32                 `protobuf:"varint,2,opt,name=rejection_count,json=rejectionCount,proto3" json:"rejection_count,omitempty"`
	CooldownEndsAt uint64                 `protobuf:"varint,3,opt,name=cooldown_ends_at,json=cooldownEndsAt,proto3" json:"cooldown_ends_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RejectionCooldown) Reset() {
	*x = RejectionCooldown{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectionCooldown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectionCooldown) ProtoMessage() {}

func (x *RejectionCooldown) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectionCooldown.ProtoReflect.Descriptor instead.
func (*RejectionCooldown) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *RejectionCooldown) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *RejectionCooldown) GetRejectionCount() uint32 {
	if x != nil {
		return x.RejectionCount
	}
	return 0
}

func (x *RejectionCooldown) GetCooldownEndsAt() uint64 {
	if x != nil {
		return x.CooldownEndsAt
	}
	return 0
}

type SeedPartnership struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HumanAddr         string                 `protobuf:"bytes,2,opt,name=human_addr,json=humanAddr,proto3" json:"human_addr,omitempty"`
	AgentAddr         string                 `protobuf:"bytes,3,opt,name=agent_addr,json=agentAddr,proto3" json:"agent_addr,omitempty"`
	CreatedAt         uint64                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt         uint64                 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	HumanContribution string                 `protobuf:"bytes,6,opt,name=human_contribution,json=humanContribution,proto3" json:"human_contribution,omitempty"`
	AgentContribution string                 `protobuf:"bytes,7,opt,name=agent_contribution,json=agentContribution,proto3" json:"agent_contribution,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CommonPotBalance  string                 `protobuf:"bytes,9,opt,name=common_pot_balance,json=commonPotBalance,proto3" json:"common_pot_balance,omitempty"`
	CommonPotCap      string                 `protobuf:"bytes,10,opt,name=common_pot_cap,json=commonPotCap,proto3" json:"common_pot_cap,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SeedPartnership) Reset() {
	*x = SeedPartnership{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedPartnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedPartnership) ProtoMessage() {}

func (x *SeedPartnership) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedPartnership.ProtoReflect.Descriptor instead.
func (*SeedPartnership) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *SeedPartnership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SeedPartnership) GetHumanAddr() string {
	if x != nil {
		return x.HumanAddr
	}
	return ""
}

func (x *SeedPartnership) GetAgentAddr() string {
	if x != nil {
		return x.AgentAddr
	}
	return ""
}

func (x *SeedPartnership) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SeedPartnership) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SeedPartnership) GetHumanContribution() string {
	if x != nil {
		return x.HumanContribution
	}
	return ""
}

func (x *SeedPartnership) GetAgentContribution() string {
	if x != nil {
		return x.AgentContribution
	}
	return ""
}

func (x *SeedPartnership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeedPartnership) GetCommonPotBalance() string {
	if x != nil {
		return x.CommonPotBalance
	}
	return ""
}

func (x *SeedPartnership) GetCommonPotCap() string {
	if x != nil {
		return x.CommonPotCap
	}
	return ""
}

type PoolEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	PreferredRole string                 `protobuf:"bytes,3,opt,name=preferred_role,json=preferredRole,proto3" json:"preferred_role,omitempty"`
	StakeMin      string                 `protobuf:"bytes,4,opt,name=stake_min,json=stakeMin,proto3" json:"stake_min,omitempty"`
	StakeMax      string                 `protobuf:"bytes,5,opt,name=stake_max,json=stakeMax,proto3" json:"stake_max,omitempty"`
	RegisteredAt  uint64                 `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Deposit       string                 `protobuf:"bytes,7,opt,name=deposit,proto3" json:"deposit,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	MatchedWith   string                 `protobuf:"bytes,10,opt,name=matched_with,json=matchedWith,proto3" json:"matched_with,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolEntry) Reset() {
	*x = PoolEntry{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolEntry) ProtoMessage() {}

func (x *PoolEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolEntry.ProtoReflect.Descriptor instead.
func (*PoolEntry) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *PoolEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PoolEntry) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *PoolEntry) GetPreferredRole() string {
	if x != nil {
		return x.PreferredRole
	}
	return ""
}

func (x *PoolEntry) GetStakeMin() string {
	if x != nil {
		return x.StakeMin
	}
	return ""
}

func (x *PoolEntry) GetStakeMax() string {
	if x != nil {
		return x.StakeMax
	}
	return ""
}

func (x *PoolEntry) GetRegisteredAt() uint64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *PoolEntry) GetDeposit() string {
	if x != nil {
		return x.Deposit
	}
	return ""
}

func (x *PoolEntry) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PoolEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PoolEntry) GetMatchedWith() string {
	if x != nil {
		return x.MatchedWith
	}
	return ""
}

type MentorshipConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SponsorAddr          string                 `protobuf:"bytes,1,opt,name=sponsor_addr,json=sponsorAddr,proto3" json:"sponsor_addr,omitempty"`
	MenteeAddr           string                 `protobuf:"bytes,2,opt,name=mentee_addr,json=menteeAddr,proto3" json:"mentee_addr,omitempty"`
	PartnershipId        string                 `protobuf:"bytes,3,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	SponsorContribution  string                 `protobuf:"bytes,4,opt,name=sponsor_contribution,json=sponsorContribution,proto3" json:"sponsor_contribution,omitempty"`
	MenteeContribution   string                 `protobuf:"bytes,5,opt,name=mentee_contribution,json=menteeContribution,proto3" json:"mentee_contribution,omitempty"`
	SponsorSplitBps      uint64                 `protobuf:"varint,6,opt,name=sponsor_split_bps,json=sponsorSplitBps,proto3" json:"sponsor_split_bps,omitempty"`
	MenteeSplitBps       uint64                 `protobuf:"varint,7,opt,name=mentee_split_bps,json=menteeSplitBps,proto3" json:"mentee_split_bps,omitempty"`
	GraduationBlock      uint64                 `protobuf:"varint,8,opt,name=graduation_block,json=graduationBlock,proto3" json:"graduation_block,omitempty"`
	Graduated            bool                   `protobuf:"varint,9,opt,name=graduated,proto3" json:"graduated,omitempty"`
	SponsorVerifications uint64                 `protobuf:"varint,10,opt,name=sponsor_verifications,json=sponsorVerifications,proto3" json:"sponsor_verifications,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MentorshipConfig) Reset() {
	*x = MentorshipConfig{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorshipConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorshipConfig) ProtoMessage() {}

func (x *MentorshipConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorshipConfig.ProtoReflect.Descriptor instead.
func (*MentorshipConfig) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *MentorshipConfig) GetSponsorAddr() string {
	if x != nil {
		return x.SponsorAddr
	}
	return ""
}

func (x *MentorshipConfig) GetMenteeAddr() string {
	if x != nil {
		return x.MenteeAddr
	}
	return ""
}

func (x *MentorshipConfig) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *MentorshipConfig) GetSponsorContribution() string {
	if x != nil {
		return x.SponsorContribution
	}
	return ""
}

func (x *MentorshipConfig) GetMenteeContribution() string {
	if x != nil {
		return x.MenteeContribution
	}
	return ""
}

func (x *MentorshipConfig) GetSponsorSplitBps() uint64 {
	if x != nil {
		return x.SponsorSplitBps
	}
	return 0
}

func (x *MentorshipConfig) GetMenteeSplitBps() uint64 {
	if x != nil {
		return x.MenteeSplitBps
	}
	return 0
}

func (x *MentorshipConfig) GetGraduationBlock() uint64 {
	if x != nil {
		return x.GraduationBlock
	}
	return 0
}

func (x *MentorshipConfig) GetGraduated() bool {
	if x != nil {
		return x.Graduated
	}
	return false
}

func (x *MentorshipConfig) GetSponsorVerifications() uint64 {
	if x != nil {
		return x.SponsorVerifications
	}
	return 0
}

type Mentorship struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MentorAddr           string                 `protobuf:"bytes,2,opt,name=mentor_addr,json=mentorAddr,proto3" json:"mentor_addr,omitempty"`
	MenteeAddr           string                 `protobuf:"bytes,3,opt,name=mentee_addr,json=menteeAddr,proto3" json:"mentee_addr,omitempty"`
	Domain               string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartBlock           uint64                 `protobuf:"varint,6,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	DurationBlocks       uint64                 `protobuf:"varint,7,opt,name=duration_blocks,json=durationBlocks,proto3" json:"duration_blocks,omitempty"`
	MenteeVerifications  uint64                 `protobuf:"varint,8,opt,name=mentee_verifications,json=menteeVerifications,proto3" json:"mentee_verifications,omitempty"`
	MenteeClaimsSubmitted uint64                `protobuf:"varint,9,opt,name=mentee_claims_submitted,json=menteeClaimsSubmitted,proto3" json:"mentee_claims_submitted,omitempty"`
	GraduationThreshold  uint64                 `protobuf:"varint,10,opt,name=graduation_threshold,json=graduationThreshold,proto3" json:"graduation_threshold,omitempty"`
	GraduationClaimsReq  uint64                 `protobuf:"varint,11,opt,name=graduation_claims_req,json=graduationClaimsReq,proto3" json:"graduation_claims_req,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Mentorship) Reset() {
	*x = Mentorship{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mentorship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mentorship) ProtoMessage() {}

func (x *Mentorship) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mentorship.ProtoReflect.Descriptor instead.
func (*Mentorship) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *Mentorship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mentorship) GetMentorAddr() string {
	if x != nil {
		return x.MentorAddr
	}
	return ""
}

func (x *Mentorship) GetMenteeAddr() string {
	if x != nil {
		return x.MenteeAddr
	}
	return ""
}

func (x *Mentorship) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Mentorship) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Mentorship) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Mentorship) GetDurationBlocks() uint64 {
	if x != nil {
		return x.DurationBlocks
	}
	return 0
}

func (x *Mentorship) GetMenteeVerifications() uint64 {
	if x != nil {
		return x.MenteeVerifications
	}
	return 0
}

func (x *Mentorship) GetMenteeClaimsSubmitted() uint64 {
	if x != nil {
		return x.MenteeClaimsSubmitted
	}
	return 0
}

func (x *Mentorship) GetGraduationThreshold() uint64 {
	if x != nil {
		return x.GraduationThreshold
	}
	return 0
}

func (x *Mentorship) GetGraduationClaimsReq() uint64 {
	if x != nil {
		return x.GraduationClaimsReq
	}
	return 0
}

type FormationMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr1         string                 `protobuf:"bytes,2,opt,name=addr1,proto3" json:"addr1,omitempty"`
	Addr2         string                 `protobuf:"bytes,3,opt,name=addr2,proto3" json:"addr2,omitempty"`
	Score         uint64                 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	ProposedAt    uint64                 `protobuf:"varint,5,opt,name=proposed_at,json=proposedAt,proto3" json:"proposed_at,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Addr1Accepted bool                   `protobuf:"varint,8,opt,name=addr1_accepted,json=addr1Accepted,proto3" json:"addr1_accepted,omitempty"`
	Addr2Accepted bool                   `protobuf:"varint,9,opt,name=addr2_accepted,json=addr2Accepted,proto3" json:"addr2_accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormationMatch) Reset() {
	*x = FormationMatch{}
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormationMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormationMatch) ProtoMessage() {}

func (x *FormationMatch) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_partnerships_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormationMatch.ProtoReflect.Descriptor instead.
func (*FormationMatch) Descriptor() ([]byte, []int) {
	return file_zerone_partnerships_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *FormationMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormationMatch) GetAddr1() string {
	if x != nil {
		return x.Addr1
	}
	return ""
}

func (x *FormationMatch) GetAddr2() string {
	if x != nil {
		return x.Addr2
	}
	return ""
}

func (x *FormationMatch) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FormationMatch) GetProposedAt() uint64 {
	if x != nil {
		return x.ProposedAt
	}
	return 0
}

func (x *FormationMatch) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *FormationMatch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FormationMatch) GetAddr1Accepted() bool {
	if x != nil {
		return x.Addr1Accepted
	}
	return false
}

func (x *FormationMatch) GetAddr2Accepted() bool {
	if x != nil {
		return x.Addr2Accepted
	}
	return false
}

var File_zerone_partnerships_v1_types_proto protoreflect.FileDescriptor

const file_zerone_partnerships_v1_types_proto_rawDesc = "" +
	"\n\"zerone/partnerships/v1/types.proto\x12\x16zerone.partnerships.v1\"t\n\tExitSt" +
	"ate\x12!\n\x0cinitiated_by\x18\x01 \x01(\tR\x0binitiatedBy\x12!\n\x0cinitiated_at\x18\x02 \x01(\x04R\x0binitiate" +
	"dAt\x12!\n\x0ccooldown_end\x18\x03 \x01(\x04R\x0bcooldownEnd\"\x84\x04\n\x0bPartnership\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id" +
	"\x12\x1d\n\nhuman_addr\x18\x02 \x01(\tR\thumanAddr\x12\x1d\n\nagent_addr\x18\x03 \x01(\tR\tagentAddr\x12\x16\n\x06stat" +
	"us\x18\x04 \x01(\tR\x06status\x12\x12\n\x04tier\x18\x05 \x01(\rR\x04tier\x12\x1b\n\tlock_tier\x18\x06 \x01(\rR\x08lockTier\x12&\n\x0fl" +
	"ock_expires_at\x18\x07 \x01(\x04R\rlockExpiresAt\x12&\n\x0fsplit_human_bps\x18\x08 \x01(\x04R\rsplitHum" +
	"anBps\x12&\n\x0fsplit_agent_bps\x18\t \x01(\x04R\rsplitAgentBps\x12,\n\x12common_pot_balance\x18\n " +
	"\x01(\tR\x10commonPotBalance\x12!\n\x0ctotal_earned\x18\x0b \x01(\tR\x0btotalEarned\x12+\n\x11cooperatio" +
	"n_score\x18\x0c \x01(\x04R\x10cooperationScore\x12&\n\x0fformed_at_block\x18\r \x01(\x04R\rformedAtBloc" +
	"k\x12@\n\nexit_state\x18\x0e \x01(\x0b2!.zerone.partnerships.v1.ExitStateR\texitState\"\xed\x01" +
	"\n\x11DeliberationState\x12\x1f\n\x0bamount_tier\x18\x01 \x01(\tR\namountTier\x12\"\n\rfloor_ends_at\x18" +
	"\x02 \x01(\x04R\x0bfloorEndsAt\x12$\n\x0ewindow_ends_at\x18\x03 \x01(\x04R\x0cwindowEndsAt\x12\x1c\n\trationale\x18" +
	"\x04 \x01(\tR\trationale\x12.\n\x13counter_proposal_of\x18\x05 \x01(\tR\x11counterProposalOf\x12\x1f\n\x0bch" +
	"ain_depth\x18\x06 \x01(\rR\nchainDepth\"\xa3\x02\n\x12ConsensusOperation\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12%\n\x0e" +
	"partnership_id\x18\x02 \x01(\tR\rpartnershipId\x12\x17\n\x07op_type\x18\x03 \x01(\tR\x06opType\x12\x1f\n\x0bpropos" +
	"ed_by\x18\x04 \x01(\tR\nproposedBy\x12\x16\n\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n\x06status\x18\x06 \x01(\tR\x06statu" +
	"s\x12M\n\x0cdeliberation\x18\x07 \x01(\x0b2).zerone.partnerships.v1.DeliberationStateR\x0cde" +
	"liberation\x12\x1d\n\ncreated_at\x18\x08 \x01(\x04R\tcreatedAt\"\xc5\x01\n\x0cSafetyFreeze\x12%\n\x0epartners" +
	"hip_id\x18\x01 \x01(\tR\rpartnershipId\x12\x1b\n\tfrozen_by\x18\x02 \x01(\tR\x08frozenBy\x12\x1b\n\tfrozen_at\x18" +
	"\x03 \x01(\x04R\x08frozenAt\x12\x1d\n\nexpires_at\x18\x04 \x01(\x04R\texpiresAt\x125\n\x17freeze_count_this_ep" +
	"och\x18\x05 \x01(\rR\x14freezeCountThisEpoch\"\xc9\x01\n\x0eCoercionSignal\x12\x1b\n\tsignal_id\x18\x01 \x01(\tR" +
	"\x08signalId\x12%\n\x0epartnership_id\x18\x02 \x01(\tR\rpartnershipId\x12\x1b\n\traised_by\x18\x03 \x01(\tR\x08r" +
	"aisedBy\x12\x1b\n\traised_at\x18\x04 \x01(\x04R\x08raisedAt\x12\x1d\n\nexpires_at\x18\x05 \x01(\x04R\texpiresAt\x12\x1a\n" +
	"\x08resolved\x18\x06 \x01(\x08R\x08resolved\"\x8d\x01\n\x11RejectionCooldown\x12%\n\x0epartnership_id\x18\x01 \x01(" +
	"\tR\rpartnershipId\x12'\n\x0frejection_count\x18\x02 \x01(\rR\x0erejectionCount\x12(\n\x10cooldown_" +
	"ends_at\x18\x03 \x01(\x04R\x0ecooldownEndsAt\"\xe7\x02\n\x0fSeedPartnership\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n\nh" +
	"uman_addr\x18\x02 \x01(\tR\thumanAddr\x12\x1d\n\nagent_addr\x18\x03 \x01(\tR\tagentAddr\x12\x1d\n\ncreated_a" +
	"t\x18\x04 \x01(\x04R\tcreatedAt\x12\x1d\n\nexpires_at\x18\x05 \x01(\x04R\texpiresAt\x12-\n\x12human_contributio" +
	"n\x18\x06 \x01(\tR\x11humanContribution\x12-\n\x12agent_contribution\x18\x07 \x01(\tR\x11agentContribut" +
	"ion\x12\x16\n\x06status\x18\x08 \x01(\tR\x06status\x12,\n\x12common_pot_balance\x18\t \x01(\tR\x10commonPotBala" +
	"nce\x12$\n\x0ecommon_pot_cap\x18\n \x01(\tR\x0ccommonPotCap\"\xb9\x02\n\tPoolEntry\x12\x18\n\x07address\x18\x01 \x01" +
	"(\tR\x07address\x12\x18\n\x07domains\x18\x02 \x03(\tR\x07domains\x12%\n\x0epreferred_role\x18\x03 \x01(\tR\rpreferr" +
	"edRole\x12\x1b\n\tstake_min\x18\x04 \x01(\tR\x08stakeMin\x12\x1b\n\tstake_max\x18\x05 \x01(\tR\x08stakeMax\x12#\n\rre" +
	"gistered_at\x18\x06 \x01(\x04R\x0cregisteredAt\x12\x18\n\x07deposit\x18\x07 \x01(\tR\x07deposit\x12\x1d\n\nexpires_a" +
	"t\x18\x08 \x01(\x04R\texpiresAt\x12\x16\n\x06status\x18\t \x01(\tR\x06status\x12!\n\x0cmatched_with\x18\n \x01(\tR\x0bmatc" +
	"hedWith\"\xb5\x03\n\x10MentorshipConfig\x12!\n\x0csponsor_addr\x18\x01 \x01(\tR\x0bsponsorAddr\x12\x1f\n\x0bmen" +
	"tee_addr\x18\x02 \x01(\tR\nmenteeAddr\x12%\n\x0epartnership_id\x18\x03 \x01(\tR\rpartnershipId\x121\n\x14s" +
	"ponsor_contribution\x18\x04 \x01(\tR\x13sponsorContribution\x12/\n\x13mentee_contribution\x18" +
	"\x05 \x01(\tR\x12menteeContribution\x12*\n\x11sponsor_split_bps\x18\x06 \x01(\x04R\x0fsponsorSplitBps\x12" +
	"(\n\x10mentee_split_bps\x18\x07 \x01(\x04R\x0ementeeSplitBps\x12)\n\x10graduation_block\x18\x08 \x01(\x04R\x0fg" +
	"raduationBlock\x12\x1c\n\tgraduated\x18\t \x01(\x08R\tgraduated\x123\n\x15sponsor_verifications\x18" +
	"\n \x01(\x04R\x14sponsorVerifications\"\xaa\x03\n\nMentorship\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n\x0bmentor_a" +
	"ddr\x18\x02 \x01(\tR\nmentorAddr\x12\x1f\n\x0bmentee_addr\x18\x03 \x01(\tR\nmenteeAddr\x12\x16\n\x06domain\x18\x04 \x01(\t" +
	"R\x06domain\x12\x16\n\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n\x0bstart_block\x18\x06 \x01(\x04R\nstartBlock\x12'\n\x0fd" +
	"uration_blocks\x18\x07 \x01(\x04R\x0edurationBlocks\x121\n\x14mentee_verifications\x18\x08 \x01(\x04R\x13me" +
	"nteeVerifications\x126\n\x17mentee_claims_submitted\x18\t \x01(\x04R\x15menteeClaimsSubmit" +
	"ted\x121\n\x14graduation_threshold\x18\n \x01(\x04R\x13graduationThreshold\x122\n\x15graduation_c" +
	"laims_req\x18\x0b \x01(\x04R\x13graduationClaimsReq\"\x88\x02\n\x0eFormationMatch\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02i" +
	"d\x12\x14\n\x05addr1\x18\x02 \x01(\tR\x05addr1\x12\x14\n\x05addr2\x18\x03 \x01(\tR\x05addr2\x12\x14\n\x05score\x18\x04 \x01(\x04R\x05score\x12\x1f\n" +
	"\x0bproposed_at\x18\x05 \x01(\x04R\nproposedAt\x12\x1d\n\nexpires_at\x18\x06 \x01(\x04R\texpiresAt\x12\x16\n\x06statu" +
	"s\x18\x07 \x01(\tR\x06status\x12%\n\x0eaddr1_accepted\x18\x08 \x01(\x08R\raddr1Accepted\x12%\n\x0eaddr2_accept" +
	"ed\x18\t \x01(\x08R\raddr2AcceptedB5Z3github.com/zerone-chain/zerone/x/partnershi" +
	"ps/typesb\x06proto3"

var (
	file_zerone_partnerships_v1_types_proto_rawDescOnce sync.Once
	file_zerone_partnerships_v1_types_proto_rawDescData []byte
)

func file_zerone_partnerships_v1_types_proto_rawDescGZIP() []byte {
	file_zerone_partnerships_v1_types_proto_rawDescOnce.Do(func() {
		file_zerone_partnerships_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_partnerships_v1_types_proto_rawDesc), len(file_zerone_partnerships_v1_types_proto_rawDesc)))
	})
	return file_zerone_partnerships_v1_types_proto_rawDescData
}

var file_zerone_partnerships_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_zerone_partnerships_v1_types_proto_goTypes = []any{
	(*ExitState)(nil),          // 0: zerone.partnerships.v1.ExitState
	(*Partnership)(nil),        // 1: zerone.partnerships.v1.Partnership
	(*DeliberationState)(nil),  // 2: zerone.partnerships.v1.DeliberationState
	(*ConsensusOperation)(nil), // 3: zerone.partnerships.v1.ConsensusOperation
	(*SafetyFreeze)(nil),       // 4: zerone.partnerships.v1.SafetyFreeze
	(*CoercionSignal)(nil),     // 5: zerone.partnerships.v1.CoercionSignal
	(*RejectionCooldown)(nil),  // 6: zerone.partnerships.v1.RejectionCooldown
	(*SeedPartnership)(nil),    // 7: zerone.partnerships.v1.SeedPartnership
	(*PoolEntry)(nil),          // 8: zerone.partnerships.v1.PoolEntry
	(*MentorshipConfig)(nil),   // 9: zerone.partnerships.v1.MentorshipConfig
	(*Mentorship)(nil),         // 10: zerone.partnerships.v1.Mentorship
	(*FormationMatch)(nil),     // 11: zerone.partnerships.v1.FormationMatch
}
var file_zerone_partnerships_v1_types_proto_depIdxs = []int32{
	0, // 0: zerone.partnerships.v1.Partnership.exit_state:type_name -> zerone.partnerships.v1.ExitState
	2, // 1: zerone.partnerships.v1.ConsensusOperation.deliberation:type_name -> zerone.partnerships.v1.DeliberationState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zerone_partnerships_v1_types_proto_init() }
func file_zerone_partnerships_v1_types_proto_init() {
	if File_zerone_partnerships_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_partnerships_v1_types_proto_rawDesc), len(file_zerone_partnerships_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_partnerships_v1_types_proto_goTypes,
		DependencyIndexes: file_zerone_partnerships_v1_types_proto_depIdxs,
		MessageInfos:      file_zerone_partnerships_v1_types_proto_msgTypes,
	}.Build()
	File_zerone_partnerships_v1_types_proto = out.File
	file_zerone_partnerships_v1_types_proto_goTypes = nil
	file_zerone_partnerships_v1_types_proto_depIdxs = nil
}
