// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/disputes/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_InitiateDispute_FullMethodName = "/zerone.disputes.v1.Msg/InitiateDispute"
	Msg_CommitEvidence_FullMethodName  = "/zerone.disputes.v1.Msg/CommitEvidence"
	Msg_RevealEvidence_FullMethodName  = "/zerone.disputes.v1.Msg/RevealEvidence"
	Msg_ArbiterVote_FullMethodName     = "/zerone.disputes.v1.Msg/ArbiterVote"
	Msg_EscalateDispute_FullMethodName = "/zerone.disputes.v1.Msg/EscalateDispute"
	Msg_SettleDispute_FullMethodName   = "/zerone.disputes.v1.Msg/SettleDispute"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	InitiateDispute(ctx context.Context, in *MsgInitiateDispute, opts ...grpc.CallOption) (*MsgInitiateDisputeResponse, error)
	CommitEvidence(ctx context.Context, in *MsgCommitEvidence, opts ...grpc.CallOption) (*MsgCommitEvidenceResponse, error)
	RevealEvidence(ctx context.Context, in *MsgRevealEvidence, opts ...grpc.CallOption) (*MsgRevealEvidenceResponse, error)
	ArbiterVote(ctx context.Context, in *MsgArbiterVote, opts ...grpc.CallOption) (*MsgArbiterVoteResponse, error)
	EscalateDispute(ctx context.Context, in *MsgEscalateDispute, opts ...grpc.CallOption) (*MsgEscalateDisputeResponse, error)
	SettleDispute(ctx context.Context, in *MsgSettleDispute, opts ...grpc.CallOption) (*MsgSettleDisputeResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InitiateDispute(ctx context.Context, in *MsgInitiateDispute, opts ...grpc.CallOption) (*MsgInitiateDisputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgInitiateDisputeResponse)
	err := c.cc.Invoke(ctx, Msg_InitiateDispute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CommitEvidence(ctx context.Context, in *MsgCommitEvidence, opts ...grpc.CallOption) (*MsgCommitEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCommitEvidenceResponse)
	err := c.cc.Invoke(ctx, Msg_CommitEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealEvidence(ctx context.Context, in *MsgRevealEvidence, opts ...grpc.CallOption) (*MsgRevealEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealEvidenceResponse)
	err := c.cc.Invoke(ctx, Msg_RevealEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ArbiterVote(ctx context.Context, in *MsgArbiterVote, opts ...grpc.CallOption) (*MsgArbiterVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgArbiterVoteResponse)
	err := c.cc.Invoke(ctx, Msg_ArbiterVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EscalateDispute(ctx context.Context, in *MsgEscalateDispute, opts ...grpc.CallOption) (*MsgEscalateDisputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgEscalateDisputeResponse)
	err := c.cc.Invoke(ctx, Msg_EscalateDispute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SettleDispute(ctx context.Context, in *MsgSettleDispute, opts ...grpc.CallOption) (*MsgSettleDisputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSettleDisputeResponse)
	err := c.cc.Invoke(ctx, Msg_SettleDispute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	InitiateDispute(context.Context, *MsgInitiateDispute) (*MsgInitiateDisputeResponse, error)
	CommitEvidence(context.Context, *MsgCommitEvidence) (*MsgCommitEvidenceResponse, error)
	RevealEvidence(context.Context, *MsgRevealEvidence) (*MsgRevealEvidenceResponse, error)
	ArbiterVote(context.Context, *MsgArbiterVote) (*MsgArbiterVoteResponse, error)
	EscalateDispute(context.Context, *MsgEscalateDispute) (*MsgEscalateDisputeResponse, error)
	SettleDispute(context.Context, *MsgSettleDispute) (*MsgSettleDisputeResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) InitiateDispute(context.Context, *MsgInitiateDispute) (*MsgInitiateDisputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateDispute not implemented")
}
func (UnimplementedMsgServer) CommitEvidence(context.Context, *MsgCommitEvidence) (*MsgCommitEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitEvidence not implemented")
}
func (UnimplementedMsgServer) RevealEvidence(context.Context, *MsgRevealEvidence) (*MsgRevealEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealEvidence not implemented")
}
func (UnimplementedMsgServer) ArbiterVote(context.Context, *MsgArbiterVote) (*MsgArbiterVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArbiterVote not implemented")
}
func (UnimplementedMsgServer) EscalateDispute(context.Context, *MsgEscalateDispute) (*MsgEscalateDisputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EscalateDispute not implemented")
}
func (UnimplementedMsgServer) SettleDispute(context.Context, *MsgSettleDispute) (*MsgSettleDisputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleDispute not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_InitiateDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InitiateDispute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateDispute(ctx, req.(*MsgInitiateDispute))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CommitEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CommitEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitEvidence(ctx, req.(*MsgCommitEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealEvidence(ctx, req.(*MsgRevealEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ArbiterVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgArbiterVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ArbiterVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ArbiterVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ArbiterVote(ctx, req.(*MsgArbiterVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EscalateDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEscalateDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EscalateDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_EscalateDispute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EscalateDispute(ctx, req.(*MsgEscalateDispute))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SettleDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSettleDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SettleDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SettleDispute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SettleDispute(ctx, req.(*MsgSettleDispute))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.disputes.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateDispute",
			Handler:    _Msg_InitiateDispute_Handler,
		},
		{
			MethodName: "CommitEvidence",
			Handler:    _Msg_CommitEvidence_Handler,
		},
		{
			MethodName: "RevealEvidence",
			Handler:    _Msg_RevealEvidence_Handler,
		},
		{
			MethodName: "ArbiterVote",
			Handler:    _Msg_ArbiterVote_Handler,
		},
		{
			MethodName: "EscalateDispute",
			Handler:    _Msg_EscalateDispute_Handler,
		},
		{
			MethodName: "SettleDispute",
			Handler:    _Msg_SettleDispute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/disputes/v1/tx.proto",
}
