package types

import "cosmossdk.io/errors"

var (
	ErrPoolNotFound          = errors.Register(ModuleName, 2, "pool not found")
	ErrPoolAlreadyExists     = errors.Register(ModuleName, 3, "pool already exists for this denom pair")
	ErrMaxPoolsReached       = errors.Register(ModuleName, 4, "maximum open pools reached")
	ErrInsufficientLiquidity = errors.Register(ModuleName, 5, "insufficient initial liquidity")
	ErrInvalidDenom          = errors.Register(ModuleName, 6, "invalid denom")
	ErrSameDenom             = errors.Register(ModuleName, 7, "cannot create pool with same denom on both sides")
	ErrSlippageExceeded      = errors.Register(ModuleName, 8, "output below minimum (slippage exceeded)")
	ErrPoolLocked            = errors.Register(ModuleName, 9, "pool is locked (swap in progress)")
	ErrZeroAmount            = errors.Register(ModuleName, 10, "amount must be positive")
	ErrInvalidSwapFee        = errors.Register(ModuleName, 11, "swap fee must use the governed default and cannot exceed 100000 millionths (10%)")
	ErrUnauthorized          = errors.Register(ModuleName, 12, "unauthorized")
	ErrDenomNotInPool        = errors.Register(ModuleName, 13, "denom not found in this pool")
	ErrInsufficientLP        = errors.Register(ModuleName, 14, "insufficient LP tokens")
	ErrNoPool                = errors.Register(ModuleName, 15, "no pool found for denom pair")
	ErrReserveBelowMinimum   = errors.Register(ModuleName, 16, "reserve would fall below minimum")
	ErrMissingZRNSide        = errors.Register(ModuleName, 17, "pool must pair uzrn with a counter denom (zerone pools are ZRN-quoted by design)")
	ErrInvalidAmount         = errors.Register(ModuleName, 18, "invalid amount")
	ErrPoolNotActive         = errors.Register(ModuleName, 19, "pool does not permit swaps")
	ErrPoolAddDisabled       = errors.Register(ModuleName, 20, "pool does not permit liquidity additions")
	ErrPoolExitDisabled      = errors.Register(ModuleName, 21, "pool does not permit liquidity exits")
	ErrZeroSwapOutput        = errors.Register(ModuleName, 22, "swap output rounds to zero")
	ErrZeroLPTokens          = errors.Register(ModuleName, 23, "LP token amount rounds to zero")
	ErrInvalidPoolStatus     = errors.Register(ModuleName, 24, "invalid pool status")
	ErrClosedPoolImmutable   = errors.Register(ModuleName, 25, "closed pool is immutable")
	ErrTWAPWindowUnavailable = errors.Register(ModuleName, 26, "requested TWAP window is unavailable")
	ErrInvalidPoolState      = errors.Register(ModuleName, 27, "invalid pool state")
	ErrPoolDenomNotAllowed   = errors.Register(ModuleName, 28, "counter-denom is not admitted for pool creation")
	ErrPoolCreatorNotAllowed = errors.Register(ModuleName, 29, "creator is not admitted to fund pools")
	ErrPoolRecordCapReached  = errors.Register(ModuleName, 30, "lifetime pool record cap reached")
)
