// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/research/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SubmitResearch_FullMethodName    = "/zerone.research.v1.Msg/SubmitResearch"
	Msg_ChallengeResearch_FullMethodName = "/zerone.research.v1.Msg/ChallengeResearch"
	Msg_ReviewResearch_FullMethodName    = "/zerone.research.v1.Msg/ReviewResearch"
	Msg_ResolveResearch_FullMethodName   = "/zerone.research.v1.Msg/ResolveResearch"
	Msg_CreateBounty_FullMethodName      = "/zerone.research.v1.Msg/CreateBounty"
	Msg_ClaimBounty_FullMethodName       = "/zerone.research.v1.Msg/ClaimBounty"
	Msg_FulfillBounty_FullMethodName     = "/zerone.research.v1.Msg/FulfillBounty"
	Msg_FundResearch_FullMethodName      = "/zerone.research.v1.Msg/FundResearch"
	Msg_UpdateParams_FullMethodName      = "/zerone.research.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the research module's transaction service.
type MsgClient interface {
	SubmitResearch(ctx context.Context, in *MsgSubmitResearch, opts ...grpc.CallOption) (*MsgSubmitResearchResponse, error)
	ChallengeResearch(ctx context.Context, in *MsgChallengeResearch, opts ...grpc.CallOption) (*MsgChallengeResearchResponse, error)
	ReviewResearch(ctx context.Context, in *MsgReviewResearch, opts ...grpc.CallOption) (*MsgReviewResearchResponse, error)
	ResolveResearch(ctx context.Context, in *MsgResolveResearch, opts ...grpc.CallOption) (*MsgResolveResearchResponse, error)
	CreateBounty(ctx context.Context, in *MsgCreateBounty, opts ...grpc.CallOption) (*MsgCreateBountyResponse, error)
	ClaimBounty(ctx context.Context, in *MsgClaimBounty, opts ...grpc.CallOption) (*MsgClaimBountyResponse, error)
	FulfillBounty(ctx context.Context, in *MsgFulfillBounty, opts ...grpc.CallOption) (*MsgFulfillBountyResponse, error)
	FundResearch(ctx context.Context, in *MsgFundResearch, opts ...grpc.CallOption) (*MsgFundResearchResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitResearch(ctx context.Context, in *MsgSubmitResearch, opts ...grpc.CallOption) (*MsgSubmitResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitResearchResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChallengeResearch(ctx context.Context, in *MsgChallengeResearch, opts ...grpc.CallOption) (*MsgChallengeResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgChallengeResearchResponse)
	err := c.cc.Invoke(ctx, Msg_ChallengeResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReviewResearch(ctx context.Context, in *MsgReviewResearch, opts ...grpc.CallOption) (*MsgReviewResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgReviewResearchResponse)
	err := c.cc.Invoke(ctx, Msg_ReviewResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResolveResearch(ctx context.Context, in *MsgResolveResearch, opts ...grpc.CallOption) (*MsgResolveResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgResolveResearchResponse)
	err := c.cc.Invoke(ctx, Msg_ResolveResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateBounty(ctx context.Context, in *MsgCreateBounty, opts ...grpc.CallOption) (*MsgCreateBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateBountyResponse)
	err := c.cc.Invoke(ctx, Msg_CreateBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimBounty(ctx context.Context, in *MsgClaimBounty, opts ...grpc.CallOption) (*MsgClaimBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClaimBountyResponse)
	err := c.cc.Invoke(ctx, Msg_ClaimBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FulfillBounty(ctx context.Context, in *MsgFulfillBounty, opts ...grpc.CallOption) (*MsgFulfillBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgFulfillBountyResponse)
	err := c.cc.Invoke(ctx, Msg_FulfillBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FundResearch(ctx context.Context, in *MsgFundResearch, opts ...grpc.CallOption) (*MsgFundResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgFundResearchResponse)
	err := c.cc.Invoke(ctx, Msg_FundResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the research module's transaction service.
type MsgServer interface {
	SubmitResearch(context.Context, *MsgSubmitResearch) (*MsgSubmitResearchResponse, error)
	ChallengeResearch(context.Context, *MsgChallengeResearch) (*MsgChallengeResearchResponse, error)
	ReviewResearch(context.Context, *MsgReviewResearch) (*MsgReviewResearchResponse, error)
	ResolveResearch(context.Context, *MsgResolveResearch) (*MsgResolveResearchResponse, error)
	CreateBounty(context.Context, *MsgCreateBounty) (*MsgCreateBountyResponse, error)
	ClaimBounty(context.Context, *MsgClaimBounty) (*MsgClaimBountyResponse, error)
	FulfillBounty(context.Context, *MsgFulfillBounty) (*MsgFulfillBountyResponse, error)
	FundResearch(context.Context, *MsgFundResearch) (*MsgFundResearchResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SubmitResearch(context.Context, *MsgSubmitResearch) (*MsgSubmitResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResearch not implemented")
}
func (UnimplementedMsgServer) ChallengeResearch(context.Context, *MsgChallengeResearch) (*MsgChallengeResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChallengeResearch not implemented")
}
func (UnimplementedMsgServer) ReviewResearch(context.Context, *MsgReviewResearch) (*MsgReviewResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewResearch not implemented")
}
func (UnimplementedMsgServer) ResolveResearch(context.Context, *MsgResolveResearch) (*MsgResolveResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveResearch not implemented")
}
func (UnimplementedMsgServer) CreateBounty(context.Context, *MsgCreateBounty) (*MsgCreateBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBounty not implemented")
}
func (UnimplementedMsgServer) ClaimBounty(context.Context, *MsgClaimBounty) (*MsgClaimBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimBounty not implemented")
}
func (UnimplementedMsgServer) FulfillBounty(context.Context, *MsgFulfillBounty) (*MsgFulfillBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FulfillBounty not implemented")
}
func (UnimplementedMsgServer) FundResearch(context.Context, *MsgFundResearch) (*MsgFundResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FundResearch not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SubmitResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitResearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitResearch(ctx, req.(*MsgSubmitResearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChallengeResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChallengeResearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChallengeResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ChallengeResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChallengeResearch(ctx, req.(*MsgChallengeResearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReviewResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReviewResearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReviewResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ReviewResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReviewResearch(ctx, req.(*MsgReviewResearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResolveResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResolveResearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResolveResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ResolveResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResolveResearch(ctx, req.(*MsgResolveResearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBounty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBounty(ctx, req.(*MsgCreateBounty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimBounty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClaimBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimBounty(ctx, req.(*MsgClaimBounty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FulfillBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFulfillBounty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FulfillBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FulfillBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FulfillBounty(ctx, req.(*MsgFulfillBounty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FundResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundResearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FundResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundResearch(ctx, req.(*MsgFundResearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.research.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResearch",
			Handler:    _Msg_SubmitResearch_Handler,
		},
		{
			MethodName: "ChallengeResearch",
			Handler:    _Msg_ChallengeResearch_Handler,
		},
		{
			MethodName: "ReviewResearch",
			Handler:    _Msg_ReviewResearch_Handler,
		},
		{
			MethodName: "ResolveResearch",
			Handler:    _Msg_ResolveResearch_Handler,
		},
		{
			MethodName: "CreateBounty",
			Handler:    _Msg_CreateBounty_Handler,
		},
		{
			MethodName: "ClaimBounty",
			Handler:    _Msg_ClaimBounty_Handler,
		},
		{
			MethodName: "FulfillBounty",
			Handler:    _Msg_FulfillBounty_Handler,
		},
		{
			MethodName: "FundResearch",
			Handler:    _Msg_FundResearch_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/research/v1/tx.proto",
}
