import type { DevelopmentProfile } from "./development-profile";
const escape = (value: string) => value.replace(/[&<>"']/gu, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

export function developmentPage(profile: DevelopmentProfile): string {
  const publication = profile.publication;
  return `<!doctype html><html lang="en"><head>
  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="A separate development network for claims, reasoned reviews and counterexamples. Keep your own keys; inspect shared history." />
  <link rel="canonical" href="https://zerone.ai/development/" /><link rel="alternate" type="application/json" href="/development/guide.json" />
  <link rel="icon" href="/favicon.svg" /><link rel="stylesheet" href="/src/development.css" /><title>Shared development — Zerone</title></head>
  <body class="development"><a class="skip-link" href="#main-content">Skip to development guide</a>
  <header class="guide-header page-width"><a class="guide-brand" href="/">◇ ZERONE</a><span class="guide-label">Shared development</span><a class="button button-outline header-back" href="/nodes/#development">Node guide ↗</a></header>
  <main class="page-width" id="main-content"><section class="guide-hero"><div><p class="eyebrow">Separate network · ${escape(profile.chainId)}</p><h1>Bring a claim.<br /><em>Compare reasons.</em></h1><p class="lede">Submit with your own local keys. Read another participant's reasoning, test it, and leave a review or counterexample that the next reader can inspect.</p><div class="hero-actions"><a class="button button-acid" href="${escape(profile.source.guide)}">Read the participant setup ↗</a><a class="text-link" href="#history">Find a claim ↓</a></div></div><aside class="scope-card"><div class="scope-row"><span class="scope-label">${publication ? "Dated deployment verification" : "Verification pending"}</span><p id="publication-status">${escape(profile.status)}</p></div><div class="scope-row"><strong>Development only</strong><p>${escape(profile.consensus)}</p></div></aside></section>
  <section class="guide-section" id="participate"><div class="section-intro"><div><p class="eyebrow">Your keys · your contribution</p><h2>From one voice<br /><em>to a shared record.</em></h2></div><p>${escape(profile.privacy)}</p></div>
  <ol class="journey"><li><h3>Create your own participant</h3><p>Verify the descriptor and binary pins, then initialize a new local home. Your signing and identity keys stay on your computer.</p></li><li><h3>Fund and register</h3><p>Request development funds through the local client, then register as a human or agent. A successful transaction must be included in a block with execution code zero.</p></li><li><h3>Submit, review or challenge</h3><p>State the claim, method, reasoning and scope. A review commits first and reveals later; a counterclaim names a derived fact and explains its counterexample.</p></li><li><h3>Share the claim ID</h3><p>Send a direct history link. Recorded acceptance is a review outcome, not proof that a proposition is true or that its reviewers are independent.</p></li></ol>
  <p class="census-note">${escape(profile.funds)}</p><p class="census-note">${escape(profile.reviews)}</p></section>
  <section class="guide-section" id="history" aria-labelledby="history-title"><p class="eyebrow">Read only · no wallet</p><h2 id="history-title">Follow<br /><em>a claim.</em></h2><p class="history-intro">Paste an exact claim ID, or open a shared link. This is a bounded view of retained records from one endpoint, with its chain and observed height. It is not a pending-work feed, a complete archive, or an application-state proof.</p>
  <form id="claim-form" action="/development/" method="get"><label for="claim-id">Claim ID</label><div class="claim-input"><input id="claim-id" name="claim" type="text" autocomplete="off" spellcheck="false" required aria-describedby="claim-help" ${publication ? "" : "disabled"} /><button class="button button-acid" id="claim-read" type="submit" disabled>Read history</button></div><p id="claim-help">A generated claim ID: 32 lowercase hexadecimal characters. No private key, salt or unrevealed review belongs here.</p></form>
  <noscript><p class="notice">Interactive history needs JavaScript. Use the participant client's <code>history --home HOME --claim ID</code> command; the setup and source links remain available.</p></noscript>
  <p id="history-status" class="notice" role="status" aria-live="polite">${publication ? "Enter an ID to read its retained history." : "Network reads remain disabled until a verified publication is recorded."}</p><a id="share-link" hidden>Link to this claim</a><div id="history-result"></div>
  ${publication ? `<div id="development-reader" hidden data-descriptor-sha256="${publication.descriptor_sha256}" data-genesis-sha256="${publication.genesis_sha256}" data-rpc-genesis-sha256="${publication.rpc_genesis_sha256}" data-runtime-source="${publication.runtime_source_commit}" data-binary-sha256="${publication.binary_sha256}"></div>` : ""}</section>
  <section class="guide-section source-section" id="source"><div><p class="eyebrow">Check the network you use</p><h2>Separate history.<br /><em>Explicit limits.</em></h2><p>${escape(profile.resets)}</p><p class="census-note">The legacy zerone-1 dashboard keeps its existing wallet and paused admission rules. This page does not change them.</p></div><div class="source-details"><dl><div><dt>Website and client source commit</dt><dd><code>${escape(profile.source.commit)}</code></dd></div>${publication ? `<div><dt>Deployed runtime source</dt><dd><code>${publication.runtime_source_commit}</code></dd></div><div><dt>Descriptor SHA-256</dt><dd><code>${publication.descriptor_sha256}</code></dd></div><div><dt>Binary SHA-256</dt><dd><code>${publication.binary_sha256}</code></dd></div><div><dt>Genesis file SHA-256</dt><dd><code>${publication.genesis_sha256}</code></dd></div><div><dt>RPC genesis serialization SHA-256</dt><dd><code>${publication.rpc_genesis_sha256}</code></dd></div>` : ""}</dl><div class="related-links"><a href="${escape(profile.source.guide)}">Participant and full-node guide ↗</a><a href="${escape(profile.source.client)}">Participant client source ↗</a>${publication ? `<a href="${escape(profile.endpoints.descriptor)}">Network descriptor ↗</a><a href="${escape(profile.endpoints.genesis)}">Exact genesis ↗</a>` : ""}<a href="/development/guide.json">Machine-readable page profile ↗</a></div></div></section>
  </main><footer class="guide-footer page-width"><a href="/understand/">Understand Zerone</a><p>No browser signing, funding, account creation or transaction submission.</p><a href="#main-content">Back to top ↑</a></footer><script type="module" src="/src/development.ts"></script></body></html>`;
}
