// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/qualification/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgQualifyByStake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	StakeAmount   string                 `protobuf:"bytes,3,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"` // uzrn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByStake) Reset() {
	*x = MsgQualifyByStake{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByStake) ProtoMessage() {}

func (x *MsgQualifyByStake) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByStake.ProtoReflect.Descriptor instead.
func (*MsgQualifyByStake) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgQualifyByStake) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgQualifyByStake) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgQualifyByStake) GetStakeAmount() string {
	if x != nil {
		return x.StakeAmount
	}
	return ""
}

type MsgQualifyByStakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByStakeResponse) Reset() {
	*x = MsgQualifyByStakeResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByStakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByStakeResponse) ProtoMessage() {}

func (x *MsgQualifyByStakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByStakeResponse.ProtoReflect.Descriptor instead.
func (*MsgQualifyByStakeResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgQualifyByTrackRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByTrackRecord) Reset() {
	*x = MsgQualifyByTrackRecord{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByTrackRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByTrackRecord) ProtoMessage() {}

func (x *MsgQualifyByTrackRecord) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByTrackRecord.ProtoReflect.Descriptor instead.
func (*MsgQualifyByTrackRecord) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgQualifyByTrackRecord) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgQualifyByTrackRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type MsgQualifyByTrackRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByTrackRecordResponse) Reset() {
	*x = MsgQualifyByTrackRecordResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByTrackRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByTrackRecordResponse) ProtoMessage() {}

func (x *MsgQualifyByTrackRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByTrackRecordResponse.ProtoReflect.Descriptor instead.
func (*MsgQualifyByTrackRecordResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgQualifyByCrossReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	TargetDomain  string                 `protobuf:"bytes,2,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	SourceDomain  string                 `protobuf:"bytes,3,opt,name=source_domain,json=sourceDomain,proto3" json:"source_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByCrossReference) Reset() {
	*x = MsgQualifyByCrossReference{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByCrossReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByCrossReference) ProtoMessage() {}

func (x *MsgQualifyByCrossReference) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByCrossReference.ProtoReflect.Descriptor instead.
func (*MsgQualifyByCrossReference) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgQualifyByCrossReference) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgQualifyByCrossReference) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *MsgQualifyByCrossReference) GetSourceDomain() string {
	if x != nil {
		return x.SourceDomain
	}
	return ""
}

type MsgQualifyByCrossReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByCrossReferenceResponse) Reset() {
	*x = MsgQualifyByCrossReferenceResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByCrossReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByCrossReferenceResponse) ProtoMessage() {}

func (x *MsgQualifyByCrossReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByCrossReferenceResponse.ProtoReflect.Descriptor instead.
func (*MsgQualifyByCrossReferenceResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgQualifyByInheritance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	TargetDomain  string                 `protobuf:"bytes,2,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	ParentDomain  string                 `protobuf:"bytes,3,opt,name=parent_domain,json=parentDomain,proto3" json:"parent_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByInheritance) Reset() {
	*x = MsgQualifyByInheritance{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByInheritance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByInheritance) ProtoMessage() {}

func (x *MsgQualifyByInheritance) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByInheritance.ProtoReflect.Descriptor instead.
func (*MsgQualifyByInheritance) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgQualifyByInheritance) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgQualifyByInheritance) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *MsgQualifyByInheritance) GetParentDomain() string {
	if x != nil {
		return x.ParentDomain
	}
	return ""
}

type MsgQualifyByInheritanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQualifyByInheritanceResponse) Reset() {
	*x = MsgQualifyByInheritanceResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQualifyByInheritanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQualifyByInheritanceResponse) ProtoMessage() {}

func (x *MsgQualifyByInheritanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQualifyByInheritanceResponse.ProtoReflect.Descriptor instead.
func (*MsgQualifyByInheritanceResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{7}
}

type MsgEndorseQualification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endorser      string                 `protobuf:"bytes,1,opt,name=endorser,proto3" json:"endorser,omitempty"`
	Validator     string                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Weight        uint32                 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndorseQualification) Reset() {
	*x = MsgEndorseQualification{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndorseQualification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndorseQualification) ProtoMessage() {}

func (x *MsgEndorseQualification) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndorseQualification.ProtoReflect.Descriptor instead.
func (*MsgEndorseQualification) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgEndorseQualification) GetEndorser() string {
	if x != nil {
		return x.Endorser
	}
	return ""
}

func (x *MsgEndorseQualification) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgEndorseQualification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MsgEndorseQualification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MsgEndorseQualification) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type MsgEndorseQualificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndorsementId uint64                 `protobuf:"varint,1,opt,name=endorsement_id,json=endorsementId,proto3" json:"endorsement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndorseQualificationResponse) Reset() {
	*x = MsgEndorseQualificationResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndorseQualificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndorseQualificationResponse) ProtoMessage() {}

func (x *MsgEndorseQualificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndorseQualificationResponse.ProtoReflect.Descriptor instead.
func (*MsgEndorseQualificationResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgEndorseQualificationResponse) GetEndorsementId() uint64 {
	if x != nil {
		return x.EndorsementId
	}
	return 0
}

type MsgRenewQualification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRenewQualification) Reset() {
	*x = MsgRenewQualification{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRenewQualification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRenewQualification) ProtoMessage() {}

func (x *MsgRenewQualification) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRenewQualification.ProtoReflect.Descriptor instead.
func (*MsgRenewQualification) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRenewQualification) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgRenewQualification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type MsgRenewQualificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRenewQualificationResponse) Reset() {
	*x = MsgRenewQualificationResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRenewQualificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRenewQualificationResponse) ProtoMessage() {}

func (x *MsgRenewQualificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRenewQualificationResponse.ProtoReflect.Descriptor instead.
func (*MsgRenewQualificationResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{11}
}

type MsgWithdrawQualification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgWithdrawQualification) Reset() {
	*x = MsgWithdrawQualification{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgWithdrawQualification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgWithdrawQualification) ProtoMessage() {}

func (x *MsgWithdrawQualification) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgWithdrawQualification.ProtoReflect.Descriptor instead.
func (*MsgWithdrawQualification) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MsgWithdrawQualification) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgWithdrawQualification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type MsgWithdrawQualificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgWithdrawQualificationResponse) Reset() {
	*x = MsgWithdrawQualificationResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgWithdrawQualificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgWithdrawQualificationResponse) ProtoMessage() {}

func (x *MsgWithdrawQualificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgWithdrawQualificationResponse.ProtoReflect.Descriptor instead.
func (*MsgWithdrawQualificationResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{13}
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{14}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_qualification_v1_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_qualification_v1_tx_proto_rawDescGZIP(), []int{15}
}

var File_zerone_qualification_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_qualification_v1_tx_proto_rawDesc = "" +
	"\n" +
	" zerone/qualification/v1/tx.proto\x12\x17zerone.qualification.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a#zerone/qualification/v1/types.proto\x1a%zerone/qualification/v1/genesis.proto\"|\n" +
	"\x11MsgQualifyByStake\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12!\n" +
	"\fstake_amount\x18\x03 \x01(\tR\vstakeAmount:\x0e\x82\xe7\xb0*\tvalidator\"\x1b\n" +
	"\x19MsgQualifyByStakeResponse\"_\n" +
	"\x17MsgQualifyByTrackRecord\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain:\x0e\x82\xe7\xb0*\tvalidator\"!\n" +
	"\x1fMsgQualifyByTrackRecordResponse\"\x94\x01\n" +
	"\x1aMsgQualifyByCrossReference\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12#\n" +
	"\rtarget_domain\x18\x02 \x01(\tR\ftargetDomain\x12#\n" +
	"\rsource_domain\x18\x03 \x01(\tR\fsourceDomain:\x0e\x82\xe7\xb0*\tvalidator\"$\n" +
	"\"MsgQualifyByCrossReferenceResponse\"\x91\x01\n" +
	"\x17MsgQualifyByInheritance\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12#\n" +
	"\rtarget_domain\x18\x02 \x01(\tR\ftargetDomain\x12#\n" +
	"\rparent_domain\x18\x03 \x01(\tR\fparentDomain:\x0e\x82\xe7\xb0*\tvalidator\"!\n" +
	"\x1fMsgQualifyByInheritanceResponse\"\xaa\x01\n" +
	"\x17MsgEndorseQualification\x12\x1a\n" +
	"\bendorser\x18\x01 \x01(\tR\bendorser\x12\x1c\n" +
	"\tvalidator\x18\x02 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\rR\x06weight:\r\x82\xe7\xb0*\bendorser\"H\n" +
	"\x1fMsgEndorseQualificationResponse\x12%\n" +
	"\x0eendorsement_id\x18\x01 \x01(\x04R\rendorsementId\"]\n" +
	"\x15MsgRenewQualification\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain:\x0e\x82\xe7\xb0*\tvalidator\"\x1f\n" +
	"\x1dMsgRenewQualificationResponse\"`\n" +
	"\x18MsgWithdrawQualification\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain:\x0e\x82\xe7\xb0*\tvalidator\"\"\n" +
	" MsgWithdrawQualificationResponse\"x\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x127\n" +
	"\x06params\x18\x02 \x01(\v2\x1f.zerone.qualification.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\x8d\b\n" +
	"\x03Msg\x12p\n" +
	"\x0eQualifyByStake\x12*.zerone.qualification.v1.MsgQualifyByStake\x1a2.zerone.qualification.v1.MsgQualifyByStakeResponse\x12\x82\x01\n" +
	"\x14QualifyByTrackRecord\x120.zerone.qualification.v1.MsgQualifyByTrackRecord\x1a8.zerone.qualification.v1.MsgQualifyByTrackRecordResponse\x12\x8b\x01\n" +
	"\x17QualifyByCrossReference\x123.zerone.qualification.v1.MsgQualifyByCrossReference\x1a;.zerone.qualification.v1.MsgQualifyByCrossReferenceResponse\x12\x82\x01\n" +
	"\x14QualifyByInheritance\x120.zerone.qualification.v1.MsgQualifyByInheritance\x1a8.zerone.qualification.v1.MsgQualifyByInheritanceResponse\x12\x82\x01\n" +
	"\x14EndorseQualification\x120.zerone.qualification.v1.MsgEndorseQualification\x1a8.zerone.qualification.v1.MsgEndorseQualificationResponse\x12|\n" +
	"\x12RenewQualification\x12..zerone.qualification.v1.MsgRenewQualification\x1a6.zerone.qualification.v1.MsgRenewQualificationResponse\x12\x85\x01\n" +
	"\x15WithdrawQualification\x121.zerone.qualification.v1.MsgWithdrawQualification\x1a9.zerone.qualification.v1.MsgWithdrawQualificationResponse\x12j\n" +
	"\fUpdateParams\x12(.zerone.qualification.v1.MsgUpdateParams\x1a0.zerone.qualification.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B6Z4github.com/zerone-chain/zerone/x/qualification/typesb\x06proto3"

var (
	file_zerone_qualification_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_qualification_v1_tx_proto_rawDescData []byte
)

func file_zerone_qualification_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_qualification_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_qualification_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_qualification_v1_tx_proto_rawDesc), len(file_zerone_qualification_v1_tx_proto_rawDesc)))
	})
	return file_zerone_qualification_v1_tx_proto_rawDescData
}

var file_zerone_qualification_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_zerone_qualification_v1_tx_proto_goTypes = []any{
	(*MsgQualifyByStake)(nil),                  // 0: zerone.qualification.v1.MsgQualifyByStake
	(*MsgQualifyByStakeResponse)(nil),          // 1: zerone.qualification.v1.MsgQualifyByStakeResponse
	(*MsgQualifyByTrackRecord)(nil),            // 2: zerone.qualification.v1.MsgQualifyByTrackRecord
	(*MsgQualifyByTrackRecordResponse)(nil),    // 3: zerone.qualification.v1.MsgQualifyByTrackRecordResponse
	(*MsgQualifyByCrossReference)(nil),         // 4: zerone.qualification.v1.MsgQualifyByCrossReference
	(*MsgQualifyByCrossReferenceResponse)(nil), // 5: zerone.qualification.v1.MsgQualifyByCrossReferenceResponse
	(*MsgQualifyByInheritance)(nil),            // 6: zerone.qualification.v1.MsgQualifyByInheritance
	(*MsgQualifyByInheritanceResponse)(nil),    // 7: zerone.qualification.v1.MsgQualifyByInheritanceResponse
	(*MsgEndorseQualification)(nil),            // 8: zerone.qualification.v1.MsgEndorseQualification
	(*MsgEndorseQualificationResponse)(nil),    // 9: zerone.qualification.v1.MsgEndorseQualificationResponse
	(*MsgRenewQualification)(nil),              // 10: zerone.qualification.v1.MsgRenewQualification
	(*MsgRenewQualificationResponse)(nil),      // 11: zerone.qualification.v1.MsgRenewQualificationResponse
	(*MsgWithdrawQualification)(nil),           // 12: zerone.qualification.v1.MsgWithdrawQualification
	(*MsgWithdrawQualificationResponse)(nil),   // 13: zerone.qualification.v1.MsgWithdrawQualificationResponse
	(*MsgUpdateParams)(nil),                    // 14: zerone.qualification.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),            // 15: zerone.qualification.v1.MsgUpdateParamsResponse
	(*Params)(nil),                             // 16: zerone.qualification.v1.Params
}
var file_zerone_qualification_v1_tx_proto_depIdxs = []int32{
	16, // 0: zerone.qualification.v1.MsgUpdateParams.params:type_name -> zerone.qualification.v1.Params
	0,  // 1: zerone.qualification.v1.Msg.QualifyByStake:input_type -> zerone.qualification.v1.MsgQualifyByStake
	2,  // 2: zerone.qualification.v1.Msg.QualifyByTrackRecord:input_type -> zerone.qualification.v1.MsgQualifyByTrackRecord
	4,  // 3: zerone.qualification.v1.Msg.QualifyByCrossReference:input_type -> zerone.qualification.v1.MsgQualifyByCrossReference
	6,  // 4: zerone.qualification.v1.Msg.QualifyByInheritance:input_type -> zerone.qualification.v1.MsgQualifyByInheritance
	8,  // 5: zerone.qualification.v1.Msg.EndorseQualification:input_type -> zerone.qualification.v1.MsgEndorseQualification
	10, // 6: zerone.qualification.v1.Msg.RenewQualification:input_type -> zerone.qualification.v1.MsgRenewQualification
	12, // 7: zerone.qualification.v1.Msg.WithdrawQualification:input_type -> zerone.qualification.v1.MsgWithdrawQualification
	14, // 8: zerone.qualification.v1.Msg.UpdateParams:input_type -> zerone.qualification.v1.MsgUpdateParams
	1,  // 9: zerone.qualification.v1.Msg.QualifyByStake:output_type -> zerone.qualification.v1.MsgQualifyByStakeResponse
	3,  // 10: zerone.qualification.v1.Msg.QualifyByTrackRecord:output_type -> zerone.qualification.v1.MsgQualifyByTrackRecordResponse
	5,  // 11: zerone.qualification.v1.Msg.QualifyByCrossReference:output_type -> zerone.qualification.v1.MsgQualifyByCrossReferenceResponse
	7,  // 12: zerone.qualification.v1.Msg.QualifyByInheritance:output_type -> zerone.qualification.v1.MsgQualifyByInheritanceResponse
	9,  // 13: zerone.qualification.v1.Msg.EndorseQualification:output_type -> zerone.qualification.v1.MsgEndorseQualificationResponse
	11, // 14: zerone.qualification.v1.Msg.RenewQualification:output_type -> zerone.qualification.v1.MsgRenewQualificationResponse
	13, // 15: zerone.qualification.v1.Msg.WithdrawQualification:output_type -> zerone.qualification.v1.MsgWithdrawQualificationResponse
	15, // 16: zerone.qualification.v1.Msg.UpdateParams:output_type -> zerone.qualification.v1.MsgUpdateParamsResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_qualification_v1_tx_proto_init() }
func file_zerone_qualification_v1_tx_proto_init() {
	if File_zerone_qualification_v1_tx_proto != nil {
		return
	}
	file_zerone_qualification_v1_types_proto_init()
	file_zerone_qualification_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_qualification_v1_tx_proto_rawDesc), len(file_zerone_qualification_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_qualification_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_qualification_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_qualification_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_qualification_v1_tx_proto = out.File
	file_zerone_qualification_v1_tx_proto_goTypes = nil
	file_zerone_qualification_v1_tx_proto_depIdxs = nil
}
