// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/ibcratelimit/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgAddRateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"` // governance address
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	MaxSend       string                 `protobuf:"bytes,4,opt,name=max_send,json=maxSend,proto3" json:"max_send,omitempty"` // bigint string
	MaxRecv       string                 `protobuf:"bytes,5,opt,name=max_recv,json=maxRecv,proto3" json:"max_recv,omitempty"` // bigint string
	WindowBlocks  uint64                 `protobuf:"varint,6,opt,name=window_blocks,json=windowBlocks,proto3" json:"window_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAddRateLimit) Reset() {
	*x = MsgAddRateLimit{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAddRateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAddRateLimit) ProtoMessage() {}

func (x *MsgAddRateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAddRateLimit.ProtoReflect.Descriptor instead.
func (*MsgAddRateLimit) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAddRateLimit) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgAddRateLimit) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MsgAddRateLimit) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgAddRateLimit) GetMaxSend() string {
	if x != nil {
		return x.MaxSend
	}
	return ""
}

func (x *MsgAddRateLimit) GetMaxRecv() string {
	if x != nil {
		return x.MaxRecv
	}
	return ""
}

func (x *MsgAddRateLimit) GetWindowBlocks() uint64 {
	if x != nil {
		return x.WindowBlocks
	}
	return 0
}

type MsgAddRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAddRateLimitResponse) Reset() {
	*x = MsgAddRateLimitResponse{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAddRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAddRateLimitResponse) ProtoMessage() {}

func (x *MsgAddRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAddRateLimitResponse.ProtoReflect.Descriptor instead.
func (*MsgAddRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgRemoveRateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"` // governance address
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRemoveRateLimit) Reset() {
	*x = MsgRemoveRateLimit{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRemoveRateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveRateLimit) ProtoMessage() {}

func (x *MsgRemoveRateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveRateLimit.ProtoReflect.Descriptor instead.
func (*MsgRemoveRateLimit) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRemoveRateLimit) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRemoveRateLimit) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MsgRemoveRateLimit) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type MsgRemoveRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRemoveRateLimitResponse) Reset() {
	*x = MsgRemoveRateLimitResponse{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRemoveRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveRateLimitResponse) ProtoMessage() {}

func (x *MsgRemoveRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveRateLimitResponse.ProtoReflect.Descriptor instead.
func (*MsgRemoveRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"` // governance address
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_zerone_ibcratelimit_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_ibcratelimit_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1fzerone/ibcratelimit/v1/tx.proto\x12\x16zerone.ibcratelimit.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a$zerone/ibcratelimit/v1/genesis.proto\"\xcf\x01\n" +
	"\x0fMsgAddRateLimit\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom\x12\x19\n" +
	"\bmax_send\x18\x04 \x01(\tR\amaxSend\x12\x19\n" +
	"\bmax_recv\x18\x05 \x01(\tR\amaxRecv\x12#\n" +
	"\rwindow_blocks\x18\x06 \x01(\x04R\fwindowBlocks:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgAddRateLimitResponse\"w\n" +
	"\x12MsgRemoveRateLimit\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom:\x0e\x82\xe7\xb0*\tauthority\"\x1c\n" +
	"\x1aMsgRemoveRateLimitResponse\"w\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x126\n" +
	"\x06params\x18\x02 \x01(\v2\x1e.zerone.ibcratelimit.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xd3\x02\n" +
	"\x03Msg\x12h\n" +
	"\fAddRateLimit\x12'.zerone.ibcratelimit.v1.MsgAddRateLimit\x1a/.zerone.ibcratelimit.v1.MsgAddRateLimitResponse\x12q\n" +
	"\x0fRemoveRateLimit\x12*.zerone.ibcratelimit.v1.MsgRemoveRateLimit\x1a2.zerone.ibcratelimit.v1.MsgRemoveRateLimitResponse\x12h\n" +
	"\fUpdateParams\x12'.zerone.ibcratelimit.v1.MsgUpdateParams\x1a/.zerone.ibcratelimit.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B5Z3github.com/zerone-chain/zerone/x/ibcratelimit/typesb\x06proto3"

var (
	file_zerone_ibcratelimit_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_ibcratelimit_v1_tx_proto_rawDescData []byte
)

func file_zerone_ibcratelimit_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_ibcratelimit_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_ibcratelimit_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_ibcratelimit_v1_tx_proto_rawDesc), len(file_zerone_ibcratelimit_v1_tx_proto_rawDesc)))
	})
	return file_zerone_ibcratelimit_v1_tx_proto_rawDescData
}

var file_zerone_ibcratelimit_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zerone_ibcratelimit_v1_tx_proto_goTypes = []any{
	(*MsgAddRateLimit)(nil),            // 0: zerone.ibcratelimit.v1.MsgAddRateLimit
	(*MsgAddRateLimitResponse)(nil),    // 1: zerone.ibcratelimit.v1.MsgAddRateLimitResponse
	(*MsgRemoveRateLimit)(nil),         // 2: zerone.ibcratelimit.v1.MsgRemoveRateLimit
	(*MsgRemoveRateLimitResponse)(nil), // 3: zerone.ibcratelimit.v1.MsgRemoveRateLimitResponse
	(*MsgUpdateParams)(nil),            // 4: zerone.ibcratelimit.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),    // 5: zerone.ibcratelimit.v1.MsgUpdateParamsResponse
	(*Params)(nil),                     // 6: zerone.ibcratelimit.v1.Params
}
var file_zerone_ibcratelimit_v1_tx_proto_depIdxs = []int32{
	6, // 0: zerone.ibcratelimit.v1.MsgUpdateParams.params:type_name -> zerone.ibcratelimit.v1.Params
	0, // 1: zerone.ibcratelimit.v1.Msg.AddRateLimit:input_type -> zerone.ibcratelimit.v1.MsgAddRateLimit
	2, // 2: zerone.ibcratelimit.v1.Msg.RemoveRateLimit:input_type -> zerone.ibcratelimit.v1.MsgRemoveRateLimit
	4, // 3: zerone.ibcratelimit.v1.Msg.UpdateParams:input_type -> zerone.ibcratelimit.v1.MsgUpdateParams
	1, // 4: zerone.ibcratelimit.v1.Msg.AddRateLimit:output_type -> zerone.ibcratelimit.v1.MsgAddRateLimitResponse
	3, // 5: zerone.ibcratelimit.v1.Msg.RemoveRateLimit:output_type -> zerone.ibcratelimit.v1.MsgRemoveRateLimitResponse
	5, // 6: zerone.ibcratelimit.v1.Msg.UpdateParams:output_type -> zerone.ibcratelimit.v1.MsgUpdateParamsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zerone_ibcratelimit_v1_tx_proto_init() }
func file_zerone_ibcratelimit_v1_tx_proto_init() {
	if File_zerone_ibcratelimit_v1_tx_proto != nil {
		return
	}
	file_zerone_ibcratelimit_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_ibcratelimit_v1_tx_proto_rawDesc), len(file_zerone_ibcratelimit_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_ibcratelimit_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_ibcratelimit_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_ibcratelimit_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_ibcratelimit_v1_tx_proto = out.File
	file_zerone_ibcratelimit_v1_tx_proto_goTypes = nil
	file_zerone_ibcratelimit_v1_tx_proto_depIdxs = nil
}
