// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/ibcratelimit/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RateLimit defines a per-(channel, denom) flow cap with a sliding window.
type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	MaxSend       string                 `protobuf:"bytes,3,opt,name=max_send,json=maxSend,proto3" json:"max_send,omitempty"` // bigint string (uzrn)
	MaxRecv       string                 `protobuf:"bytes,4,opt,name=max_recv,json=maxRecv,proto3" json:"max_recv,omitempty"` // bigint string (uzrn)
	WindowBlocks  uint64                 `protobuf:"varint,5,opt,name=window_blocks,json=windowBlocks,proto3" json:"window_blocks,omitempty"`
	CurrentSend   string                 `protobuf:"bytes,6,opt,name=current_send,json=currentSend,proto3" json:"current_send,omitempty"`  // bigint string — accumulated in current window
	CurrentRecv   string                 `protobuf:"bytes,7,opt,name=current_recv,json=currentRecv,proto3" json:"current_recv,omitempty"`  // bigint string — accumulated in current window
	WindowStart   uint64                 `protobuf:"varint,8,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"` // block height at which the current window began
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_zerone_ibcratelimit_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimit) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RateLimit) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *RateLimit) GetMaxSend() string {
	if x != nil {
		return x.MaxSend
	}
	return ""
}

func (x *RateLimit) GetMaxRecv() string {
	if x != nil {
		return x.MaxRecv
	}
	return ""
}

func (x *RateLimit) GetWindowBlocks() uint64 {
	if x != nil {
		return x.WindowBlocks
	}
	return 0
}

func (x *RateLimit) GetCurrentSend() string {
	if x != nil {
		return x.CurrentSend
	}
	return ""
}

func (x *RateLimit) GetCurrentRecv() string {
	if x != nil {
		return x.CurrentRecv
	}
	return ""
}

func (x *RateLimit) GetWindowStart() uint64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

// PacketFlow records an outbound packet for quota reversal on timeout/error ack.
type PacketFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"` // bigint string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketFlow) Reset() {
	*x = PacketFlow{}
	mi := &file_zerone_ibcratelimit_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFlow) ProtoMessage() {}

func (x *PacketFlow) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_ibcratelimit_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFlow.ProtoReflect.Descriptor instead.
func (*PacketFlow) Descriptor() ([]byte, []int) {
	return file_zerone_ibcratelimit_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PacketFlow) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PacketFlow) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PacketFlow) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *PacketFlow) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_zerone_ibcratelimit_v1_types_proto protoreflect.FileDescriptor

const file_zerone_ibcratelimit_v1_types_proto_rawDesc = "" +
	"\n" +
	"\"zerone/ibcratelimit/v1/types.proto\x12\x16zerone.ibcratelimit.v1\"\x84\x02\n" +
	"\tRateLimit\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x19\n" +
	"\bmax_send\x18\x03 \x01(\tR\amaxSend\x12\x19\n" +
	"\bmax_recv\x18\x04 \x01(\tR\amaxRecv\x12#\n" +
	"\rwindow_blocks\x18\x05 \x01(\x04R\fwindowBlocks\x12!\n" +
	"\fcurrent_send\x18\x06 \x01(\tR\vcurrentSend\x12!\n" +
	"\fcurrent_recv\x18\a \x01(\tR\vcurrentRecv\x12!\n" +
	"\fwindow_start\x18\b \x01(\x04R\vwindowStart\"u\n" +
	"\n" +
	"PacketFlow\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amountB5Z3github.com/zerone-chain/zerone/x/ibcratelimit/typesb\x06proto3"

var (
	file_zerone_ibcratelimit_v1_types_proto_rawDescOnce sync.Once
	file_zerone_ibcratelimit_v1_types_proto_rawDescData []byte
)

func file_zerone_ibcratelimit_v1_types_proto_rawDescGZIP() []byte {
	file_zerone_ibcratelimit_v1_types_proto_rawDescOnce.Do(func() {
		file_zerone_ibcratelimit_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_ibcratelimit_v1_types_proto_rawDesc), len(file_zerone_ibcratelimit_v1_types_proto_rawDesc)))
	})
	return file_zerone_ibcratelimit_v1_types_proto_rawDescData
}

var file_zerone_ibcratelimit_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zerone_ibcratelimit_v1_types_proto_goTypes = []any{
	(*RateLimit)(nil),  // 0: zerone.ibcratelimit.v1.RateLimit
	(*PacketFlow)(nil), // 1: zerone.ibcratelimit.v1.PacketFlow
}
var file_zerone_ibcratelimit_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zerone_ibcratelimit_v1_types_proto_init() }
func file_zerone_ibcratelimit_v1_types_proto_init() {
	if File_zerone_ibcratelimit_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_ibcratelimit_v1_types_proto_rawDesc), len(file_zerone_ibcratelimit_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_ibcratelimit_v1_types_proto_goTypes,
		DependencyIndexes: file_zerone_ibcratelimit_v1_types_proto_depIdxs,
		MessageInfos:      file_zerone_ibcratelimit_v1_types_proto_msgTypes,
	}.Build()
	File_zerone_ibcratelimit_v1_types_proto = out.File
	file_zerone_ibcratelimit_v1_types_proto_goTypes = nil
	file_zerone_ibcratelimit_v1_types_proto_depIdxs = nil
}
