package types

import "cosmossdk.io/errors"

var (
	ErrProjectNotFound           = errors.Register(ModuleName, 2, "project not found")
	ErrServiceNotFound           = errors.Register(ModuleName, 3, "service not found")
	ErrTaskNotFound              = errors.Register(ModuleName, 4, "task not found")
	ErrSeedAlreadyPlanted        = errors.Register(ModuleName, 5, "opportunity seed already planted")
	ErrInvalidTaskState          = errors.Register(ModuleName, 6, "invalid task state transition")
	ErrInvalidPhaseTransition    = errors.Register(ModuleName, 7, "invalid project phase transition")
	ErrNotFounder                = errors.Register(ModuleName, 8, "sender is not the project founder")
	ErrMaxTasksReached           = errors.Register(ModuleName, 9, "max tasks per project reached")
	ErrNotAssignee               = errors.Register(ModuleName, 10, "sender is not the task assignee")
	ErrMaxContributorsReached    = errors.Register(ModuleName, 11, "max contributors reached")
	ErrMaxApplicationsReached    = errors.Register(ModuleName, 12, "max applications reached")
	ErrAlreadyApplied            = errors.Register(ModuleName, 13, "already applied to this project")
	ErrApplicationNotFound       = errors.Register(ModuleName, 14, "application not found")
	ErrSeedNotFound              = errors.Register(ModuleName, 15, "opportunity seed not found")
	ErrSeedExpired               = errors.Register(ModuleName, 16, "opportunity seed has expired")
	ErrInvalidServiceState       = errors.Register(ModuleName, 17, "invalid service state transition")
	ErrMaxRejectionsReached      = errors.Register(ModuleName, 18, "max rejections reached for task")
	ErrNotContributor            = errors.Register(ModuleName, 19, "sender is not a project contributor")
	ErrInsufficientBudget        = errors.Register(ModuleName, 20, "insufficient project budget")
	ErrSelfReview                = errors.Register(ModuleName, 21, "reviewer cannot be the task assignee")
	ErrNoServices                = errors.Register(ModuleName, 22, "project must have at least one service to deploy")
	ErrServiceNotActive          = errors.Register(ModuleName, 23, "service is not active")
	ErrInsufficientPayment       = errors.Register(ModuleName, 24, "insufficient payment for service call")
	ErrServiceCallFailed         = errors.Register(ModuleName, 25, "service call execution failed")
	ErrSeedAlreadyClaimed        = errors.Register(ModuleName, 26, "opportunity seed already claimed")
	ErrSubscriptionNotFound      = errors.Register(ModuleName, 27, "subscription not found")
	ErrBountyExceedsBudget       = errors.Register(ModuleName, 28, "bounty exceeds remaining project budget")
	ErrAbandonTimelockActive     = errors.Register(ModuleName, 29, "abandon timelock is active; wait for expiry or cancel")
	ErrAbandonRequiresConsent    = errors.Register(ModuleName, 30, "abandon requires contributor majority consent")
	ErrNoActiveAbandonProposal   = errors.Register(ModuleName, 31, "no active abandon proposal for this project")
	ErrDisputeSlashFailed        = errors.Register(ModuleName, 32, "dispute bounty slash failed")
	ErrInsufficientModuleBalance = errors.Register(ModuleName, 33, "insufficient tree module balance for transfer")
)
