// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/tree/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContributorRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Did            string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAtBlock  uint64                 `protobuf:"varint,3,opt,name=joined_at_block,json=joinedAtBlock,proto3" json:"joined_at_block,omitempty"`
	TasksCompleted uint32                 `protobuf:"varint,4,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	TotalEarned    string                 `protobuf:"bytes,5,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContributorRecord) Reset() {
	*x = ContributorRecord{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributorRecord) ProtoMessage() {}

func (x *ContributorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributorRecord.ProtoReflect.Descriptor instead.
func (*ContributorRecord) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ContributorRecord) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ContributorRecord) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ContributorRecord) GetJoinedAtBlock() uint64 {
	if x != nil {
		return x.JoinedAtBlock
	}
	return 0
}

func (x *ContributorRecord) GetTasksCompleted() uint32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *ContributorRecord) GetTotalEarned() string {
	if x != nil {
		return x.TotalEarned
	}
	return ""
}

type ProductSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceType   string                 `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Requirements  []string               `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MvpCriteria   string                 `protobuf:"bytes,4,opt,name=mvp_criteria,json=mvpCriteria,proto3" json:"mvp_criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSpec) Reset() {
	*x = ProductSpec{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSpec) ProtoMessage() {}

func (x *ProductSpec) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSpec.ProtoReflect.Descriptor instead.
func (*ProductSpec) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProductSpec) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ProductSpec) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ProductSpec) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProductSpec) GetMvpCriteria() string {
	if x != nil {
		return x.MvpCriteria
	}
	return ""
}

type FundingSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Terms         string                 `protobuf:"bytes,3,opt,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingSource) Reset() {
	*x = FundingSource{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingSource) ProtoMessage() {}

func (x *FundingSource) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingSource.ProtoReflect.Descriptor instead.
func (*FundingSource) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *FundingSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FundingSource) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FundingSource) GetTerms() string {
	if x != nil {
		return x.Terms
	}
	return ""
}

type DemandSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Evidence      map[string]string      `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Strength      string                 `protobuf:"bytes,3,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandSignal) Reset() {
	*x = DemandSignal{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandSignal) ProtoMessage() {}

func (x *DemandSignal) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandSignal.ProtoReflect.Descriptor instead.
func (*DemandSignal) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *DemandSignal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DemandSignal) GetEvidence() map[string]string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DemandSignal) GetStrength() string {
	if x != nil {
		return x.Strength
	}
	return ""
}

type ProjectApplication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Did            string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	ProposedRole   string                 `protobuf:"bytes,2,opt,name=proposed_role,json=proposedRole,proto3" json:"proposed_role,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Capabilities   []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	AppliedAtBlock uint64                 `protobuf:"varint,5,opt,name=applied_at_block,json=appliedAtBlock,proto3" json:"applied_at_block,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectApplication) Reset() {
	*x = ProjectApplication{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectApplication) ProtoMessage() {}

func (x *ProjectApplication) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectApplication.ProtoReflect.Descriptor instead.
func (*ProjectApplication) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectApplication) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ProjectApplication) GetProposedRole() string {
	if x != nil {
		return x.ProposedRole
	}
	return ""
}

func (x *ProjectApplication) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProjectApplication) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProjectApplication) GetAppliedAtBlock() uint64 {
	if x != nil {
		return x.AppliedAtBlock
	}
	return 0
}

func (x *ProjectApplication) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskDeliverable struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Uri              string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	SubmittedAtBlock uint64                 `protobuf:"varint,3,opt,name=submitted_at_block,json=submittedAtBlock,proto3" json:"submitted_at_block,omitempty"`
	VerifiedBy       []string               `protobuf:"bytes,4,rep,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskDeliverable) Reset() {
	*x = TaskDeliverable{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDeliverable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDeliverable) ProtoMessage() {}

func (x *TaskDeliverable) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDeliverable.ProtoReflect.Descriptor instead.
func (*TaskDeliverable) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *TaskDeliverable) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TaskDeliverable) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TaskDeliverable) GetSubmittedAtBlock() uint64 {
	if x != nil {
		return x.SubmittedAtBlock
	}
	return 0
}

func (x *TaskDeliverable) GetVerifiedBy() []string {
	if x != nil {
		return x.VerifiedBy
	}
	return nil
}

type ProductProject struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Phase               string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	PreviousPhase       string                 `protobuf:"bytes,5,opt,name=previous_phase,json=previousPhase,proto3" json:"previous_phase,omitempty"`
	CreatedAtBlock      uint64                 `protobuf:"varint,6,opt,name=created_at_block,json=createdAtBlock,proto3" json:"created_at_block,omitempty"`
	PhaseChangedAtBlock uint64                 `protobuf:"varint,7,opt,name=phase_changed_at_block,json=phaseChangedAtBlock,proto3" json:"phase_changed_at_block,omitempty"`
	KnowledgeDomain     string                 `protobuf:"bytes,8,opt,name=knowledge_domain,json=knowledgeDomain,proto3" json:"knowledge_domain,omitempty"`
	Founder             string                 `protobuf:"bytes,9,opt,name=founder,proto3" json:"founder,omitempty"`
	Contributors        []*ContributorRecord   `protobuf:"bytes,10,rep,name=contributors,proto3" json:"contributors,omitempty"`
	Budget              string                 `protobuf:"bytes,11,opt,name=budget,proto3" json:"budget,omitempty"`
	Spent               string                 `protobuf:"bytes,12,opt,name=spent,proto3" json:"spent,omitempty"`
	TaskIds             []string               `protobuf:"bytes,13,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	ServiceIds          []string               `protobuf:"bytes,14,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	TotalTasks          uint32                 `protobuf:"varint,15,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks      uint32                 `protobuf:"varint,16,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	RevenueGenerated    string                 `protobuf:"bytes,17,opt,name=revenue_generated,json=revenueGenerated,proto3" json:"revenue_generated,omitempty"`
	ParentProjectId     string                 `protobuf:"bytes,18,opt,name=parent_project_id,json=parentProjectId,proto3" json:"parent_project_id,omitempty"`
	PauseReason         string                 `protobuf:"bytes,19,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	Applications        []*ProjectApplication  `protobuf:"bytes,20,rep,name=applications,proto3" json:"applications,omitempty"`
	FundingSources      []*FundingSource       `protobuf:"bytes,21,rep,name=funding_sources,json=fundingSources,proto3" json:"funding_sources,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductProject) Reset() {
	*x = ProductProject{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductProject) ProtoMessage() {}

func (x *ProductProject) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductProject.ProtoReflect.Descriptor instead.
func (*ProductProject) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProductProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductProject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductProject) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProductProject) GetPreviousPhase() string {
	if x != nil {
		return x.PreviousPhase
	}
	return ""
}

func (x *ProductProject) GetCreatedAtBlock() uint64 {
	if x != nil {
		return x.CreatedAtBlock
	}
	return 0
}

func (x *ProductProject) GetPhaseChangedAtBlock() uint64 {
	if x != nil {
		return x.PhaseChangedAtBlock
	}
	return 0
}

func (x *ProductProject) GetKnowledgeDomain() string {
	if x != nil {
		return x.KnowledgeDomain
	}
	return ""
}

func (x *ProductProject) GetFounder() string {
	if x != nil {
		return x.Founder
	}
	return ""
}

func (x *ProductProject) GetContributors() []*ContributorRecord {
	if x != nil {
		return x.Contributors
	}
	return nil
}

func (x *ProductProject) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

func (x *ProductProject) GetSpent() string {
	if x != nil {
		return x.Spent
	}
	return ""
}

func (x *ProductProject) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *ProductProject) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *ProductProject) GetTotalTasks() uint32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *ProductProject) GetCompletedTasks() uint32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *ProductProject) GetRevenueGenerated() string {
	if x != nil {
		return x.RevenueGenerated
	}
	return ""
}

func (x *ProductProject) GetParentProjectId() string {
	if x != nil {
		return x.ParentProjectId
	}
	return ""
}

func (x *ProductProject) GetPauseReason() string {
	if x != nil {
		return x.PauseReason
	}
	return ""
}

func (x *ProductProject) GetApplications() []*ProjectApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ProductProject) GetFundingSources() []*FundingSource {
	if x != nil {
		return x.FundingSources
	}
	return nil
}

type ProjectTask struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TaskType             string                 `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Assignee             string                 `protobuf:"bytes,6,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	BountyAmount         string                 `protobuf:"bytes,8,opt,name=bounty_amount,json=bountyAmount,proto3" json:"bounty_amount,omitempty"`
	CreatedAtBlock       uint64                 `protobuf:"varint,9,opt,name=created_at_block,json=createdAtBlock,proto3" json:"created_at_block,omitempty"`
	CompletedAtBlock     uint64                 `protobuf:"varint,10,opt,name=completed_at_block,json=completedAtBlock,proto3" json:"completed_at_block,omitempty"`
	Deliverable          *TaskDeliverable       `protobuf:"bytes,11,opt,name=deliverable,proto3" json:"deliverable,omitempty"`
	RejectionCount       uint32                 `protobuf:"varint,12,opt,name=rejection_count,json=rejectionCount,proto3" json:"rejection_count,omitempty"`
	Reviewers            []string               `protobuf:"bytes,13,rep,name=reviewers,proto3" json:"reviewers,omitempty"`
	RequiredCapabilities []string               `protobuf:"bytes,14,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProjectTask) Reset() {
	*x = ProjectTask{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectTask) ProtoMessage() {}

func (x *ProjectTask) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectTask.ProtoReflect.Descriptor instead.
func (*ProjectTask) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectTask) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectTask) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ProjectTask) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *ProjectTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectTask) GetBountyAmount() string {
	if x != nil {
		return x.BountyAmount
	}
	return ""
}

func (x *ProjectTask) GetCreatedAtBlock() uint64 {
	if x != nil {
		return x.CreatedAtBlock
	}
	return 0
}

func (x *ProjectTask) GetCompletedAtBlock() uint64 {
	if x != nil {
		return x.CompletedAtBlock
	}
	return 0
}

func (x *ProjectTask) GetDeliverable() *TaskDeliverable {
	if x != nil {
		return x.Deliverable
	}
	return nil
}

func (x *ProjectTask) GetRejectionCount() uint32 {
	if x != nil {
		return x.RejectionCount
	}
	return 0
}

func (x *ProjectTask) GetReviewers() []string {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

func (x *ProjectTask) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

type ServiceLeaf struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId         string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ServiceType       string                 `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ContractAddress   string                 `protobuf:"bytes,6,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TotalCalls        string                 `protobuf:"bytes,7,opt,name=total_calls,json=totalCalls,proto3" json:"total_calls,omitempty"`
	TotalRevenue      string                 `protobuf:"bytes,8,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	UptimeBlocks      string                 `protobuf:"bytes,9,opt,name=uptime_blocks,json=uptimeBlocks,proto3" json:"uptime_blocks,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DeployedAtBlock   uint64                 `protobuf:"varint,11,opt,name=deployed_at_block,json=deployedAtBlock,proto3" json:"deployed_at_block,omitempty"`
	LastCalledBlock   uint64                 `protobuf:"varint,12,opt,name=last_called_block,json=lastCalledBlock,proto3" json:"last_called_block,omitempty"`
	PricePerCall      string                 `protobuf:"bytes,13,opt,name=price_per_call,json=pricePerCall,proto3" json:"price_per_call,omitempty"`
	SubscriptionPrice string                 `protobuf:"bytes,14,opt,name=subscription_price,json=subscriptionPrice,proto3" json:"subscription_price,omitempty"`
	Capabilities      []string               `protobuf:"bytes,15,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceLeaf) Reset() {
	*x = ServiceLeaf{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLeaf) ProtoMessage() {}

func (x *ServiceLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLeaf.ProtoReflect.Descriptor instead.
func (*ServiceLeaf) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceLeaf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceLeaf) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ServiceLeaf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceLeaf) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceLeaf) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceLeaf) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ServiceLeaf) GetTotalCalls() string {
	if x != nil {
		return x.TotalCalls
	}
	return ""
}

func (x *ServiceLeaf) GetTotalRevenue() string {
	if x != nil {
		return x.TotalRevenue
	}
	return ""
}

func (x *ServiceLeaf) GetUptimeBlocks() string {
	if x != nil {
		return x.UptimeBlocks
	}
	return ""
}

func (x *ServiceLeaf) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceLeaf) GetDeployedAtBlock() uint64 {
	if x != nil {
		return x.DeployedAtBlock
	}
	return 0
}

func (x *ServiceLeaf) GetLastCalledBlock() uint64 {
	if x != nil {
		return x.LastCalledBlock
	}
	return 0
}

func (x *ServiceLeaf) GetPricePerCall() string {
	if x != nil {
		return x.PricePerCall
	}
	return ""
}

func (x *ServiceLeaf) GetSubscriptionPrice() string {
	if x != nil {
		return x.SubscriptionPrice
	}
	return ""
}

func (x *ServiceLeaf) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type OpportunitySeed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectedAtBlock uint64                 `protobuf:"varint,2,opt,name=detected_at_block,json=detectedAtBlock,proto3" json:"detected_at_block,omitempty"`
	KnowledgeDomain string                 `protobuf:"bytes,3,opt,name=knowledge_domain,json=knowledgeDomain,proto3" json:"knowledge_domain,omitempty"`
	Confidence      string                 `protobuf:"bytes,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAtBlock  uint64                 `protobuf:"varint,6,opt,name=expires_at_block,json=expiresAtBlock,proto3" json:"expires_at_block,omitempty"`
	ProjectId       string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClaimedBy       string                 `protobuf:"bytes,8,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"`
	Signal          *DemandSignal          `protobuf:"bytes,9,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpportunitySeed) Reset() {
	*x = OpportunitySeed{}
	mi := &file_zerone_tree_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpportunitySeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpportunitySeed) ProtoMessage() {}

func (x *OpportunitySeed) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_tree_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpportunitySeed.ProtoReflect.Descriptor instead.
func (*OpportunitySeed) Descriptor() ([]byte, []int) {
	return file_zerone_tree_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *OpportunitySeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpportunitySeed) GetDetectedAtBlock() uint64 {
	if x != nil {
		return x.DetectedAtBlock
	}
	return 0
}

func (x *OpportunitySeed) GetKnowledgeDomain() string {
	if x != nil {
		return x.KnowledgeDomain
	}
	return ""
}

func (x *OpportunitySeed) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *OpportunitySeed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpportunitySeed) GetExpiresAtBlock() uint64 {
	if x != nil {
		return x.ExpiresAtBlock
	}
	return 0
}

func (x *OpportunitySeed) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *OpportunitySeed) GetClaimedBy() string {
	if x != nil {
		return x.ClaimedBy
	}
	return ""
}

func (x *OpportunitySeed) GetSignal() *DemandSignal {
	if x != nil {
		return x.Signal
	}
	return nil
}

var File_zerone_tree_v1_types_proto protoreflect.FileDescriptor

const file_zerone_tree_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1azerone/tree/v1/types.proto\x12\x0ezerone.tree.v1\"\xad\x01\n" +
	"\x11ContributorRecord\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12&\n" +
	"\x0fjoined_at_block\x18\x03 \x01(\x04R\rjoinedAtBlock\x12'\n" +
	"\x0ftasks_completed\x18\x04 \x01(\rR\x0etasksCompleted\x12!\n" +
	"\ftotal_earned\x18\x05 \x01(\tR\vtotalEarned\"\x9b\x01\n" +
	"\vProductSpec\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\x12\"\n" +
	"\frequirements\x18\x02 \x03(\tR\frequirements\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12!\n" +
	"\fmvp_criteria\x18\x04 \x01(\tR\vmvpCriteria\"Q\n" +
	"\rFundingSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x14\n" +
	"\x05terms\x18\x03 \x01(\tR\x05terms\"\xc3\x01\n" +
	"\fDemandSignal\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12F\n" +
	"\bevidence\x18\x02 \x03(\v2*.zerone.tree.v1.DemandSignal.EvidenceEntryR\bevidence\x12\x1a\n" +
	"\bstrength\x18\x03 \x01(\tR\bstrength\x1a;\n" +
	"\rEvidenceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x12ProjectApplication\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12#\n" +
	"\rproposed_role\x18\x02 \x01(\tR\fproposedRole\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12(\n" +
	"\x10applied_at_block\x18\x05 \x01(\x04R\x0eappliedAtBlock\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x86\x01\n" +
	"\x0fTaskDeliverable\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12,\n" +
	"\x12submitted_at_block\x18\x03 \x01(\x04R\x10submittedAtBlock\x12\x1f\n" +
	"\vverified_by\x18\x04 \x03(\tR\n" +
	"verifiedBy\"\xbe\x06\n" +
	"\x0eProductProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12%\n" +
	"\x0eprevious_phase\x18\x05 \x01(\tR\rpreviousPhase\x12(\n" +
	"\x10created_at_block\x18\x06 \x01(\x04R\x0ecreatedAtBlock\x123\n" +
	"\x16phase_changed_at_block\x18\a \x01(\x04R\x13phaseChangedAtBlock\x12)\n" +
	"\x10knowledge_domain\x18\b \x01(\tR\x0fknowledgeDomain\x12\x18\n" +
	"\afounder\x18\t \x01(\tR\afounder\x12E\n" +
	"\fcontributors\x18\n" +
	" \x03(\v2!.zerone.tree.v1.ContributorRecordR\fcontributors\x12\x16\n" +
	"\x06budget\x18\v \x01(\tR\x06budget\x12\x14\n" +
	"\x05spent\x18\f \x01(\tR\x05spent\x12\x19\n" +
	"\btask_ids\x18\r \x03(\tR\ataskIds\x12\x1f\n" +
	"\vservice_ids\x18\x0e \x03(\tR\n" +
	"serviceIds\x12\x1f\n" +
	"\vtotal_tasks\x18\x0f \x01(\rR\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x10 \x01(\rR\x0ecompletedTasks\x12+\n" +
	"\x11revenue_generated\x18\x11 \x01(\tR\x10revenueGenerated\x12*\n" +
	"\x11parent_project_id\x18\x12 \x01(\tR\x0fparentProjectId\x12!\n" +
	"\fpause_reason\x18\x13 \x01(\tR\vpauseReason\x12F\n" +
	"\fapplications\x18\x14 \x03(\v2\".zerone.tree.v1.ProjectApplicationR\fapplications\x12F\n" +
	"\x0ffunding_sources\x18\x15 \x03(\v2\x1d.zerone.tree.v1.FundingSourceR\x0efundingSources\"\x81\x04\n" +
	"\vProjectTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttask_type\x18\x05 \x01(\tR\btaskType\x12\x1a\n" +
	"\bassignee\x18\x06 \x01(\tR\bassignee\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rbounty_amount\x18\b \x01(\tR\fbountyAmount\x12(\n" +
	"\x10created_at_block\x18\t \x01(\x04R\x0ecreatedAtBlock\x12,\n" +
	"\x12completed_at_block\x18\n" +
	" \x01(\x04R\x10completedAtBlock\x12A\n" +
	"\vdeliverable\x18\v \x01(\v2\x1f.zerone.tree.v1.TaskDeliverableR\vdeliverable\x12'\n" +
	"\x0frejection_count\x18\f \x01(\rR\x0erejectionCount\x12\x1c\n" +
	"\treviewers\x18\r \x03(\tR\treviewers\x123\n" +
	"\x15required_capabilities\x18\x0e \x03(\tR\x14requiredCapabilities\"\x94\x04\n" +
	"\vServiceLeaf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fservice_type\x18\x05 \x01(\tR\vserviceType\x12)\n" +
	"\x10contract_address\x18\x06 \x01(\tR\x0fcontractAddress\x12\x1f\n" +
	"\vtotal_calls\x18\a \x01(\tR\n" +
	"totalCalls\x12#\n" +
	"\rtotal_revenue\x18\b \x01(\tR\ftotalRevenue\x12#\n" +
	"\ruptime_blocks\x18\t \x01(\tR\fuptimeBlocks\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12*\n" +
	"\x11deployed_at_block\x18\v \x01(\x04R\x0fdeployedAtBlock\x12*\n" +
	"\x11last_called_block\x18\f \x01(\x04R\x0flastCalledBlock\x12$\n" +
	"\x0eprice_per_call\x18\r \x01(\tR\fpricePerCall\x12-\n" +
	"\x12subscription_price\x18\x0e \x01(\tR\x11subscriptionPrice\x12\"\n" +
	"\fcapabilities\x18\x0f \x03(\tR\fcapabilities\"\xce\x02\n" +
	"\x0fOpportunitySeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11detected_at_block\x18\x02 \x01(\x04R\x0fdetectedAtBlock\x12)\n" +
	"\x10knowledge_domain\x18\x03 \x01(\tR\x0fknowledgeDomain\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\tR\n" +
	"confidence\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12(\n" +
	"\x10expires_at_block\x18\x06 \x01(\x04R\x0eexpiresAtBlock\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"claimed_by\x18\b \x01(\tR\tclaimedBy\x124\n" +
	"\x06signal\x18\t \x01(\v2\x1c.zerone.tree.v1.DemandSignalR\x06signalB-Z+github.com/zerone-chain/zerone/x/tree/typesb\x06proto3"

var (
	file_zerone_tree_v1_types_proto_rawDescOnce sync.Once
	file_zerone_tree_v1_types_proto_rawDescData []byte
)

func file_zerone_tree_v1_types_proto_rawDescGZIP() []byte {
	file_zerone_tree_v1_types_proto_rawDescOnce.Do(func() {
		file_zerone_tree_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_tree_v1_types_proto_rawDesc), len(file_zerone_tree_v1_types_proto_rawDesc)))
	})
	return file_zerone_tree_v1_types_proto_rawDescData
}

var file_zerone_tree_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_zerone_tree_v1_types_proto_goTypes = []any{
	(*ContributorRecord)(nil),  // 0: zerone.tree.v1.ContributorRecord
	(*ProductSpec)(nil),        // 1: zerone.tree.v1.ProductSpec
	(*FundingSource)(nil),      // 2: zerone.tree.v1.FundingSource
	(*DemandSignal)(nil),       // 3: zerone.tree.v1.DemandSignal
	(*ProjectApplication)(nil), // 4: zerone.tree.v1.ProjectApplication
	(*TaskDeliverable)(nil),    // 5: zerone.tree.v1.TaskDeliverable
	(*ProductProject)(nil),     // 6: zerone.tree.v1.ProductProject
	(*ProjectTask)(nil),        // 7: zerone.tree.v1.ProjectTask
	(*ServiceLeaf)(nil),        // 8: zerone.tree.v1.ServiceLeaf
	(*OpportunitySeed)(nil),    // 9: zerone.tree.v1.OpportunitySeed
	nil,                        // 10: zerone.tree.v1.DemandSignal.EvidenceEntry
}
var file_zerone_tree_v1_types_proto_depIdxs = []int32{
	10, // 0: zerone.tree.v1.DemandSignal.evidence:type_name -> zerone.tree.v1.DemandSignal.EvidenceEntry
	0,  // 1: zerone.tree.v1.ProductProject.contributors:type_name -> zerone.tree.v1.ContributorRecord
	4,  // 2: zerone.tree.v1.ProductProject.applications:type_name -> zerone.tree.v1.ProjectApplication
	2,  // 3: zerone.tree.v1.ProductProject.funding_sources:type_name -> zerone.tree.v1.FundingSource
	5,  // 4: zerone.tree.v1.ProjectTask.deliverable:type_name -> zerone.tree.v1.TaskDeliverable
	3,  // 5: zerone.tree.v1.OpportunitySeed.signal:type_name -> zerone.tree.v1.DemandSignal
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_zerone_tree_v1_types_proto_init() }
func file_zerone_tree_v1_types_proto_init() {
	if File_zerone_tree_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_tree_v1_types_proto_rawDesc), len(file_zerone_tree_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_tree_v1_types_proto_goTypes,
		DependencyIndexes: file_zerone_tree_v1_types_proto_depIdxs,
		MessageInfos:      file_zerone_tree_v1_types_proto_msgTypes,
	}.Build()
	File_zerone_tree_v1_types_proto = out.File
	file_zerone_tree_v1_types_proto_goTypes = nil
	file_zerone_tree_v1_types_proto_depIdxs = nil
}
