// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/home/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgCreateHome struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Owner                 string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InitialGuardianConfig *HomeGuardian          `protobuf:"bytes,3,opt,name=initial_guardian_config,json=initialGuardianConfig,proto3" json:"initial_guardian_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MsgCreateHome) Reset() {
	*x = MsgCreateHome{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateHome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateHome) ProtoMessage() {}

func (x *MsgCreateHome) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateHome.ProtoReflect.Descriptor instead.
func (*MsgCreateHome) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateHome) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgCreateHome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgCreateHome) GetInitialGuardianConfig() *HomeGuardian {
	if x != nil {
		return x.InitialGuardianConfig
	}
	return nil
}

type MsgCreateHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        string                 `protobuf:"bytes,1,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateHomeResponse) Reset() {
	*x = MsgCreateHomeResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateHomeResponse) ProtoMessage() {}

func (x *MsgCreateHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateHomeResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateHomeResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateHomeResponse) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

type MsgUpdateHome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateHome) Reset() {
	*x = MsgUpdateHome{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateHome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateHome) ProtoMessage() {}

func (x *MsgUpdateHome) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateHome.ProtoReflect.Descriptor instead.
func (*MsgUpdateHome) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateHome) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgUpdateHome) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgUpdateHome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgUpdateHome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MsgUpdateHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateHomeResponse) Reset() {
	*x = MsgUpdateHomeResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateHomeResponse) ProtoMessage() {}

func (x *MsgUpdateHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateHomeResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateHomeResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgUpdateMemoryCID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMemoryCID) Reset() {
	*x = MsgUpdateMemoryCID{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMemoryCID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMemoryCID) ProtoMessage() {}

func (x *MsgUpdateMemoryCID) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMemoryCID.ProtoReflect.Descriptor instead.
func (*MsgUpdateMemoryCID) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUpdateMemoryCID) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgUpdateMemoryCID) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgUpdateMemoryCID) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type MsgUpdateMemoryCIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMemoryCIDResponse) Reset() {
	*x = MsgUpdateMemoryCIDResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMemoryCIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMemoryCIDResponse) ProtoMessage() {}

func (x *MsgUpdateMemoryCIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMemoryCIDResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateMemoryCIDResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgStartSession struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Signer               string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	HomeId               string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	KeyHash              string                 `protobuf:"bytes,3,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	RequestedPermissions []string               `protobuf:"bytes,4,rep,name=requested_permissions,json=requestedPermissions,proto3" json:"requested_permissions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MsgStartSession) Reset() {
	*x = MsgStartSession{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgStartSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStartSession) ProtoMessage() {}

func (x *MsgStartSession) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStartSession.ProtoReflect.Descriptor instead.
func (*MsgStartSession) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgStartSession) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgStartSession) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgStartSession) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *MsgStartSession) GetRequestedPermissions() []string {
	if x != nil {
		return x.RequestedPermissions
	}
	return nil
}

type MsgStartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgStartSessionResponse) Reset() {
	*x = MsgStartSessionResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgStartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStartSessionResponse) ProtoMessage() {}

func (x *MsgStartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStartSessionResponse.ProtoReflect.Descriptor instead.
func (*MsgStartSessionResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgStartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MsgEndSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndSession) Reset() {
	*x = MsgEndSession{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndSession) ProtoMessage() {}

func (x *MsgEndSession) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndSession.ProtoReflect.Descriptor instead.
func (*MsgEndSession) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgEndSession) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgEndSession) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgEndSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MsgEndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgEndSessionResponse) Reset() {
	*x = MsgEndSessionResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgEndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEndSessionResponse) ProtoMessage() {}

func (x *MsgEndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEndSessionResponse.ProtoReflect.Descriptor instead.
func (*MsgEndSessionResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{9}
}

type MsgRegisterKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	KeyHash       string                 `protobuf:"bytes,3,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	KeyType       string                 `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterKey) Reset() {
	*x = MsgRegisterKey{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterKey) ProtoMessage() {}

func (x *MsgRegisterKey) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterKey.ProtoReflect.Descriptor instead.
func (*MsgRegisterKey) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRegisterKey) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgRegisterKey) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgRegisterKey) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *MsgRegisterKey) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *MsgRegisterKey) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MsgRegisterKey) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MsgRegisterKey) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type MsgRegisterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterKeyResponse) Reset() {
	*x = MsgRegisterKeyResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterKeyResponse) ProtoMessage() {}

func (x *MsgRegisterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterKeyResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{11}
}

type MsgRevokeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	KeyHash       string                 `protobuf:"bytes,3,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeKey) Reset() {
	*x = MsgRevokeKey{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeKey) ProtoMessage() {}

func (x *MsgRevokeKey) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeKey.ProtoReflect.Descriptor instead.
func (*MsgRevokeKey) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MsgRevokeKey) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgRevokeKey) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgRevokeKey) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

type MsgRevokeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeKeyResponse) Reset() {
	*x = MsgRevokeKeyResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeKeyResponse) ProtoMessage() {}

func (x *MsgRevokeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRevokeKeyResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{13}
}

type MsgConfigureGuardian struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Owner             string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId            string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	DefenseStrategy   string                 `protobuf:"bytes,3,opt,name=defense_strategy,json=defenseStrategy,proto3" json:"defense_strategy,omitempty"`
	AutoDefend        bool                   `protobuf:"varint,4,opt,name=auto_defend,json=autoDefend,proto3" json:"auto_defend,omitempty"`
	Deadman           *DeadmanConfig         `protobuf:"bytes,5,opt,name=deadman,proto3" json:"deadman,omitempty"`
	RecoveryAddresses []string               `protobuf:"bytes,6,rep,name=recovery_addresses,json=recoveryAddresses,proto3" json:"recovery_addresses,omitempty"`
	RecoveryThreshold uint32                 `protobuf:"varint,7,opt,name=recovery_threshold,json=recoveryThreshold,proto3" json:"recovery_threshold,omitempty"`
	GuardianAddress   string                 `protobuf:"bytes,8,opt,name=guardian_address,json=guardianAddress,proto3" json:"guardian_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgConfigureGuardian) Reset() {
	*x = MsgConfigureGuardian{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgConfigureGuardian) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgConfigureGuardian) ProtoMessage() {}

func (x *MsgConfigureGuardian) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgConfigureGuardian.ProtoReflect.Descriptor instead.
func (*MsgConfigureGuardian) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{14}
}

func (x *MsgConfigureGuardian) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgConfigureGuardian) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgConfigureGuardian) GetDefenseStrategy() string {
	if x != nil {
		return x.DefenseStrategy
	}
	return ""
}

func (x *MsgConfigureGuardian) GetAutoDefend() bool {
	if x != nil {
		return x.AutoDefend
	}
	return false
}

func (x *MsgConfigureGuardian) GetDeadman() *DeadmanConfig {
	if x != nil {
		return x.Deadman
	}
	return nil
}

func (x *MsgConfigureGuardian) GetRecoveryAddresses() []string {
	if x != nil {
		return x.RecoveryAddresses
	}
	return nil
}

func (x *MsgConfigureGuardian) GetRecoveryThreshold() uint32 {
	if x != nil {
		return x.RecoveryThreshold
	}
	return 0
}

func (x *MsgConfigureGuardian) GetGuardianAddress() string {
	if x != nil {
		return x.GuardianAddress
	}
	return ""
}

type MsgConfigureGuardianResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgConfigureGuardianResponse) Reset() {
	*x = MsgConfigureGuardianResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgConfigureGuardianResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgConfigureGuardianResponse) ProtoMessage() {}

func (x *MsgConfigureGuardianResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgConfigureGuardianResponse.ProtoReflect.Descriptor instead.
func (*MsgConfigureGuardianResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{15}
}

type MsgAcknowledgeAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	AlertId       string                 `protobuf:"bytes,3,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAcknowledgeAlert) Reset() {
	*x = MsgAcknowledgeAlert{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAcknowledgeAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcknowledgeAlert) ProtoMessage() {}

func (x *MsgAcknowledgeAlert) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcknowledgeAlert.ProtoReflect.Descriptor instead.
func (*MsgAcknowledgeAlert) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{16}
}

func (x *MsgAcknowledgeAlert) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgAcknowledgeAlert) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgAcknowledgeAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type MsgAcknowledgeAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAcknowledgeAlertResponse) Reset() {
	*x = MsgAcknowledgeAlertResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAcknowledgeAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcknowledgeAlertResponse) ProtoMessage() {}

func (x *MsgAcknowledgeAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcknowledgeAlertResponse.ProtoReflect.Descriptor instead.
func (*MsgAcknowledgeAlertResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{17}
}

type MsgSetSpendingLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HomeId        string                 `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	PeriodBlocks  uint64                 `protobuf:"varint,5,opt,name=period_blocks,json=periodBlocks,proto3" json:"period_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetSpendingLimit) Reset() {
	*x = MsgSetSpendingLimit{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetSpendingLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetSpendingLimit) ProtoMessage() {}

func (x *MsgSetSpendingLimit) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetSpendingLimit.ProtoReflect.Descriptor instead.
func (*MsgSetSpendingLimit) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{18}
}

func (x *MsgSetSpendingLimit) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgSetSpendingLimit) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MsgSetSpendingLimit) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *MsgSetSpendingLimit) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *MsgSetSpendingLimit) GetPeriodBlocks() uint64 {
	if x != nil {
		return x.PeriodBlocks
	}
	return 0
}

type MsgSetSpendingLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetSpendingLimitResponse) Reset() {
	*x = MsgSetSpendingLimitResponse{}
	mi := &file_zerone_home_v1_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetSpendingLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetSpendingLimitResponse) ProtoMessage() {}

func (x *MsgSetSpendingLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_home_v1_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetSpendingLimitResponse.ProtoReflect.Descriptor instead.
func (*MsgSetSpendingLimitResponse) Descriptor() ([]byte, []int) {
	return file_zerone_home_v1_tx_proto_rawDescGZIP(), []int{19}
}

var File_zerone_home_v1_tx_proto protoreflect.FileDescriptor

const file_zerone_home_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x17zerone/home/v1/tx.proto\x12\x0ezerone.home.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x1azerone/home/v1/types.proto\"\x9b\x01\n" +
	"\rMsgCreateHome\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12T\n" +
	"\x17initial_guardian_config\x18\x03 \x01(\v2\x1c.zerone.home.v1.HomeGuardianR\x15initialGuardianConfig:\n" +
	"\x82\xe7\xb0*\x05owner\"0\n" +
	"\x15MsgCreateHomeResponse\x12\x17\n" +
	"\ahome_id\x18\x01 \x01(\tR\x06homeId\"v\n" +
	"\rMsgUpdateHome\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status:\n" +
	"\x82\xe7\xb0*\x05owner\"\x17\n" +
	"\x15MsgUpdateHomeResponse\"a\n" +
	"\x12MsgUpdateMemoryCID\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid:\n" +
	"\x82\xe7\xb0*\x05owner\"\x1c\n" +
	"\x1aMsgUpdateMemoryCIDResponse\"\x9f\x01\n" +
	"\x0fMsgStartSession\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x19\n" +
	"\bkey_hash\x18\x03 \x01(\tR\akeyHash\x123\n" +
	"\x15requested_permissions\x18\x04 \x03(\tR\x14requestedPermissions:\v\x82\xe7\xb0*\x06signer\"8\n" +
	"\x17MsgStartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"l\n" +
	"\rMsgEndSession\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId:\v\x82\xe7\xb0*\x06signer\"\x17\n" +
	"\x15MsgEndSessionResponse\"\xd6\x01\n" +
	"\x0eMsgRegisterKey\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x19\n" +
	"\bkey_hash\x18\x03 \x01(\tR\akeyHash\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x04R\texpiresAt:\n" +
	"\x82\xe7\xb0*\x05owner\"\x18\n" +
	"\x16MsgRegisterKeyResponse\"d\n" +
	"\fMsgRevokeKey\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x19\n" +
	"\bkey_hash\x18\x03 \x01(\tR\akeyHash:\n" +
	"\x82\xe7\xb0*\x05owner\"\x16\n" +
	"\x14MsgRevokeKeyResponse\"\xdf\x02\n" +
	"\x14MsgConfigureGuardian\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12)\n" +
	"\x10defense_strategy\x18\x03 \x01(\tR\x0fdefenseStrategy\x12\x1f\n" +
	"\vauto_defend\x18\x04 \x01(\bR\n" +
	"autoDefend\x127\n" +
	"\adeadman\x18\x05 \x01(\v2\x1d.zerone.home.v1.DeadmanConfigR\adeadman\x12-\n" +
	"\x12recovery_addresses\x18\x06 \x03(\tR\x11recoveryAddresses\x12-\n" +
	"\x12recovery_threshold\x18\a \x01(\rR\x11recoveryThreshold\x12)\n" +
	"\x10guardian_address\x18\b \x01(\tR\x0fguardianAddress:\n" +
	"\x82\xe7\xb0*\x05owner\"\x1e\n" +
	"\x1cMsgConfigureGuardianResponse\"n\n" +
	"\x13MsgAcknowledgeAlert\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x19\n" +
	"\balert_id\x18\x03 \x01(\tR\aalertId:\v\x82\xe7\xb0*\x06signer\"\x1d\n" +
	"\x1bMsgAcknowledgeAlertResponse\"\xaf\x01\n" +
	"\x13MsgSetSpendingLimit\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\ahome_id\x18\x02 \x01(\tR\x06homeId\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\tR\tmaxAmount\x12#\n" +
	"\rperiod_blocks\x18\x05 \x01(\x04R\fperiodBlocks:\n" +
	"\x82\xe7\xb0*\x05owner\"\x1d\n" +
	"\x1bMsgSetSpendingLimitResponse2\xa2\a\n" +
	"\x03Msg\x12R\n" +
	"\n" +
	"CreateHome\x12\x1d.zerone.home.v1.MsgCreateHome\x1a%.zerone.home.v1.MsgCreateHomeResponse\x12R\n" +
	"\n" +
	"UpdateHome\x12\x1d.zerone.home.v1.MsgUpdateHome\x1a%.zerone.home.v1.MsgUpdateHomeResponse\x12a\n" +
	"\x0fUpdateMemoryCID\x12\".zerone.home.v1.MsgUpdateMemoryCID\x1a*.zerone.home.v1.MsgUpdateMemoryCIDResponse\x12X\n" +
	"\fStartSession\x12\x1f.zerone.home.v1.MsgStartSession\x1a'.zerone.home.v1.MsgStartSessionResponse\x12R\n" +
	"\n" +
	"EndSession\x12\x1d.zerone.home.v1.MsgEndSession\x1a%.zerone.home.v1.MsgEndSessionResponse\x12U\n" +
	"\vRegisterKey\x12\x1e.zerone.home.v1.MsgRegisterKey\x1a&.zerone.home.v1.MsgRegisterKeyResponse\x12O\n" +
	"\tRevokeKey\x12\x1c.zerone.home.v1.MsgRevokeKey\x1a$.zerone.home.v1.MsgRevokeKeyResponse\x12g\n" +
	"\x11ConfigureGuardian\x12$.zerone.home.v1.MsgConfigureGuardian\x1a,.zerone.home.v1.MsgConfigureGuardianResponse\x12d\n" +
	"\x10AcknowledgeAlert\x12#.zerone.home.v1.MsgAcknowledgeAlert\x1a+.zerone.home.v1.MsgAcknowledgeAlertResponse\x12d\n" +
	"\x10SetSpendingLimit\x12#.zerone.home.v1.MsgSetSpendingLimit\x1a+.zerone.home.v1.MsgSetSpendingLimitResponse\x1a\x05\x80\xe7\xb0*\x01B-Z+github.com/zerone-chain/zerone/x/home/typesb\x06proto3"

var (
	file_zerone_home_v1_tx_proto_rawDescOnce sync.Once
	file_zerone_home_v1_tx_proto_rawDescData []byte
)

func file_zerone_home_v1_tx_proto_rawDescGZIP() []byte {
	file_zerone_home_v1_tx_proto_rawDescOnce.Do(func() {
		file_zerone_home_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_home_v1_tx_proto_rawDesc), len(file_zerone_home_v1_tx_proto_rawDesc)))
	})
	return file_zerone_home_v1_tx_proto_rawDescData
}

var file_zerone_home_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_zerone_home_v1_tx_proto_goTypes = []any{
	(*MsgCreateHome)(nil),                // 0: zerone.home.v1.MsgCreateHome
	(*MsgCreateHomeResponse)(nil),        // 1: zerone.home.v1.MsgCreateHomeResponse
	(*MsgUpdateHome)(nil),                // 2: zerone.home.v1.MsgUpdateHome
	(*MsgUpdateHomeResponse)(nil),        // 3: zerone.home.v1.MsgUpdateHomeResponse
	(*MsgUpdateMemoryCID)(nil),           // 4: zerone.home.v1.MsgUpdateMemoryCID
	(*MsgUpdateMemoryCIDResponse)(nil),   // 5: zerone.home.v1.MsgUpdateMemoryCIDResponse
	(*MsgStartSession)(nil),              // 6: zerone.home.v1.MsgStartSession
	(*MsgStartSessionResponse)(nil),      // 7: zerone.home.v1.MsgStartSessionResponse
	(*MsgEndSession)(nil),                // 8: zerone.home.v1.MsgEndSession
	(*MsgEndSessionResponse)(nil),        // 9: zerone.home.v1.MsgEndSessionResponse
	(*MsgRegisterKey)(nil),               // 10: zerone.home.v1.MsgRegisterKey
	(*MsgRegisterKeyResponse)(nil),       // 11: zerone.home.v1.MsgRegisterKeyResponse
	(*MsgRevokeKey)(nil),                 // 12: zerone.home.v1.MsgRevokeKey
	(*MsgRevokeKeyResponse)(nil),         // 13: zerone.home.v1.MsgRevokeKeyResponse
	(*MsgConfigureGuardian)(nil),         // 14: zerone.home.v1.MsgConfigureGuardian
	(*MsgConfigureGuardianResponse)(nil), // 15: zerone.home.v1.MsgConfigureGuardianResponse
	(*MsgAcknowledgeAlert)(nil),          // 16: zerone.home.v1.MsgAcknowledgeAlert
	(*MsgAcknowledgeAlertResponse)(nil),  // 17: zerone.home.v1.MsgAcknowledgeAlertResponse
	(*MsgSetSpendingLimit)(nil),          // 18: zerone.home.v1.MsgSetSpendingLimit
	(*MsgSetSpendingLimitResponse)(nil),  // 19: zerone.home.v1.MsgSetSpendingLimitResponse
	(*HomeGuardian)(nil),                 // 20: zerone.home.v1.HomeGuardian
	(*DeadmanConfig)(nil),                // 21: zerone.home.v1.DeadmanConfig
}
var file_zerone_home_v1_tx_proto_depIdxs = []int32{
	20, // 0: zerone.home.v1.MsgCreateHome.initial_guardian_config:type_name -> zerone.home.v1.HomeGuardian
	21, // 1: zerone.home.v1.MsgConfigureGuardian.deadman:type_name -> zerone.home.v1.DeadmanConfig
	0,  // 2: zerone.home.v1.Msg.CreateHome:input_type -> zerone.home.v1.MsgCreateHome
	2,  // 3: zerone.home.v1.Msg.UpdateHome:input_type -> zerone.home.v1.MsgUpdateHome
	4,  // 4: zerone.home.v1.Msg.UpdateMemoryCID:input_type -> zerone.home.v1.MsgUpdateMemoryCID
	6,  // 5: zerone.home.v1.Msg.StartSession:input_type -> zerone.home.v1.MsgStartSession
	8,  // 6: zerone.home.v1.Msg.EndSession:input_type -> zerone.home.v1.MsgEndSession
	10, // 7: zerone.home.v1.Msg.RegisterKey:input_type -> zerone.home.v1.MsgRegisterKey
	12, // 8: zerone.home.v1.Msg.RevokeKey:input_type -> zerone.home.v1.MsgRevokeKey
	14, // 9: zerone.home.v1.Msg.ConfigureGuardian:input_type -> zerone.home.v1.MsgConfigureGuardian
	16, // 10: zerone.home.v1.Msg.AcknowledgeAlert:input_type -> zerone.home.v1.MsgAcknowledgeAlert
	18, // 11: zerone.home.v1.Msg.SetSpendingLimit:input_type -> zerone.home.v1.MsgSetSpendingLimit
	1,  // 12: zerone.home.v1.Msg.CreateHome:output_type -> zerone.home.v1.MsgCreateHomeResponse
	3,  // 13: zerone.home.v1.Msg.UpdateHome:output_type -> zerone.home.v1.MsgUpdateHomeResponse
	5,  // 14: zerone.home.v1.Msg.UpdateMemoryCID:output_type -> zerone.home.v1.MsgUpdateMemoryCIDResponse
	7,  // 15: zerone.home.v1.Msg.StartSession:output_type -> zerone.home.v1.MsgStartSessionResponse
	9,  // 16: zerone.home.v1.Msg.EndSession:output_type -> zerone.home.v1.MsgEndSessionResponse
	11, // 17: zerone.home.v1.Msg.RegisterKey:output_type -> zerone.home.v1.MsgRegisterKeyResponse
	13, // 18: zerone.home.v1.Msg.RevokeKey:output_type -> zerone.home.v1.MsgRevokeKeyResponse
	15, // 19: zerone.home.v1.Msg.ConfigureGuardian:output_type -> zerone.home.v1.MsgConfigureGuardianResponse
	17, // 20: zerone.home.v1.Msg.AcknowledgeAlert:output_type -> zerone.home.v1.MsgAcknowledgeAlertResponse
	19, // 21: zerone.home.v1.Msg.SetSpendingLimit:output_type -> zerone.home.v1.MsgSetSpendingLimitResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_zerone_home_v1_tx_proto_init() }
func file_zerone_home_v1_tx_proto_init() {
	if File_zerone_home_v1_tx_proto != nil {
		return
	}
	file_zerone_home_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_home_v1_tx_proto_rawDesc), len(file_zerone_home_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_home_v1_tx_proto_goTypes,
		DependencyIndexes: file_zerone_home_v1_tx_proto_depIdxs,
		MessageInfos:      file_zerone_home_v1_tx_proto_msgTypes,
	}.Build()
	File_zerone_home_v1_tx_proto = out.File
	file_zerone_home_v1_tx_proto_goTypes = nil
	file_zerone_home_v1_tx_proto_depIdxs = nil
}
