// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/substrate_bridge/v1/adapter.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdapterStatus governs registration lifecycle. ACTIVE accepts new
// attestations; SUSPENDED refuses new but in-flight settle;
// TOMBSTONED is permanent retirement (commitment 10 forward-only).
type AdapterStatus int32

const (
	AdapterStatus_ADAPTER_STATUS_UNSPECIFIED AdapterStatus = 0
	AdapterStatus_ADAPTER_STATUS_ACTIVE      AdapterStatus = 1
	AdapterStatus_ADAPTER_STATUS_SUSPENDED   AdapterStatus = 2
	AdapterStatus_ADAPTER_STATUS_TOMBSTONED  AdapterStatus = 3
)

// Enum value maps for AdapterStatus.
var (
	AdapterStatus_name = map[int32]string{
		0: "ADAPTER_STATUS_UNSPECIFIED",
		1: "ADAPTER_STATUS_ACTIVE",
		2: "ADAPTER_STATUS_SUSPENDED",
		3: "ADAPTER_STATUS_TOMBSTONED",
	}
	AdapterStatus_value = map[string]int32{
		"ADAPTER_STATUS_UNSPECIFIED": 0,
		"ADAPTER_STATUS_ACTIVE":      1,
		"ADAPTER_STATUS_SUSPENDED":   2,
		"ADAPTER_STATUS_TOMBSTONED":  3,
	}
)

func (x AdapterStatus) Enum() *AdapterStatus {
	p := new(AdapterStatus)
	*p = x
	return p
}

func (x AdapterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdapterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zerone_substrate_bridge_v1_adapter_proto_enumTypes[0].Descriptor()
}

func (AdapterStatus) Type() protoreflect.EnumType {
	return &file_zerone_substrate_bridge_v1_adapter_proto_enumTypes[0]
}

func (x AdapterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdapterStatus.Descriptor instead.
func (AdapterStatus) EnumDescriptor() ([]byte, []int) {
	return file_zerone_substrate_bridge_v1_adapter_proto_rawDescGZIP(), []int{0}
}

// QualificationStatus mirrors x/qualification's status enum so an
// adapter can specify the minimum status a submitter must hold in the
// required domain. Imported here as a uint32 for proto isolation;
// keeper resolves to x/qualification's enum at query time.
type QualificationStatus int32

const (
	QualificationStatus_QUALIFICATION_STATUS_UNSPECIFIED   QualificationStatus = 0
	QualificationStatus_QUALIFICATION_STATUS_PROBATIONARY  QualificationStatus = 1
	QualificationStatus_QUALIFICATION_STATUS_ACTIVE        QualificationStatus = 2
	QualificationStatus_QUALIFICATION_STATUS_DISTINGUISHED QualificationStatus = 3
)

// Enum value maps for QualificationStatus.
var (
	QualificationStatus_name = map[int32]string{
		0: "QUALIFICATION_STATUS_UNSPECIFIED",
		1: "QUALIFICATION_STATUS_PROBATIONARY",
		2: "QUALIFICATION_STATUS_ACTIVE",
		3: "QUALIFICATION_STATUS_DISTINGUISHED",
	}
	QualificationStatus_value = map[string]int32{
		"QUALIFICATION_STATUS_UNSPECIFIED":   0,
		"QUALIFICATION_STATUS_PROBATIONARY":  1,
		"QUALIFICATION_STATUS_ACTIVE":        2,
		"QUALIFICATION_STATUS_DISTINGUISHED": 3,
	}
)

func (x QualificationStatus) Enum() *QualificationStatus {
	p := new(QualificationStatus)
	*p = x
	return p
}

func (x QualificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zerone_substrate_bridge_v1_adapter_proto_enumTypes[1].Descriptor()
}

func (QualificationStatus) Type() protoreflect.EnumType {
	return &file_zerone_substrate_bridge_v1_adapter_proto_enumTypes[1]
}

func (x QualificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualificationStatus.Descriptor instead.
func (QualificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_zerone_substrate_bridge_v1_adapter_proto_rawDescGZIP(), []int{1}
}

// SlashGradient mirrors M1's graduated slashing — different failure
// modes carry different bps slash weights. Values stored at adapter
// registration and applied at attestation rejection paths.
type SlashGradient struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompilerDriftBps uint32                 `protobuf:"varint,1,opt,name=compiler_drift_bps,json=compilerDriftBps,proto3" json:"compiler_drift_bps,omitempty"` // adapter-binary mismatch — typically 10000 (full)
	AxisOverflowBps  uint32                 `protobuf:"varint,2,opt,name=axis_overflow_bps,json=axisOverflowBps,proto3" json:"axis_overflow_bps,omitempty"`    // axis claim exceeds bounds — typically pro-rata
	FraudBps         uint32                 `protobuf:"varint,3,opt,name=fraud_bps,json=fraudBps,proto3" json:"fraud_bps,omitempty"`                           // > rejection threshold reached — typically 10000
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SlashGradient) Reset() {
	*x = SlashGradient{}
	mi := &file_zerone_substrate_bridge_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashGradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashGradient) ProtoMessage() {}

func (x *SlashGradient) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_substrate_bridge_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashGradient.ProtoReflect.Descriptor instead.
func (*SlashGradient) Descriptor() ([]byte, []int) {
	return file_zerone_substrate_bridge_v1_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *SlashGradient) GetCompilerDriftBps() uint32 {
	if x != nil {
		return x.CompilerDriftBps
	}
	return 0
}

func (x *SlashGradient) GetAxisOverflowBps() uint32 {
	if x != nil {
		return x.AxisOverflowBps
	}
	return 0
}

func (x *SlashGradient) GetFraudBps() uint32 {
	if x != nil {
		return x.FraudBps
	}
	return 0
}

// AdapterRegistration is the gov-approved metadata for one adapter.
// Adapter is a recipe (binary hash + bounds + slash); no operator role.
// Anyone who runs the registered binary AND submits an attestation
// earns via the UW formula.
type AdapterRegistration struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	AdapterId                   string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`                              // canonical, gov-approved (e.g. "wikipedia-en-v1")
	SourceType                  string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`                           // "wikipedia" | "arxiv" | "ibc_packet" | etc.
	Version                     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                   // semver
	CompilerBinaryHash          []byte                 `protobuf:"bytes,4,opt,name=compiler_binary_hash,json=compilerBinaryHash,proto3" json:"compiler_binary_hash,omitempty"` // determinism guarantee
	AxisBounds                  *AxisBounds            `protobuf:"bytes,5,opt,name=axis_bounds,json=axisBounds,proto3" json:"axis_bounds,omitempty"`
	MinAttestationBondUzrn      string                 `protobuf:"bytes,6,opt,name=min_attestation_bond_uzrn,json=minAttestationBondUzrn,proto3" json:"min_attestation_bond_uzrn,omitempty"`
	MinPerClaimBondUzrn         string                 `protobuf:"bytes,7,opt,name=min_per_claim_bond_uzrn,json=minPerClaimBondUzrn,proto3" json:"min_per_claim_bond_uzrn,omitempty"`
	SlashGradient               *SlashGradient         `protobuf:"bytes,8,opt,name=slash_gradient,json=slashGradient,proto3" json:"slash_gradient,omitempty"`
	RequiredQualificationDomain string                 `protobuf:"bytes,9,opt,name=required_qualification_domain,json=requiredQualificationDomain,proto3" json:"required_qualification_domain,omitempty"`
	MinQualificationStatus      QualificationStatus    `protobuf:"varint,10,opt,name=min_qualification_status,json=minQualificationStatus,proto3,enum=zerone.substrate_bridge.v1.QualificationStatus" json:"min_qualification_status,omitempty"`
	AllowedClassIds             []string               `protobuf:"bytes,11,rep,name=allowed_class_ids,json=allowedClassIds,proto3" json:"allowed_class_ids,omitempty"` // empty = any class allowed
	Status                      AdapterStatus          `protobuf:"varint,12,opt,name=status,proto3,enum=zerone.substrate_bridge.v1.AdapterStatus" json:"status,omitempty"`
	RegisteredViaLipId          string                 `protobuf:"bytes,13,opt,name=registered_via_lip_id,json=registeredViaLipId,proto3" json:"registered_via_lip_id,omitempty"`
	RegisteredAtBlock           uint64                 `protobuf:"varint,14,opt,name=registered_at_block,json=registeredAtBlock,proto3" json:"registered_at_block,omitempty"`
	TombstonedAtBlock           uint64                 `protobuf:"varint,15,opt,name=tombstoned_at_block,json=tombstonedAtBlock,proto3" json:"tombstoned_at_block,omitempty"` // 0 if not tombstoned
	// Witness reward: uzrn minted (cap-gated) per witness-only attestation
	// settled through this adapter. Escrowed for the challenge window before
	// release — tombstoning the adapter inside the window cancels unpaid
	// rewards (issuance follows survival, not acceptance). Empty or "0"
	// means witness-only attestations return their bond and pay nothing.
	WitnessRewardUzrn string `protobuf:"bytes,16,opt,name=witness_reward_uzrn,json=witnessRewardUzrn,proto3" json:"witness_reward_uzrn,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdapterRegistration) Reset() {
	*x = AdapterRegistration{}
	mi := &file_zerone_substrate_bridge_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterRegistration) ProtoMessage() {}

func (x *AdapterRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_substrate_bridge_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterRegistration.ProtoReflect.Descriptor instead.
func (*AdapterRegistration) Descriptor() ([]byte, []int) {
	return file_zerone_substrate_bridge_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterRegistration) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *AdapterRegistration) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AdapterRegistration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdapterRegistration) GetCompilerBinaryHash() []byte {
	if x != nil {
		return x.CompilerBinaryHash
	}
	return nil
}

func (x *AdapterRegistration) GetAxisBounds() *AxisBounds {
	if x != nil {
		return x.AxisBounds
	}
	return nil
}

func (x *AdapterRegistration) GetMinAttestationBondUzrn() string {
	if x != nil {
		return x.MinAttestationBondUzrn
	}
	return ""
}

func (x *AdapterRegistration) GetMinPerClaimBondUzrn() string {
	if x != nil {
		return x.MinPerClaimBondUzrn
	}
	return ""
}

func (x *AdapterRegistration) GetSlashGradient() *SlashGradient {
	if x != nil {
		return x.SlashGradient
	}
	return nil
}

func (x *AdapterRegistration) GetRequiredQualificationDomain() string {
	if x != nil {
		return x.RequiredQualificationDomain
	}
	return ""
}

func (x *AdapterRegistration) GetMinQualificationStatus() QualificationStatus {
	if x != nil {
		return x.MinQualificationStatus
	}
	return QualificationStatus_QUALIFICATION_STATUS_UNSPECIFIED
}

func (x *AdapterRegistration) GetAllowedClassIds() []string {
	if x != nil {
		return x.AllowedClassIds
	}
	return nil
}

func (x *AdapterRegistration) GetStatus() AdapterStatus {
	if x != nil {
		return x.Status
	}
	return AdapterStatus_ADAPTER_STATUS_UNSPECIFIED
}

func (x *AdapterRegistration) GetRegisteredViaLipId() string {
	if x != nil {
		return x.RegisteredViaLipId
	}
	return ""
}

func (x *AdapterRegistration) GetRegisteredAtBlock() uint64 {
	if x != nil {
		return x.RegisteredAtBlock
	}
	return 0
}

func (x *AdapterRegistration) GetTombstonedAtBlock() uint64 {
	if x != nil {
		return x.TombstonedAtBlock
	}
	return 0
}

func (x *AdapterRegistration) GetWitnessRewardUzrn() string {
	if x != nil {
		return x.WitnessRewardUzrn
	}
	return ""
}

var File_zerone_substrate_bridge_v1_adapter_proto protoreflect.FileDescriptor

const file_zerone_substrate_bridge_v1_adapter_proto_rawDesc = "" +
	"\n" +
	"(zerone/substrate_bridge/v1/adapter.proto\x12\x1azerone.substrate_bridge.v1\x1a&zerone/substrate_bridge/v1/types.proto\"\x86\x01\n" +
	"\rSlashGradient\x12,\n" +
	"\x12compiler_drift_bps\x18\x01 \x01(\rR\x10compilerDriftBps\x12*\n" +
	"\x11axis_overflow_bps\x18\x02 \x01(\rR\x0faxisOverflowBps\x12\x1b\n" +
	"\tfraud_bps\x18\x03 \x01(\rR\bfraudBps\"\x8e\a\n" +
	"\x13AdapterRegistration\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x120\n" +
	"\x14compiler_binary_hash\x18\x04 \x01(\fR\x12compilerBinaryHash\x12G\n" +
	"\vaxis_bounds\x18\x05 \x01(\v2&.zerone.substrate_bridge.v1.AxisBoundsR\n" +
	"axisBounds\x129\n" +
	"\x19min_attestation_bond_uzrn\x18\x06 \x01(\tR\x16minAttestationBondUzrn\x124\n" +
	"\x17min_per_claim_bond_uzrn\x18\a \x01(\tR\x13minPerClaimBondUzrn\x12P\n" +
	"\x0eslash_gradient\x18\b \x01(\v2).zerone.substrate_bridge.v1.SlashGradientR\rslashGradient\x12B\n" +
	"\x1drequired_qualification_domain\x18\t \x01(\tR\x1brequiredQualificationDomain\x12i\n" +
	"\x18min_qualification_status\x18\n" +
	" \x01(\x0e2/.zerone.substrate_bridge.v1.QualificationStatusR\x16minQualificationStatus\x12*\n" +
	"\x11allowed_class_ids\x18\v \x03(\tR\x0fallowedClassIds\x12A\n" +
	"\x06status\x18\f \x01(\x0e2).zerone.substrate_bridge.v1.AdapterStatusR\x06status\x121\n" +
	"\x15registered_via_lip_id\x18\r \x01(\tR\x12registeredViaLipId\x12.\n" +
	"\x13registered_at_block\x18\x0e \x01(\x04R\x11registeredAtBlock\x12.\n" +
	"\x13tombstoned_at_block\x18\x0f \x01(\x04R\x11tombstonedAtBlock\x12.\n" +
	"\x13witness_reward_uzrn\x18\x10 \x01(\tR\x11witnessRewardUzrn*\x87\x01\n" +
	"\rAdapterStatus\x12\x1e\n" +
	"\x1aADAPTER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ADAPTER_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ADAPTER_STATUS_SUSPENDED\x10\x02\x12\x1d\n" +
	"\x19ADAPTER_STATUS_TOMBSTONED\x10\x03*\xab\x01\n" +
	"\x13QualificationStatus\x12$\n" +
	" QUALIFICATION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!QUALIFICATION_STATUS_PROBATIONARY\x10\x01\x12\x1f\n" +
	"\x1bQUALIFICATION_STATUS_ACTIVE\x10\x02\x12&\n" +
	"\"QUALIFICATION_STATUS_DISTINGUISHED\x10\x03B9Z7github.com/zerone-chain/zerone/x/substrate_bridge/typesb\x06proto3"

var (
	file_zerone_substrate_bridge_v1_adapter_proto_rawDescOnce sync.Once
	file_zerone_substrate_bridge_v1_adapter_proto_rawDescData []byte
)

func file_zerone_substrate_bridge_v1_adapter_proto_rawDescGZIP() []byte {
	file_zerone_substrate_bridge_v1_adapter_proto_rawDescOnce.Do(func() {
		file_zerone_substrate_bridge_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_substrate_bridge_v1_adapter_proto_rawDesc), len(file_zerone_substrate_bridge_v1_adapter_proto_rawDesc)))
	})
	return file_zerone_substrate_bridge_v1_adapter_proto_rawDescData
}

var file_zerone_substrate_bridge_v1_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zerone_substrate_bridge_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zerone_substrate_bridge_v1_adapter_proto_goTypes = []any{
	(AdapterStatus)(0),          // 0: zerone.substrate_bridge.v1.AdapterStatus
	(QualificationStatus)(0),    // 1: zerone.substrate_bridge.v1.QualificationStatus
	(*SlashGradient)(nil),       // 2: zerone.substrate_bridge.v1.SlashGradient
	(*AdapterRegistration)(nil), // 3: zerone.substrate_bridge.v1.AdapterRegistration
	(*AxisBounds)(nil),          // 4: zerone.substrate_bridge.v1.AxisBounds
}
var file_zerone_substrate_bridge_v1_adapter_proto_depIdxs = []int32{
	4, // 0: zerone.substrate_bridge.v1.AdapterRegistration.axis_bounds:type_name -> zerone.substrate_bridge.v1.AxisBounds
	2, // 1: zerone.substrate_bridge.v1.AdapterRegistration.slash_gradient:type_name -> zerone.substrate_bridge.v1.SlashGradient
	1, // 2: zerone.substrate_bridge.v1.AdapterRegistration.min_qualification_status:type_name -> zerone.substrate_bridge.v1.QualificationStatus
	0, // 3: zerone.substrate_bridge.v1.AdapterRegistration.status:type_name -> zerone.substrate_bridge.v1.AdapterStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zerone_substrate_bridge_v1_adapter_proto_init() }
func file_zerone_substrate_bridge_v1_adapter_proto_init() {
	if File_zerone_substrate_bridge_v1_adapter_proto != nil {
		return
	}
	file_zerone_substrate_bridge_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_substrate_bridge_v1_adapter_proto_rawDesc), len(file_zerone_substrate_bridge_v1_adapter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_substrate_bridge_v1_adapter_proto_goTypes,
		DependencyIndexes: file_zerone_substrate_bridge_v1_adapter_proto_depIdxs,
		EnumInfos:         file_zerone_substrate_bridge_v1_adapter_proto_enumTypes,
		MessageInfos:      file_zerone_substrate_bridge_v1_adapter_proto_msgTypes,
	}.Build()
	File_zerone_substrate_bridge_v1_adapter_proto = out.File
	file_zerone_substrate_bridge_v1_adapter_proto_goTypes = nil
	file_zerone_substrate_bridge_v1_adapter_proto_depIdxs = nil
}
