// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/substrate_bridge/v1/params.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	MaxPendingClaimsPerAttestation    uint32                 `protobuf:"varint,1,opt,name=max_pending_claims_per_attestation,json=maxPendingClaimsPerAttestation,proto3" json:"max_pending_claims_per_attestation,omitempty"`
	PerPendingClaimBondUzrn           string                 `protobuf:"bytes,2,opt,name=per_pending_claim_bond_uzrn,json=perPendingClaimBondUzrn,proto3" json:"per_pending_claim_bond_uzrn,omitempty"`
	AttestationMinBondUzrn            string                 `protobuf:"bytes,3,opt,name=attestation_min_bond_uzrn,json=attestationMinBondUzrn,proto3" json:"attestation_min_bond_uzrn,omitempty"`
	MaxPendingWindowBlocks            uint64                 `protobuf:"varint,4,opt,name=max_pending_window_blocks,json=maxPendingWindowBlocks,proto3" json:"max_pending_window_blocks,omitempty"`
	PendingClaimRejectionThresholdBps uint32                 `protobuf:"varint,5,opt,name=pending_claim_rejection_threshold_bps,json=pendingClaimRejectionThresholdBps,proto3" json:"pending_claim_rejection_threshold_bps,omitempty"`
	MinVerifiedRatioForSettleBps      uint32                 `protobuf:"varint,6,opt,name=min_verified_ratio_for_settle_bps,json=minVerifiedRatioForSettleBps,proto3" json:"min_verified_ratio_for_settle_bps,omitempty"`
	LineageShareBps                   uint32                 `protobuf:"varint,7,opt,name=lineage_share_bps,json=lineageShareBps,proto3" json:"lineage_share_bps,omitempty"`
	DecayBpsPerHop                    uint32                 `protobuf:"varint,8,opt,name=decay_bps_per_hop,json=decayBpsPerHop,proto3" json:"decay_bps_per_hop,omitempty"`
	MaxPropagationDepth               uint32                 `protobuf:"varint,9,opt,name=max_propagation_depth,json=maxPropagationDepth,proto3" json:"max_propagation_depth,omitempty"`
	MinPropagationUzrn                string                 `protobuf:"bytes,10,opt,name=min_propagation_uzrn,json=minPropagationUzrn,proto3" json:"min_propagation_uzrn,omitempty"`
	SelfCitationCapBps                uint32                 `protobuf:"varint,11,opt,name=self_citation_cap_bps,json=selfCitationCapBps,proto3" json:"self_citation_cap_bps,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_zerone_substrate_bridge_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_substrate_bridge_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_zerone_substrate_bridge_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetMaxPendingClaimsPerAttestation() uint32 {
	if x != nil {
		return x.MaxPendingClaimsPerAttestation
	}
	return 0
}

func (x *Params) GetPerPendingClaimBondUzrn() string {
	if x != nil {
		return x.PerPendingClaimBondUzrn
	}
	return ""
}

func (x *Params) GetAttestationMinBondUzrn() string {
	if x != nil {
		return x.AttestationMinBondUzrn
	}
	return ""
}

func (x *Params) GetMaxPendingWindowBlocks() uint64 {
	if x != nil {
		return x.MaxPendingWindowBlocks
	}
	return 0
}

func (x *Params) GetPendingClaimRejectionThresholdBps() uint32 {
	if x != nil {
		return x.PendingClaimRejectionThresholdBps
	}
	return 0
}

func (x *Params) GetMinVerifiedRatioForSettleBps() uint32 {
	if x != nil {
		return x.MinVerifiedRatioForSettleBps
	}
	return 0
}

func (x *Params) GetLineageShareBps() uint32 {
	if x != nil {
		return x.LineageShareBps
	}
	return 0
}

func (x *Params) GetDecayBpsPerHop() uint32 {
	if x != nil {
		return x.DecayBpsPerHop
	}
	return 0
}

func (x *Params) GetMaxPropagationDepth() uint32 {
	if x != nil {
		return x.MaxPropagationDepth
	}
	return 0
}

func (x *Params) GetMinPropagationUzrn() string {
	if x != nil {
		return x.MinPropagationUzrn
	}
	return ""
}

func (x *Params) GetSelfCitationCapBps() uint32 {
	if x != nil {
		return x.SelfCitationCapBps
	}
	return 0
}

var File_zerone_substrate_bridge_v1_params_proto protoreflect.FileDescriptor

const file_zerone_substrate_bridge_v1_params_proto_rawDesc = "" +
	"\n" +
	"'zerone/substrate_bridge/v1/params.proto\x12\x1azerone.substrate_bridge.v1\"\x93\x05\n" +
	"\x06Params\x12J\n" +
	"\"max_pending_claims_per_attestation\x18\x01 \x01(\rR\x1emaxPendingClaimsPerAttestation\x12<\n" +
	"\x1bper_pending_claim_bond_uzrn\x18\x02 \x01(\tR\x17perPendingClaimBondUzrn\x129\n" +
	"\x19attestation_min_bond_uzrn\x18\x03 \x01(\tR\x16attestationMinBondUzrn\x129\n" +
	"\x19max_pending_window_blocks\x18\x04 \x01(\x04R\x16maxPendingWindowBlocks\x12P\n" +
	"%pending_claim_rejection_threshold_bps\x18\x05 \x01(\rR!pendingClaimRejectionThresholdBps\x12G\n" +
	"!min_verified_ratio_for_settle_bps\x18\x06 \x01(\rR\x1cminVerifiedRatioForSettleBps\x12*\n" +
	"\x11lineage_share_bps\x18\a \x01(\rR\x0flineageShareBps\x12)\n" +
	"\x11decay_bps_per_hop\x18\b \x01(\rR\x0edecayBpsPerHop\x122\n" +
	"\x15max_propagation_depth\x18\t \x01(\rR\x13maxPropagationDepth\x120\n" +
	"\x14min_propagation_uzrn\x18\n" +
	" \x01(\tR\x12minPropagationUzrn\x121\n" +
	"\x15self_citation_cap_bps\x18\v \x01(\rR\x12selfCitationCapBpsB9Z7github.com/zerone-chain/zerone/x/substrate_bridge/typesb\x06proto3"

var (
	file_zerone_substrate_bridge_v1_params_proto_rawDescOnce sync.Once
	file_zerone_substrate_bridge_v1_params_proto_rawDescData []byte
)

func file_zerone_substrate_bridge_v1_params_proto_rawDescGZIP() []byte {
	file_zerone_substrate_bridge_v1_params_proto_rawDescOnce.Do(func() {
		file_zerone_substrate_bridge_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_substrate_bridge_v1_params_proto_rawDesc), len(file_zerone_substrate_bridge_v1_params_proto_rawDesc)))
	})
	return file_zerone_substrate_bridge_v1_params_proto_rawDescData
}

var file_zerone_substrate_bridge_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zerone_substrate_bridge_v1_params_proto_goTypes = []any{
	(*Params)(nil), // 0: zerone.substrate_bridge.v1.Params
}
var file_zerone_substrate_bridge_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zerone_substrate_bridge_v1_params_proto_init() }
func file_zerone_substrate_bridge_v1_params_proto_init() {
	if File_zerone_substrate_bridge_v1_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_substrate_bridge_v1_params_proto_rawDesc), len(file_zerone_substrate_bridge_v1_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_substrate_bridge_v1_params_proto_goTypes,
		DependencyIndexes: file_zerone_substrate_bridge_v1_params_proto_depIdxs,
		MessageInfos:      file_zerone_substrate_bridge_v1_params_proto_msgTypes,
	}.Build()
	File_zerone_substrate_bridge_v1_params_proto = out.File
	file_zerone_substrate_bridge_v1_params_proto_goTypes = nil
	file_zerone_substrate_bridge_v1_params_proto_depIdxs = nil
}
