// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/schedule/v2/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{0}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryScheduleRequest) Reset() {
	*x = QueryScheduleRequest{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScheduleRequest) ProtoMessage() {}

func (x *QueryScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScheduleRequest.ProtoReflect.Descriptor instead.
func (*QueryScheduleRequest) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryScheduleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryScheduleResponse) Reset() {
	*x = QueryScheduleResponse{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScheduleResponse) ProtoMessage() {}

func (x *QueryScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScheduleResponse.ProtoReflect.Descriptor instead.
func (*QueryScheduleResponse) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type QuerySchedulesByCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	StartAfter    string                 `protobuf:"bytes,2,opt,name=start_after,json=startAfter,proto3" json:"start_after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySchedulesByCreatorRequest) Reset() {
	*x = QuerySchedulesByCreatorRequest{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySchedulesByCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySchedulesByCreatorRequest) ProtoMessage() {}

func (x *QuerySchedulesByCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySchedulesByCreatorRequest.ProtoReflect.Descriptor instead.
func (*QuerySchedulesByCreatorRequest) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySchedulesByCreatorRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *QuerySchedulesByCreatorRequest) GetStartAfter() string {
	if x != nil {
		return x.StartAfter
	}
	return ""
}

func (x *QuerySchedulesByCreatorRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QuerySchedulesByCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	NextKey       string                 `protobuf:"bytes,2,opt,name=next_key,json=nextKey,proto3" json:"next_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySchedulesByCreatorResponse) Reset() {
	*x = QuerySchedulesByCreatorResponse{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySchedulesByCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySchedulesByCreatorResponse) ProtoMessage() {}

func (x *QuerySchedulesByCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySchedulesByCreatorResponse.ProtoReflect.Descriptor instead.
func (*QuerySchedulesByCreatorResponse) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySchedulesByCreatorResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *QuerySchedulesByCreatorResponse) GetNextKey() string {
	if x != nil {
		return x.NextKey
	}
	return ""
}

type QueryReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OccurrenceId  string                 `protobuf:"bytes,1,opt,name=occurrence_id,json=occurrenceId,proto3" json:"occurrence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReceiptRequest) Reset() {
	*x = QueryReceiptRequest{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReceiptRequest) ProtoMessage() {}

func (x *QueryReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReceiptRequest.ProtoReflect.Descriptor instead.
func (*QueryReceiptRequest) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryReceiptRequest) GetOccurrenceId() string {
	if x != nil {
		return x.OccurrenceId
	}
	return ""
}

type QueryReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *ExecutionReceipt      `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReceiptResponse) Reset() {
	*x = QueryReceiptResponse{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReceiptResponse) ProtoMessage() {}

func (x *QueryReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReceiptResponse.ProtoReflect.Descriptor instead.
func (*QueryReceiptResponse) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryReceiptResponse) GetReceipt() *ExecutionReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type QueryReceiptsByScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	StartSequence uint32                 `protobuf:"varint,2,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReceiptsByScheduleRequest) Reset() {
	*x = QueryReceiptsByScheduleRequest{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReceiptsByScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReceiptsByScheduleRequest) ProtoMessage() {}

func (x *QueryReceiptsByScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReceiptsByScheduleRequest.ProtoReflect.Descriptor instead.
func (*QueryReceiptsByScheduleRequest) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryReceiptsByScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *QueryReceiptsByScheduleRequest) GetStartSequence() uint32 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *QueryReceiptsByScheduleRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryReceiptsByScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*ExecutionReceipt    `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	NextSequence  uint32                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReceiptsByScheduleResponse) Reset() {
	*x = QueryReceiptsByScheduleResponse{}
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReceiptsByScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReceiptsByScheduleResponse) ProtoMessage() {}

func (x *QueryReceiptsByScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_schedule_v2_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReceiptsByScheduleResponse.ProtoReflect.Descriptor instead.
func (*QueryReceiptsByScheduleResponse) Descriptor() ([]byte, []int) {
	return file_zerone_schedule_v2_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryReceiptsByScheduleResponse) GetReceipts() []*ExecutionReceipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *QueryReceiptsByScheduleResponse) GetNextSequence() uint32 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

var File_zerone_schedule_v2_query_proto protoreflect.FileDescriptor

const file_zerone_schedule_v2_query_proto_rawDesc = "" +
	"\n" +
	"\x1ezerone/schedule/v2/query.proto\x12\x12zerone.schedule.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1ezerone/schedule/v2/state.proto\"\x14\n" +
	"\x12QueryParamsRequest\"I\n" +
	"\x13QueryParamsResponse\x122\n" +
	"\x06params\x18\x01 \x01(\v2\x1a.zerone.schedule.v2.ParamsR\x06params\"&\n" +
	"\x14QueryScheduleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x15QueryScheduleResponse\x128\n" +
	"\bschedule\x18\x01 \x01(\v2\x1c.zerone.schedule.v2.ScheduleR\bschedule\"q\n" +
	"\x1eQuerySchedulesByCreatorRequest\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1f\n" +
	"\vstart_after\x18\x02 \x01(\tR\n" +
	"startAfter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"x\n" +
	"\x1fQuerySchedulesByCreatorResponse\x12:\n" +
	"\tschedules\x18\x01 \x03(\v2\x1c.zerone.schedule.v2.ScheduleR\tschedules\x12\x19\n" +
	"\bnext_key\x18\x02 \x01(\tR\anextKey\":\n" +
	"\x13QueryReceiptRequest\x12#\n" +
	"\roccurrence_id\x18\x01 \x01(\tR\foccurrenceId\"V\n" +
	"\x14QueryReceiptResponse\x12>\n" +
	"\areceipt\x18\x01 \x01(\v2$.zerone.schedule.v2.ExecutionReceiptR\areceipt\"~\n" +
	"\x1eQueryReceiptsByScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12%\n" +
	"\x0estart_sequence\x18\x02 \x01(\rR\rstartSequence\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\x88\x01\n" +
	"\x1fQueryReceiptsByScheduleResponse\x12@\n" +
	"\breceipts\x18\x01 \x03(\v2$.zerone.schedule.v2.ExecutionReceiptR\breceipts\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\rR\fnextSequence2\xa1\x06\n" +
	"\x05Query\x12}\n" +
	"\x06Params\x12&.zerone.schedule.v2.QueryParamsRequest\x1a'.zerone.schedule.v2.QueryParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/zerone/schedule/v2/params\x12\x8b\x01\n" +
	"\bSchedule\x12(.zerone.schedule.v2.QueryScheduleRequest\x1a).zerone.schedule.v2.QueryScheduleResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/zerone/schedule/v2/schedules/{id}\x12\xb7\x01\n" +
	"\x12SchedulesByCreator\x122.zerone.schedule.v2.QuerySchedulesByCreatorRequest\x1a3.zerone.schedule.v2.QuerySchedulesByCreatorResponse\"8\x82\xd3\xe4\x93\x022\x120/zerone/schedule/v2/creators/{creator}/schedules\x12\x92\x01\n" +
	"\aReceipt\x12'.zerone.schedule.v2.QueryReceiptRequest\x1a(.zerone.schedule.v2.QueryReceiptResponse\"4\x82\xd3\xe4\x93\x02.\x12,/zerone/schedule/v2/receipts/{occurrence_id}\x12\xbb\x01\n" +
	"\x12ReceiptsBySchedule\x122.zerone.schedule.v2.QueryReceiptsByScheduleRequest\x1a3.zerone.schedule.v2.QueryReceiptsByScheduleResponse\"<\x82\xd3\xe4\x93\x026\x124/zerone/schedule/v2/schedules/{schedule_id}/receiptsB1Z/github.com/zerone-chain/zerone/x/schedule/typesb\x06proto3"

var (
	file_zerone_schedule_v2_query_proto_rawDescOnce sync.Once
	file_zerone_schedule_v2_query_proto_rawDescData []byte
)

func file_zerone_schedule_v2_query_proto_rawDescGZIP() []byte {
	file_zerone_schedule_v2_query_proto_rawDescOnce.Do(func() {
		file_zerone_schedule_v2_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_schedule_v2_query_proto_rawDesc), len(file_zerone_schedule_v2_query_proto_rawDesc)))
	})
	return file_zerone_schedule_v2_query_proto_rawDescData
}

var file_zerone_schedule_v2_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zerone_schedule_v2_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),              // 0: zerone.schedule.v2.QueryParamsRequest
	(*QueryParamsResponse)(nil),             // 1: zerone.schedule.v2.QueryParamsResponse
	(*QueryScheduleRequest)(nil),            // 2: zerone.schedule.v2.QueryScheduleRequest
	(*QueryScheduleResponse)(nil),           // 3: zerone.schedule.v2.QueryScheduleResponse
	(*QuerySchedulesByCreatorRequest)(nil),  // 4: zerone.schedule.v2.QuerySchedulesByCreatorRequest
	(*QuerySchedulesByCreatorResponse)(nil), // 5: zerone.schedule.v2.QuerySchedulesByCreatorResponse
	(*QueryReceiptRequest)(nil),             // 6: zerone.schedule.v2.QueryReceiptRequest
	(*QueryReceiptResponse)(nil),            // 7: zerone.schedule.v2.QueryReceiptResponse
	(*QueryReceiptsByScheduleRequest)(nil),  // 8: zerone.schedule.v2.QueryReceiptsByScheduleRequest
	(*QueryReceiptsByScheduleResponse)(nil), // 9: zerone.schedule.v2.QueryReceiptsByScheduleResponse
	(*Params)(nil),                          // 10: zerone.schedule.v2.Params
	(*Schedule)(nil),                        // 11: zerone.schedule.v2.Schedule
	(*ExecutionReceipt)(nil),                // 12: zerone.schedule.v2.ExecutionReceipt
}
var file_zerone_schedule_v2_query_proto_depIdxs = []int32{
	10, // 0: zerone.schedule.v2.QueryParamsResponse.params:type_name -> zerone.schedule.v2.Params
	11, // 1: zerone.schedule.v2.QueryScheduleResponse.schedule:type_name -> zerone.schedule.v2.Schedule
	11, // 2: zerone.schedule.v2.QuerySchedulesByCreatorResponse.schedules:type_name -> zerone.schedule.v2.Schedule
	12, // 3: zerone.schedule.v2.QueryReceiptResponse.receipt:type_name -> zerone.schedule.v2.ExecutionReceipt
	12, // 4: zerone.schedule.v2.QueryReceiptsByScheduleResponse.receipts:type_name -> zerone.schedule.v2.ExecutionReceipt
	0,  // 5: zerone.schedule.v2.Query.Params:input_type -> zerone.schedule.v2.QueryParamsRequest
	2,  // 6: zerone.schedule.v2.Query.Schedule:input_type -> zerone.schedule.v2.QueryScheduleRequest
	4,  // 7: zerone.schedule.v2.Query.SchedulesByCreator:input_type -> zerone.schedule.v2.QuerySchedulesByCreatorRequest
	6,  // 8: zerone.schedule.v2.Query.Receipt:input_type -> zerone.schedule.v2.QueryReceiptRequest
	8,  // 9: zerone.schedule.v2.Query.ReceiptsBySchedule:input_type -> zerone.schedule.v2.QueryReceiptsByScheduleRequest
	1,  // 10: zerone.schedule.v2.Query.Params:output_type -> zerone.schedule.v2.QueryParamsResponse
	3,  // 11: zerone.schedule.v2.Query.Schedule:output_type -> zerone.schedule.v2.QueryScheduleResponse
	5,  // 12: zerone.schedule.v2.Query.SchedulesByCreator:output_type -> zerone.schedule.v2.QuerySchedulesByCreatorResponse
	7,  // 13: zerone.schedule.v2.Query.Receipt:output_type -> zerone.schedule.v2.QueryReceiptResponse
	9,  // 14: zerone.schedule.v2.Query.ReceiptsBySchedule:output_type -> zerone.schedule.v2.QueryReceiptsByScheduleResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_zerone_schedule_v2_query_proto_init() }
func file_zerone_schedule_v2_query_proto_init() {
	if File_zerone_schedule_v2_query_proto != nil {
		return
	}
	file_zerone_schedule_v2_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_schedule_v2_query_proto_rawDesc), len(file_zerone_schedule_v2_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerone_schedule_v2_query_proto_goTypes,
		DependencyIndexes: file_zerone_schedule_v2_query_proto_depIdxs,
		MessageInfos:      file_zerone_schedule_v2_query_proto_msgTypes,
	}.Build()
	File_zerone_schedule_v2_query_proto = out.File
	file_zerone_schedule_v2_query_proto_goTypes = nil
	file_zerone_schedule_v2_query_proto_depIdxs = nil
}
