#!/usr/bin/env python3
"""Signed claim exercises for the persistent claims-v1 LOCAL sandbox (Python 3.11+).

All accounts are disposable test identities under one controller. This helper
never starts a node, accepts remote endpoints, or retries a broadcast silently.
"""
from __future__ import annotations

import argparse
import base64
from contextlib import contextmanager
import fcntl
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import secrets
import stat
import subprocess
import sys
import time


def sibling(name):
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), Path(__file__).with_name(name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


local = sibling("local-node")
SCHEMA = "zerone-claim-workflow-v1"
NOTICE = ("Local test identities and valueless funds, controlled by one operator. "
          "Panel agreement is not independent scientific verification. Retained history is a node observation, not an inclusion proof.")
ACTORS = ("user", "reviewer1", "reviewer2", "reviewer3", "challenger")
REVIEWERS = ACTORS[1:4]
MAX_RECORDS = 100
MAX_JSON = 8 * 1024 * 1024
PENDING = ("prepared", "broadcasting", "pending")


class WorkflowError(Exception):
    pass


def integer(value, name, minimum=0):
    if isinstance(value, bool) or not re.fullmatch(r"0|[1-9][0-9]*", str(value)):
        raise WorkflowError(f"Invalid {name}.")
    result = int(value)
    if result < minimum:
        raise WorkflowError(f"Invalid {name}.")
    return result


def parse_json(raw):
    if len(raw.encode()) > MAX_JSON:
        raise WorkflowError("Local JSON exceeds the workflow bound.")
    def pairs(rows):
        result = {}
        for key, value in rows:
            if key in result:
                raise WorkflowError("Duplicate JSON field.")
            result[key] = value
        return result
    return json.loads(raw, object_pairs_hook=pairs)


def private_directory(path):
    try:
        path.mkdir(mode=0o700)
    except FileExistsError:
        pass
    info = path.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
        raise WorkflowError("Workflow directories must be private, owned, and not symlinks.")


def read_json(path):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    with os.fdopen(fd, "rb") as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or info.st_uid != os.getuid() or info.st_mode & 0o077:
            raise WorkflowError("Workflow files must be private owned regular files with one link.")
        raw = stream.read(MAX_JSON + 1)
    if len(raw) > MAX_JSON:
        raise WorkflowError("Workflow record exceeds the read bound.")
    return parse_json(raw.decode())


def save_json(path, value, fresh=False):
    raw = (json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n").encode()
    if len(raw) > MAX_JSON:
        raise WorkflowError("Workflow record exceeds the write bound.")
    if fresh:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
        with os.fdopen(fd, "wb") as stream:
            stream.write(raw)
            stream.flush()
            os.fsync(stream.fileno())
    else:
        read_json(path)  # Refuse links or replaced control files before update.
        temporary = path.with_name(".write-" + secrets.token_hex(12))
        save_json(temporary, value, fresh=True)
        os.replace(temporary, path)
    directory = os.open(path.parent, os.O_RDONLY)
    try:
        os.fsync(directory)
    finally:
        os.close(directory)


def public_receipt(attempt):
    # Never return command arguments, raw signed transactions or error output:
    # a prepared reveal contains the still-unpublished vote and attestation.
    fields = ("id", "action", "actor", "status", "txhash", "height", "code", "gas_wanted", "gas_used", "claim_id", "round_id")
    result = {key: attempt[key] for key in fields if key in attempt}
    if "tx_bytes_base64" in attempt:
        result["tx_bytes"] = len(base64.b64decode(attempt["tx_bytes_base64"], validate=True))
    for key in ("review_fee_uzrn", "collateral_uzrn"):
        if key in attempt.get("context", {}):
            result[key] = attempt["context"][key]
    return result


def signing_json(value):
    # The current SDK signing JSON codec lacks this generated enum's symbolic
    # registration, although generate-only emits its name. Both are protobuf
    # JSON representations of the same value. Keep this bridge specific to the
    # ordinary assertion generated by this workflow; never rewrite text fields.
    for message in value.get("body", {}).get("messages", []):
        if message.get("@type") == "/zerone.knowledge.v1.MsgSubmitClaim":
            if message.get("claim_type") not in ("CLAIM_TYPE_ASSERTION", 1, "1"):
                raise WorkflowError("Unexpected ordinary claim type in signing JSON.")
            message["claim_type"] = 1
    return value


class Workflow:
    def __init__(self, home, wait=30):
        self.home = local.home_path(str(home))
        self.manifest = local.load_manifest(self.home)
        if self.manifest.get("knowledge_profile") != "claims-v1":
            raise WorkflowError("Use a fresh local-node init --knowledge-profile claims-v1 home.")
        self.accounts = self.manifest.get("accounts", {})
        if not isinstance(self.accounts, dict) or any(not re.fullmatch(r"zrn1[023456789acdefghjklmnpqrstuvwxyz]{38}", self.accounts.get(actor, "")) for actor in ACTORS):
            raise WorkflowError("The claims profile lacks its funded test accounts.")
        if len(set(self.accounts.values())) != len(self.accounts):
            raise WorkflowError("The claims profile aliases test accounts.")
        self.chain = self.manifest["chain_id"]
        self.rpc = f"http://127.0.0.1:{self.manifest['rpc_port']}"
        self.wait = wait
        self.directory = self.home / "claim-workflow"
        private_directory(self.directory)
        for name in ("attempts", "reviews"):
            private_directory(self.directory / name)
        self.check_node()

    def check_node(self):
        current = local.load_manifest(self.home)
        if current != self.manifest:
            raise WorkflowError("Local manifest changed during the workflow.")
        value = local.rpc_status(self.manifest)
        if value["sync_info"]["catching_up"] is not False:
            raise WorkflowError("Wait for the local node to finish catching up.")
        return integer(value["sync_info"]["latest_block_height"], "local block height", 1)

    @contextmanager
    def locked(self):
        fd = os.open(self.directory / ".lock", os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW, 0o600)
        with os.fdopen(fd, "r+") as lock:
            info = os.fstat(lock.fileno())
            if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or info.st_mode & 0o077:
                raise WorkflowError("Unsafe workflow lock.")
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise WorkflowError("Another workflow command is active; no transaction was sent.") from error
            yield

    def cli(self, *args, missing=False):
        result = subprocess.run([str(self.home / "bin/zeroned"), *map(str, args), "--home", str(self.home)],
                                capture_output=True, text=True, timeout=60, env=local.node_environment())
        if result.returncode:
            if missing and re.search(r"(?i)(tx .*not found|transaction .*not found)", result.stderr):
                return None
            # Computed commitment guidance contains the secret salt. Its full
            # diagnostic stays private; the reader receives neither it nor args.
            diagnostic = self.directory / "last-cli-error.json"
            save_json(diagnostic, {"command_family": list(map(str, args[:2])), "exit_code": result.returncode,
                                   "stderr": result.stderr[-65536:]}, fresh=not diagnostic.exists())
            raise WorkflowError(f"zeroned {' '.join(map(str, args[:2]))} failed (exit {result.returncode}); private diagnostic: claim-workflow/last-cli-error.json. No success is asserted.")
        return result.stdout.strip()

    def query(self, *args, height=None):
        self.check_node()
        flags = ["--node", self.rpc, "--output", "json"]
        if height is not None:
            flags += ["--height", str(height)]
        return parse_json(self.cli("query", *args, *flags))

    def records(self, name):
        paths = sorted((self.directory / name).iterdir())
        if len(paths) > MAX_RECORDS:
            raise WorkflowError("Local workflow inventory limit reached; no result was truncated.")
        result = []
        for path in paths:
            if not re.fullmatch(r"[0-9a-f]{32,64}\.json", path.name):
                raise WorkflowError("Unexpected workflow inventory entry.")
            value = read_json(path)
            if value.get("schema") != SCHEMA or value.get("chain_id") != self.chain:
                raise WorkflowError("Workflow record belongs to a different schema or chain.")
            result.append((path, value))
        return result

    def actor(self, actor):
        if actor not in ACTORS:
            raise WorkflowError("Choose a named claims-profile test actor.")
        self.check_node()
        address = self.cli("keys", "show", actor, "-a", "--keyring-backend", "test")
        if address != self.accounts[actor]:
            raise WorkflowError("The test signing account differs from the initialized profile.")
        return address

    def tx_observation(self, digest):
        self.check_node()
        raw = self.cli("query", "tx", digest, "--node", self.rpc, "--output", "json", missing=True)
        if raw is None:
            return None
        value = parse_json(raw)
        if value.get("txhash", "").upper() != digest:
            raise WorkflowError("Transaction query returned a different hash.")
        integer(value.get("height"), "transaction height", 1)
        integer(value.get("code", 0), "transaction code")
        for field in ("gas_used", "gas_wanted"):
            integer(value.get(field), field)
        return value

    def finish(self, path, attempt, observation):
        for field in ("height", "code", "gas_wanted", "gas_used"):
            attempt[field] = observation.get(field, 0)
        attempt["status"] = "committed" if int(attempt["code"]) == 0 else "failed"
        attempt["receipt"] = observation
        for field in ("claim_id", "round_id"):
            if field in attempt.get("context", {}):
                attempt[field] = attempt["context"][field]
        if attempt["action"] in ("submit", "challenge") and attempt["status"] == "committed":
            id_key = "counter_claim_id" if attempt["action"] == "challenge" else "claim_id"
            event_type = "zerone.knowledge.submit_contradiction" if attempt["action"] == "challenge" else "zerone.knowledge.submit_claim"
            ids = {attribute["value"] for event in observation.get("events", [])
                   if event.get("type") == event_type
                   for attribute in event.get("attributes", []) if attribute.get("key") == id_key}
            if len(ids) != 1:
                # Receipt remains durable even if a source/event format changes.
                attempt["status"] = "committed-unresolved"
            else:
                attempt["claim_id"] = ids.pop()
        save_json(path, attempt)
        return attempt

    def reconcile(self):
        pending = []
        for path, attempt in self.records("attempts"):
            if attempt.get("status") in PENDING:
                observed = self.tx_observation(attempt["txhash"])
                if observed is not None:
                    self.finish(path, attempt, observed)
                else:
                    pending.append(attempt["txhash"])
            elif attempt.get("status") == "committed-unresolved":
                pending.append(attempt["txhash"])
        return pending

    def send(self, action, actor, arguments, context=None):
        if self.reconcile():
            raise WorkflowError("An earlier transaction remains unresolved. Use snapshot/history to query it; no automatic retry or additional broadcast is allowed.")
        address = self.actor(actor)
        if action in ("submit", "challenge"):
            # A repeated documented command may be recovery from lost stdout.
            # Return its observed committed receipt instead of silently creating
            # the same contribution again at another height. The queried fee is
            # excluded because it can change between the two invocations.
            def intent(value):
                return {key: item for key, item in value.items() if key != "review_fee_uzrn"}
            for _, prior in self.records("attempts"):
                if prior.get("action") == action and prior.get("actor") == actor and prior.get("status") == "committed" and intent(prior.get("context", {})) == intent(context or {}):
                    return prior
        if len(self.records("attempts")) >= MAX_RECORDS:
            raise WorkflowError("Local transaction inventory is full.")
        identifier = secrets.token_hex(16)
        path = self.directory / "attempts" / (identifier + ".json")
        unsigned = signing_json(parse_json(self.cli("tx", *arguments, "--from", actor, "--chain-id", self.chain,
            "--node", self.rpc, "--keyring-backend", "test", "--gas", "2000000", "--fees", "2000000uzrn",
            "--generate-only", "--output", "json")))
        # Preparation files live separately from the bounded attempt inventory.
        unsigned_path = self.directory / (identifier + "-unsigned.json")
        signed_path = self.directory / (identifier + "-signed.json")
        save_json(unsigned_path, unsigned, fresh=True)
        signed = signing_json(parse_json(self.cli("tx", "sign", unsigned_path, "--from", actor, "--chain-id", self.chain,
            "--node", self.rpc, "--keyring-backend", "test", "--output", "json")))
        save_json(signed_path, signed, fresh=True)
        encoded = self.cli("tx", "encode", signed_path)
        raw = base64.b64decode(encoded, validate=True)
        if not raw or len(raw) > MAX_JSON:
            raise WorkflowError("Invalid encoded signed transaction.")
        digest = hashlib.sha256(raw).hexdigest().upper()
        attempt = {"schema": SCHEMA, "chain_id": self.chain, "id": identifier, "action": action, "actor": actor,
            "address": address, "status": "prepared", "txhash": digest, "tx_bytes_base64": encoded,
            "context": context or {}, "created_unix": int(time.time())}
        save_json(path, attempt, fresh=True)
        return self.broadcast(path, attempt, signed_path)

    def broadcast(self, path, attempt, signed_path):
        digest = attempt["txhash"]
        raw = base64.b64decode(attempt["tx_bytes_base64"], validate=True)
        if hashlib.sha256(raw).hexdigest().upper() != digest:
            raise WorkflowError("Saved transaction bytes do not match their hash; nothing was broadcast.")
        read_json(signed_path)
        if self.cli("tx", "encode", signed_path) != attempt["tx_bytes_base64"]:
            raise WorkflowError("Saved signed transaction changed; nothing was broadcast.")
        self.check_node()
        attempt["status"] = "broadcasting"
        attempt["broadcast_count"] = attempt.get("broadcast_count", 0) + 1
        save_json(path, attempt)
        try:
            response = parse_json(self.cli("tx", "broadcast", signed_path, "--node", self.rpc,
                                          "--broadcast-mode", "sync", "--output", "json"))
            if response.get("txhash", "").upper() != digest:
                raise WorkflowError("Broadcast response returned a different hash.")
            code = integer(response.get("code", 0), "CheckTx code")
            if code:
                attempt.update(status="rejected", code=code, check_tx=response)
                for field in ("gas_wanted", "gas_used"):
                    if field in response:
                        try:
                            integer(response[field], field)
                        except WorkflowError:
                            continue
                        attempt[field] = response[field]
                save_json(path, attempt)
                raise WorkflowError(f"CheckTx rejected transaction {digest} with code {code}; receipt retained.")
            attempt["status"] = "pending"
            save_json(path, attempt)
            deadline = time.monotonic() + self.wait
            while time.monotonic() < deadline:
                observed = self.tx_observation(digest)
                if observed is not None:
                    self.finish(path, attempt, observed)
                    if attempt["status"] != "committed":
                        raise WorkflowError(f"Transaction {digest} ended {attempt['status']}; receipt retained.")
                    return attempt
                time.sleep(0.3)
        except (OSError, subprocess.TimeoutExpired, ValueError) as error:
            raise WorkflowError(f"Transaction {digest} has an unresolved outcome; retained for query, never automatically rebroadcast.") from error
        raise WorkflowError(f"Transaction {digest} is pending after {self.wait}s; use snapshot to reconcile, never silently retry.")

    def retry(self, digest):
        digest = digest.upper()
        if not re.fullmatch(r"[0-9A-F]{64}", digest):
            raise WorkflowError("--txhash must be64 hexadecimal characters.")
        matches = [(path, row) for path, row in self.records("attempts") if row.get("txhash") == digest]
        if len(matches) != 1:
            raise WorkflowError("No unique saved transaction matches this hash.")
        path, attempt = matches[0]
        self.actor(attempt["actor"])
        observed = self.tx_observation(digest)
        if observed is not None:
            self.finish(path, attempt, observed)
            if attempt["status"] != "committed":
                raise WorkflowError("The transaction already committed unsuccessfully; it was not rebroadcast.")
            return public_receipt(attempt)
        if attempt["status"] not in (*PENDING, "rejected"):
            raise WorkflowError("This saved transaction has a terminal receipt; it was not rebroadcast.")
        if any(row.get("txhash") != digest and row.get("status") in PENDING for _, row in self.records("attempts")):
            raise WorkflowError("Another transaction is unresolved; retry that exact transaction first.")
        signed_path = self.directory / (attempt["id"] + "-signed.json")
        return public_receipt(self.broadcast(path, attempt, signed_path))

    def onboard(self):
        if self.reconcile():
            raise WorkflowError("Resolve the pending transaction before onboarding another account.")
        result = []
        for actor in ACTORS:
            prior = [value for _, value in self.records("attempts") if value["action"] == "onboard" and value["actor"] == actor and value["status"] == "committed"]
            if prior:
                result.append(public_receipt(prior[-1]))
                continue
            result.append(public_receipt(self.send("onboard", actor, ["zerone_auth", "onboard", "agent"])))
        return {"chain_id": self.chain, "local_only": True, "transactions": result}

    def round_for_claim(self, claim_id):
        response = self.query("knowledge", "claim", claim_id)
        claim = response.get("claim", {})
        if claim.get("id") != claim_id or not claim.get("verification_round_id"):
            raise WorkflowError("Claim query has no matching round.")
        row = self.query("knowledge", "verification-round", claim["verification_round_id"]).get("round", {})
        if row.get("id") != claim["verification_round_id"] or row.get("claim_id") != claim_id:
            raise WorkflowError("Round and claim identities disagree.")
        if integer(row.get("commitment_scheme"), "commitment scheme") != 2 or row.get("commitment_chain_id") != self.chain or integer(row.get("review_policy_version"), "review policy") != 1:
            raise WorkflowError("This workflow requires a current bound, neutral review round.")
        return row

    def submit(self, args):
        # Query both inputs to the existing effective-fee formula at one height.
        height = self.check_node()
        params = self.query("knowledge", "params", height=height)["params"]
        pacing = self.query("alignment", "global-pacing", height=height)
        multiplier = integer(pacing.get("creation_multiplier_bps", "0"), "creation pacing") or 1000000
        fee = integer(params["min_review_fee"], "minimum review fee", 1)
        if multiplier < 1000000:
            fee = fee * 1000000 // multiplier
        return public_receipt(self.send("submit", "user", ["knowledge", "submit-claim", args.content,
            args.domain, args.category, str(fee), "--method-id", args.method, "--reasoning-trace", args.reasoning],
            {"content": args.content, "domain": args.domain, "category": args.category,
             "method": args.method, "reasoning": args.reasoning, "review_fee_uzrn": str(fee)}))

    def review_path(self, claim_id, actor):
        digest = hashlib.sha256((self.chain + "\0" + claim_id + "\0" + actor).encode()).hexdigest()
        return self.directory / "reviews" / (digest + ".json")

    @staticmethod
    def review_flags(review):
        result = ["--commitment-scheme", "2", "--commitment-chain-id", review["chain_id"],
                  "--confidence", str(review["confidence"]), "--review-reason", review["reason"], "--review-scope", review["scope"],
                  "--review-method", review["method"]]
        for item in review["evidence"]:
            result += ["--review-evidence", item]
        return result

    def review(self, args, reveal=False):
        self.actor(args.actor)
        row = self.round_for_claim(args.claim)
        path = self.review_path(args.claim, args.actor)
        existing = path.exists()
        if existing:
            review = read_json(path)
            if not reveal and any(review[field] != getattr(args, field) for field in ("vote", "confidence", "reason", "scope", "method", "evidence")):
                raise WorkflowError("A saved review tuple cannot be replaced. Repeat its exact inputs, or reveal it.")
        else:
            if reveal:
                raise WorkflowError("No saved review tuple; reveal cannot invent replacement values.")
            if len(self.records("reviews")) >= MAX_RECORDS:
                raise WorkflowError("Local review inventory is full.")
            review = {"schema": SCHEMA, "chain_id": self.chain, "claim_id": args.claim, "round_id": row["id"],
                "actor": args.actor, "address": self.accounts[args.actor], "vote": args.vote,
                "confidence": args.confidence, "reason": args.reason, "scope": args.scope, "method": args.method, "evidence": args.evidence,
                "salt": secrets.token_hex(32), "commit_deadline": row["commit_deadline"], "reveal_deadline": row["reveal_deadline"]}
        if review.get("chain_id") != self.chain or review.get("round_id") != row["id"] or review.get("actor") != args.actor or review.get("claim_id") != args.claim or review.get("address") != self.accounts[args.actor]:
            raise WorkflowError("Saved review tuple identity mismatch.")
        self.validate_review(review)
        action = "reveal" if reveal else "commit"
        self.reconcile()
        prior = [value for _, value in self.records("attempts") if value["action"] == action and value["actor"] == args.actor and value.get("context", {}).get("round_id") == row["id"]]
        for attempt in prior:
            if attempt["status"] == "committed":
                return public_receipt(attempt)
            if attempt["status"] in PENDING:
                raise WorkflowError("This review action has an unresolved attempt; no duplicate broadcast was sent.")
        phase = row.get("phase")
        wanted = ("VERIFICATION_PHASE_REVEAL", 2, "2") if reveal else ("VERIFICATION_PHASE_COMMIT", 1, "1")
        if phase not in wanted:
            raise WorkflowError(f"Round is in {phase}; {action} was not sent. Saved tuple is retained.")
        if not existing:
            save_json(path, review, fresh=True)
        arguments = ["knowledge", "submit-reveal", row["id"], review["vote"], review["salt"]] if reveal else [
            "knowledge", "submit-commitment", row["id"], "--vote", review["vote"], "--salt", review["salt"]]
        return public_receipt(self.send(action, args.actor, arguments + self.review_flags(review),
                                       {"claim_id": args.claim, "round_id": row["id"]}))

    @staticmethod
    def validate_review(review):
        if review.get("vote") not in ("accept", "reject", "malformed") or not 0 <= integer(review.get("confidence"), "confidence") <= 1000000:
            raise WorkflowError("Invalid saved review vote or confidence.")
        for field, bound in (("reason", 4096), ("scope", 1024), ("method", 128)):
            if not isinstance(review.get(field), str) or len(review[field].encode()) > bound:
                raise WorkflowError("Review text exceeds the retained-record bounds.")
        if not review["reason"].strip():
            raise WorkflowError("A review must state what was checked.")
        evidence = review.get("evidence")
        if not isinstance(evidence, list) or len(evidence) > 16 or any(not isinstance(item, str) or not item.strip() or len(item.encode()) > 256 for item in evidence) or len(set(evidence)) != len(evidence):
            raise WorkflowError("Review evidence must contain at most16 distinct, nonempty references of256 bytes each.")
        if not re.fullmatch(r"[0-9a-f]{64}", review.get("salt", "")):
            raise WorkflowError("Invalid retained review salt.")

    def challenge(self, args):
        if any("," in item for item in args.evidence):
            raise WorkflowError("Contradiction evidence references cannot contain commas in the current CLI.")
        return public_receipt(self.send("challenge", "challenger", ["knowledge", "submit-contradiction", args.fact,
            args.content, args.stake, args.reason, "--evidence-ids", ",".join(args.evidence)],
            {"fact_id": args.fact, "content": args.content, "reason": args.reason, "evidence": args.evidence, "collateral_uzrn": args.stake}))

    def history(self, claim_id, height=None):
        height = self.check_node() if height is None else height
        value = self.query("knowledge", "claim-history", claim_id, height=height)
        if value.get("chain_id") != self.chain or integer(value.get("block_height"), "history height") != height or value.get("record", {}).get("claim_id") != claim_id:
            raise WorkflowError("Claim history returned a different identity or context.")
        return value

    def snapshot(self):
        with self.locked():
            self.reconcile()
            height = self.check_node()
            attempts = [value for _, value in self.records("attempts")]
            reviews = [value for _, value in self.records("reviews")]
            ids = sorted({value["claim_id"] for value in attempts if value.get("claim_id")} |
                         {value["claim_id"] for value in reviews})
            if len(ids) > MAX_RECORDS:
                raise WorkflowError("Claim inventory exceeds the local bound.")
            pending = []
            for review in reviews:
                matching = [value for value in attempts if value.get("context", {}).get("round_id") == review["round_id"] and value["actor"] == review["actor"]]
                revealed = any(value["action"] == "reveal" and value["status"] == "committed" for value in matching)
                committed = any(value["action"] == "commit" and value["status"] == "committed" for value in matching)
                status = "revealed" if revealed else "awaiting-reveal" if committed else "commit-unconfirmed"
                if not revealed and height >= integer(review["reveal_deadline"], "reveal deadline"):
                    status = "reveal-missed"
                pending.append({**{key: review[key] for key in ("claim_id", "round_id", "actor", "commit_deadline", "reveal_deadline")}, "status": status})
            return {"schema": SCHEMA, "chain_id": self.chain, "height": str(height), "local_only": True, "notice": NOTICE,
                    "claims": [{"claim_id": claim_id, "history": self.history(claim_id, height)} for claim_id in ids],
                    "transactions": [public_receipt(value) for value in attempts], "pending_reviews": pending}


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    sub = result.add_subparsers(dest="command", required=True)
    for name in ("onboard", "submit", "commit", "reveal", "challenge", "history", "snapshot", "retry", "serve"):
        command = sub.add_parser(name)
        command.add_argument("--home", required=True)
        command.add_argument("--wait", type=int, default=30, help="Seconds to observe a single broadcast (1–120).")
        if name == "submit":
            command.add_argument("--content", required=True)
            command.add_argument("--method", default="")
            command.add_argument("--reasoning", required=True)
            command.add_argument("--domain", default="physics")
            command.add_argument("--category", default="empirical")
        if name in ("commit", "reveal", "history"):
            command.add_argument("--claim", required=True)
        if name in ("commit", "reveal"):
            command.add_argument("--actor", choices=REVIEWERS, required=True)
        if name == "reveal":
            command.add_argument("--wait-for-phase", action="store_true", help="Wait up to 900 seconds for this round's reveal phase; never broadcast outside it.")
        if name == "commit":
            command.add_argument("--vote", choices=("accept", "reject", "malformed"), required=True)
            command.add_argument("--reason", required=True)
            command.add_argument("--scope", required=True)
            command.add_argument("--method", default="")
            command.add_argument("--confidence", type=int, default=800000)
        if name == "challenge":
            command.add_argument("--fact", required=True)
            command.add_argument("--content", required=True)
            command.add_argument("--reason", required=True)
            command.add_argument("--stake", default="11000000", help="Explicit local contradiction collateral in uzrn (default11 ZRN).")
        if name in ("commit", "challenge"):
            command.add_argument("--evidence", action="append", default=[])
        if name == "serve":
            command.add_argument("--port", type=int, default=47658)
        if name == "retry":
            command.add_argument("--txhash", required=True, help="Query first, then explicitly rebroadcast only the identical retained signed bytes if unresolved.")
    return result


def main():
    os.umask(0o077)
    args = parser().parse_args()
    try:
        if not 1 <= args.wait <= 120:
            raise WorkflowError("--wait must be1–120 seconds.")
        if args.command == "commit" and not 0 <= args.confidence <= 1000000:
            raise WorkflowError("--confidence must be0–1000000.")
        workflow = Workflow(args.home, args.wait)
        if args.command == "serve":
            sibling("claim-workflow-view").serve(workflow.snapshot, args.port)
            return 0
        if args.command == "snapshot":
            output = workflow.snapshot()
        else:
            if args.command == "reveal" and args.wait_for_phase:
                # Waiting is read-only and holds no workflow lock, so the
                # reader can keep displaying phase progress. review() checks
                # the actual phase again under the write lock before signing.
                deadline = time.monotonic() + 900
                while workflow.round_for_claim(args.claim).get("phase") in ("VERIFICATION_PHASE_COMMIT", 1, "1") and time.monotonic() < deadline:
                    time.sleep(0.5)
            with workflow.locked():
                if args.command == "onboard":
                    output = workflow.onboard()
                elif args.command == "submit":
                    output = workflow.submit(args)
                elif args.command in ("commit", "reveal"):
                    output = workflow.review(args, args.command == "reveal")
                elif args.command == "challenge":
                    output = workflow.challenge(args)
                elif args.command == "retry":
                    output = workflow.retry(args.txhash)
                else:
                    workflow.reconcile()
                    output = workflow.history(args.claim)
        print(json.dumps(output, sort_keys=True, ensure_ascii=False))
        return 0
    except (WorkflowError, local.LocalNodeError, OSError, ValueError, KeyError, TypeError, subprocess.TimeoutExpired) as error:
        print(f"claim-workflow: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
