// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zerone/knowledge/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName            = "/zerone.knowledge.v1.Query/Params"
	Query_Fact_FullMethodName              = "/zerone.knowledge.v1.Query/Fact"
	Query_Facts_FullMethodName             = "/zerone.knowledge.v1.Query/Facts"
	Query_FactsByDomain_FullMethodName     = "/zerone.knowledge.v1.Query/FactsByDomain"
	Query_FactsBySubmitter_FullMethodName  = "/zerone.knowledge.v1.Query/FactsBySubmitter"
	Query_Claim_FullMethodName             = "/zerone.knowledge.v1.Query/Claim"
	Query_PendingClaims_FullMethodName     = "/zerone.knowledge.v1.Query/PendingClaims"
	Query_VerificationRound_FullMethodName = "/zerone.knowledge.v1.Query/VerificationRound"
	Query_Domain_FullMethodName            = "/zerone.knowledge.v1.Query/Domain"
	Query_Domains_FullMethodName           = "/zerone.knowledge.v1.Query/Domains"
	Query_FactConfidence_FullMethodName    = "/zerone.knowledge.v1.Query/FactConfidence"
	Query_FactCitationCount_FullMethodName = "/zerone.knowledge.v1.Query/FactCitationCount"
	Query_FactRelations_FullMethodName     = "/zerone.knowledge.v1.Query/FactRelations"
	Query_FactsBySubject_FullMethodName    = "/zerone.knowledge.v1.Query/FactsBySubject"
	Query_FactsByTag_FullMethodName        = "/zerone.knowledge.v1.Query/FactsByTag"
	Query_FactByCanonical_FullMethodName   = "/zerone.knowledge.v1.Query/FactByCanonical"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the knowledge module.
type QueryClient interface {
	// Params queries module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Fact queries a single fact by ID.
	Fact(ctx context.Context, in *QueryFactRequest, opts ...grpc.CallOption) (*QueryFactResponse, error)
	// Facts queries facts with optional domain, status, and category filters.
	Facts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error)
	// FactsByDomain queries all facts in a domain.
	FactsByDomain(ctx context.Context, in *QueryFactsByDomainRequest, opts ...grpc.CallOption) (*QueryFactsByDomainResponse, error)
	// FactsBySubmitter queries all facts submitted by an address.
	FactsBySubmitter(ctx context.Context, in *QueryFactsBySubmitterRequest, opts ...grpc.CallOption) (*QueryFactsBySubmitterResponse, error)
	// Claim queries a single claim by ID.
	Claim(ctx context.Context, in *QueryClaimRequest, opts ...grpc.CallOption) (*QueryClaimResponse, error)
	// PendingClaims queries all pending claims.
	PendingClaims(ctx context.Context, in *QueryPendingClaimsRequest, opts ...grpc.CallOption) (*QueryPendingClaimsResponse, error)
	// VerificationRound queries a verification round by ID.
	VerificationRound(ctx context.Context, in *QueryVerificationRoundRequest, opts ...grpc.CallOption) (*QueryVerificationRoundResponse, error)
	// Domain queries a domain by name.
	Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error)
	// Domains queries all domains with optional pagination.
	Domains(ctx context.Context, in *QueryDomainsRequest, opts ...grpc.CallOption) (*QueryDomainsResponse, error)
	// FactConfidence queries the current confidence score of a fact.
	FactConfidence(ctx context.Context, in *QueryFactConfidenceRequest, opts ...grpc.CallOption) (*QueryFactConfidenceResponse, error)
	// FactCitationCount queries the citation count of a fact.
	FactCitationCount(ctx context.Context, in *QueryFactCitationCountRequest, opts ...grpc.CallOption) (*QueryFactCitationCountResponse, error)
	// FactRelations queries typed relations for a fact (knowledge graph edges).
	FactRelations(ctx context.Context, in *QueryFactRelationsRequest, opts ...grpc.CallOption) (*QueryFactRelationsResponse, error)
	// FactsBySubject queries facts by structured subject within a domain.
	FactsBySubject(ctx context.Context, in *QueryFactsBySubjectRequest, opts ...grpc.CallOption) (*QueryFactsBySubjectResponse, error)
	// FactsByTag queries facts by a searchable tag.
	FactsByTag(ctx context.Context, in *QueryFactsByTagRequest, opts ...grpc.CallOption) (*QueryFactsByTagResponse, error)
	// FactByCanonical queries a fact by its canonical form hash.
	FactByCanonical(ctx context.Context, in *QueryFactByCanonicalRequest, opts ...grpc.CallOption) (*QueryFactByCanonicalResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Fact(ctx context.Context, in *QueryFactRequest, opts ...grpc.CallOption) (*QueryFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactResponse)
	err := c.cc.Invoke(ctx, Query_Fact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Facts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsResponse)
	err := c.cc.Invoke(ctx, Query_Facts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactsByDomain(ctx context.Context, in *QueryFactsByDomainRequest, opts ...grpc.CallOption) (*QueryFactsByDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsByDomainResponse)
	err := c.cc.Invoke(ctx, Query_FactsByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactsBySubmitter(ctx context.Context, in *QueryFactsBySubmitterRequest, opts ...grpc.CallOption) (*QueryFactsBySubmitterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsBySubmitterResponse)
	err := c.cc.Invoke(ctx, Query_FactsBySubmitter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Claim(ctx context.Context, in *QueryClaimRequest, opts ...grpc.CallOption) (*QueryClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryClaimResponse)
	err := c.cc.Invoke(ctx, Query_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingClaims(ctx context.Context, in *QueryPendingClaimsRequest, opts ...grpc.CallOption) (*QueryPendingClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPendingClaimsResponse)
	err := c.cc.Invoke(ctx, Query_PendingClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerificationRound(ctx context.Context, in *QueryVerificationRoundRequest, opts ...grpc.CallOption) (*QueryVerificationRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVerificationRoundResponse)
	err := c.cc.Invoke(ctx, Query_VerificationRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDomainResponse)
	err := c.cc.Invoke(ctx, Query_Domain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Domains(ctx context.Context, in *QueryDomainsRequest, opts ...grpc.CallOption) (*QueryDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDomainsResponse)
	err := c.cc.Invoke(ctx, Query_Domains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactConfidence(ctx context.Context, in *QueryFactConfidenceRequest, opts ...grpc.CallOption) (*QueryFactConfidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactConfidenceResponse)
	err := c.cc.Invoke(ctx, Query_FactConfidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactCitationCount(ctx context.Context, in *QueryFactCitationCountRequest, opts ...grpc.CallOption) (*QueryFactCitationCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactCitationCountResponse)
	err := c.cc.Invoke(ctx, Query_FactCitationCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactRelations(ctx context.Context, in *QueryFactRelationsRequest, opts ...grpc.CallOption) (*QueryFactRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactRelationsResponse)
	err := c.cc.Invoke(ctx, Query_FactRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactsBySubject(ctx context.Context, in *QueryFactsBySubjectRequest, opts ...grpc.CallOption) (*QueryFactsBySubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsBySubjectResponse)
	err := c.cc.Invoke(ctx, Query_FactsBySubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactsByTag(ctx context.Context, in *QueryFactsByTagRequest, opts ...grpc.CallOption) (*QueryFactsByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsByTagResponse)
	err := c.cc.Invoke(ctx, Query_FactsByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactByCanonical(ctx context.Context, in *QueryFactByCanonicalRequest, opts ...grpc.CallOption) (*QueryFactByCanonicalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactByCanonicalResponse)
	err := c.cc.Invoke(ctx, Query_FactByCanonical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the knowledge module.
type QueryServer interface {
	// Params queries module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Fact queries a single fact by ID.
	Fact(context.Context, *QueryFactRequest) (*QueryFactResponse, error)
	// Facts queries facts with optional domain, status, and category filters.
	Facts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error)
	// FactsByDomain queries all facts in a domain.
	FactsByDomain(context.Context, *QueryFactsByDomainRequest) (*QueryFactsByDomainResponse, error)
	// FactsBySubmitter queries all facts submitted by an address.
	FactsBySubmitter(context.Context, *QueryFactsBySubmitterRequest) (*QueryFactsBySubmitterResponse, error)
	// Claim queries a single claim by ID.
	Claim(context.Context, *QueryClaimRequest) (*QueryClaimResponse, error)
	// PendingClaims queries all pending claims.
	PendingClaims(context.Context, *QueryPendingClaimsRequest) (*QueryPendingClaimsResponse, error)
	// VerificationRound queries a verification round by ID.
	VerificationRound(context.Context, *QueryVerificationRoundRequest) (*QueryVerificationRoundResponse, error)
	// Domain queries a domain by name.
	Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error)
	// Domains queries all domains with optional pagination.
	Domains(context.Context, *QueryDomainsRequest) (*QueryDomainsResponse, error)
	// FactConfidence queries the current confidence score of a fact.
	FactConfidence(context.Context, *QueryFactConfidenceRequest) (*QueryFactConfidenceResponse, error)
	// FactCitationCount queries the citation count of a fact.
	FactCitationCount(context.Context, *QueryFactCitationCountRequest) (*QueryFactCitationCountResponse, error)
	// FactRelations queries typed relations for a fact (knowledge graph edges).
	FactRelations(context.Context, *QueryFactRelationsRequest) (*QueryFactRelationsResponse, error)
	// FactsBySubject queries facts by structured subject within a domain.
	FactsBySubject(context.Context, *QueryFactsBySubjectRequest) (*QueryFactsBySubjectResponse, error)
	// FactsByTag queries facts by a searchable tag.
	FactsByTag(context.Context, *QueryFactsByTagRequest) (*QueryFactsByTagResponse, error)
	// FactByCanonical queries a fact by its canonical form hash.
	FactByCanonical(context.Context, *QueryFactByCanonicalRequest) (*QueryFactByCanonicalResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Fact(context.Context, *QueryFactRequest) (*QueryFactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fact not implemented")
}
func (UnimplementedQueryServer) Facts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Facts not implemented")
}
func (UnimplementedQueryServer) FactsByDomain(context.Context, *QueryFactsByDomainRequest) (*QueryFactsByDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactsByDomain not implemented")
}
func (UnimplementedQueryServer) FactsBySubmitter(context.Context, *QueryFactsBySubmitterRequest) (*QueryFactsBySubmitterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactsBySubmitter not implemented")
}
func (UnimplementedQueryServer) Claim(context.Context, *QueryClaimRequest) (*QueryClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedQueryServer) PendingClaims(context.Context, *QueryPendingClaimsRequest) (*QueryPendingClaimsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PendingClaims not implemented")
}
func (UnimplementedQueryServer) VerificationRound(context.Context, *QueryVerificationRoundRequest) (*QueryVerificationRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerificationRound not implemented")
}
func (UnimplementedQueryServer) Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Domain not implemented")
}
func (UnimplementedQueryServer) Domains(context.Context, *QueryDomainsRequest) (*QueryDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Domains not implemented")
}
func (UnimplementedQueryServer) FactConfidence(context.Context, *QueryFactConfidenceRequest) (*QueryFactConfidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactConfidence not implemented")
}
func (UnimplementedQueryServer) FactCitationCount(context.Context, *QueryFactCitationCountRequest) (*QueryFactCitationCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactCitationCount not implemented")
}
func (UnimplementedQueryServer) FactRelations(context.Context, *QueryFactRelationsRequest) (*QueryFactRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactRelations not implemented")
}
func (UnimplementedQueryServer) FactsBySubject(context.Context, *QueryFactsBySubjectRequest) (*QueryFactsBySubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactsBySubject not implemented")
}
func (UnimplementedQueryServer) FactsByTag(context.Context, *QueryFactsByTagRequest) (*QueryFactsByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactsByTag not implemented")
}
func (UnimplementedQueryServer) FactByCanonical(context.Context, *QueryFactByCanonicalRequest) (*QueryFactByCanonicalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactByCanonical not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Fact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Fact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Fact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Fact(ctx, req.(*QueryFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Facts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Facts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Facts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Facts(ctx, req.(*QueryFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactsByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsByDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactsByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactsByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactsByDomain(ctx, req.(*QueryFactsByDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactsBySubmitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsBySubmitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactsBySubmitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactsBySubmitter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactsBySubmitter(ctx, req.(*QueryFactsBySubmitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Claim(ctx, req.(*QueryClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingClaims(ctx, req.(*QueryPendingClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerificationRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerificationRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerificationRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerificationRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerificationRound(ctx, req.(*QueryVerificationRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Domain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Domain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domain(ctx, req.(*QueryDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Domains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Domains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domains(ctx, req.(*QueryDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactConfidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactConfidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactConfidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactConfidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactConfidence(ctx, req.(*QueryFactConfidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactCitationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactCitationCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactCitationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactCitationCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactCitationCount(ctx, req.(*QueryFactCitationCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactRelations(ctx, req.(*QueryFactRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactsBySubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsBySubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactsBySubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactsBySubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactsBySubject(ctx, req.(*QueryFactsBySubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactsByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactsByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactsByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactsByTag(ctx, req.(*QueryFactsByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactByCanonical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactByCanonicalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactByCanonical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FactByCanonical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactByCanonical(ctx, req.(*QueryFactByCanonicalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerone.knowledge.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Fact",
			Handler:    _Query_Fact_Handler,
		},
		{
			MethodName: "Facts",
			Handler:    _Query_Facts_Handler,
		},
		{
			MethodName: "FactsByDomain",
			Handler:    _Query_FactsByDomain_Handler,
		},
		{
			MethodName: "FactsBySubmitter",
			Handler:    _Query_FactsBySubmitter_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _Query_Claim_Handler,
		},
		{
			MethodName: "PendingClaims",
			Handler:    _Query_PendingClaims_Handler,
		},
		{
			MethodName: "VerificationRound",
			Handler:    _Query_VerificationRound_Handler,
		},
		{
			MethodName: "Domain",
			Handler:    _Query_Domain_Handler,
		},
		{
			MethodName: "Domains",
			Handler:    _Query_Domains_Handler,
		},
		{
			MethodName: "FactConfidence",
			Handler:    _Query_FactConfidence_Handler,
		},
		{
			MethodName: "FactCitationCount",
			Handler:    _Query_FactCitationCount_Handler,
		},
		{
			MethodName: "FactRelations",
			Handler:    _Query_FactRelations_Handler,
		},
		{
			MethodName: "FactsBySubject",
			Handler:    _Query_FactsBySubject_Handler,
		},
		{
			MethodName: "FactsByTag",
			Handler:    _Query_FactsByTag_Handler,
		},
		{
			MethodName: "FactByCanonical",
			Handler:    _Query_FactByCanonical_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zerone/knowledge/v1/query.proto",
}
