// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zerone/knowledge/v1/tok.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToKSelector is the union of supported subgraph extraction modes.
// Plan 1 binds RootedSubtree, AncestorCone, Frontier. Plan 2 adds
// CascadeReplay; Plan 4 adds ForkAndDecide.
type ToKSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Variant:
	//
	//	*ToKSelector_RootedSubtree
	//	*ToKSelector_AncestorCone
	//	*ToKSelector_Frontier
	Variant       isToKSelector_Variant `protobuf_oneof:"variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToKSelector) Reset() {
	*x = ToKSelector{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToKSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToKSelector) ProtoMessage() {}

func (x *ToKSelector) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToKSelector.ProtoReflect.Descriptor instead.
func (*ToKSelector) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{0}
}

func (x *ToKSelector) GetVariant() isToKSelector_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ToKSelector) GetRootedSubtree() *RootedSubtreeSelector {
	if x != nil {
		if x, ok := x.Variant.(*ToKSelector_RootedSubtree); ok {
			return x.RootedSubtree
		}
	}
	return nil
}

func (x *ToKSelector) GetAncestorCone() *AncestorConeSelector {
	if x != nil {
		if x, ok := x.Variant.(*ToKSelector_AncestorCone); ok {
			return x.AncestorCone
		}
	}
	return nil
}

func (x *ToKSelector) GetFrontier() *FrontierSelector {
	if x != nil {
		if x, ok := x.Variant.(*ToKSelector_Frontier); ok {
			return x.Frontier
		}
	}
	return nil
}

type isToKSelector_Variant interface {
	isToKSelector_Variant()
}

type ToKSelector_RootedSubtree struct {
	RootedSubtree *RootedSubtreeSelector `protobuf:"bytes,1,opt,name=rooted_subtree,json=rootedSubtree,proto3,oneof"`
}

type ToKSelector_AncestorCone struct {
	AncestorCone *AncestorConeSelector `protobuf:"bytes,2,opt,name=ancestor_cone,json=ancestorCone,proto3,oneof"`
}

type ToKSelector_Frontier struct {
	Frontier *FrontierSelector `protobuf:"bytes,3,opt,name=frontier,proto3,oneof"` // Reserved: 4 = cascade_replay (Plan 2), 5 = fork_and_decide (Plan 4).
}

func (*ToKSelector_RootedSubtree) isToKSelector_Variant() {}

func (*ToKSelector_AncestorCone) isToKSelector_Variant() {}

func (*ToKSelector_Frontier) isToKSelector_Variant() {}

// RootedSubtreeSelector: walk descendants from an axiom or interior node
// up to max_depth. Returns the rooted node + all reachable descendants.
type RootedSubtreeSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootFactId    string                 `protobuf:"bytes,1,opt,name=root_fact_id,json=rootFactId,proto3" json:"root_fact_id,omitempty"`
	MaxDepth      uint32                 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // 0 = unbounded; chain caps at 32.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootedSubtreeSelector) Reset() {
	*x = RootedSubtreeSelector{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootedSubtreeSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootedSubtreeSelector) ProtoMessage() {}

func (x *RootedSubtreeSelector) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootedSubtreeSelector.ProtoReflect.Descriptor instead.
func (*RootedSubtreeSelector) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{1}
}

func (x *RootedSubtreeSelector) GetRootFactId() string {
	if x != nil {
		return x.RootFactId
	}
	return ""
}

func (x *RootedSubtreeSelector) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// AncestorConeSelector: walk ancestors from a leaf claim up to k paths.
// Useful for "show me everything this conclusion depends on."
type AncestorConeSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafFactId    string                 `protobuf:"bytes,1,opt,name=leaf_fact_id,json=leafFactId,proto3" json:"leaf_fact_id,omitempty"`
	MaxPaths      uint32                 `protobuf:"varint,2,opt,name=max_paths,json=maxPaths,proto3" json:"max_paths,omitempty"` // 0 = all; chain caps at 256.
	MaxDepth      uint32                 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // 0 = unbounded; chain caps at 32.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AncestorConeSelector) Reset() {
	*x = AncestorConeSelector{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AncestorConeSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AncestorConeSelector) ProtoMessage() {}

func (x *AncestorConeSelector) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AncestorConeSelector.ProtoReflect.Descriptor instead.
func (*AncestorConeSelector) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{2}
}

func (x *AncestorConeSelector) GetLeafFactId() string {
	if x != nil {
		return x.LeafFactId
	}
	return ""
}

func (x *AncestorConeSelector) GetMaxPaths() uint32 {
	if x != nil {
		return x.MaxPaths
	}
	return 0
}

func (x *AncestorConeSelector) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// FrontierSelector: latest-N facts in a domain since block. Useful for
// incremental/streaming training updates.
type FrontierSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	SinceBlock    uint64                 `protobuf:"varint,2,opt,name=since_block,json=sinceBlock,proto3" json:"since_block,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = chain default (1024); cap 8192.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontierSelector) Reset() {
	*x = FrontierSelector{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontierSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontierSelector) ProtoMessage() {}

func (x *FrontierSelector) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontierSelector.ProtoReflect.Descriptor instead.
func (*FrontierSelector) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{3}
}

func (x *FrontierSelector) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FrontierSelector) GetSinceBlock() uint64 {
	if x != nil {
		return x.SinceBlock
	}
	return 0
}

func (x *FrontierSelector) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ToKBundle is the response of BundleToK. The Merkle root commits to
// the included node and edge IDs domain-tagged separately. A trainer
// who has the IDs can re-derive the root locally without trusting the
// RPC to faithfully serialise payloads.
type ToKBundle struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SnapshotBlock       uint64                 `protobuf:"varint,1,opt,name=snapshot_block,json=snapshotBlock,proto3" json:"snapshot_block,omitempty"`
	SnapshotRoot        []byte                 `protobuf:"bytes,2,opt,name=snapshot_root,json=snapshotRoot,proto3" json:"snapshot_root,omitempty"`                      // 32-byte Merkle root.
	IncludedNodeIds     []string               `protobuf:"bytes,3,rep,name=included_node_ids,json=includedNodeIds,proto3" json:"included_node_ids,omitempty"`           // sorted, deterministic.
	IncludedEdges       []*ToKEdge             `protobuf:"bytes,4,rep,name=included_edges,json=includedEdges,proto3" json:"included_edges,omitempty"`                   // sorted by (from,to,relation).
	Nodes               []*Fact                `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`                                                        // full payloads, in node-id order.
	SerialisationFormat string                 `protobuf:"bytes,6,opt,name=serialisation_format,json=serialisationFormat,proto3" json:"serialisation_format,omitempty"` // "jsonl_adjacency_v1" by default.
	SerialisedPayload   []byte                 `protobuf:"bytes,7,opt,name=serialised_payload,json=serialisedPayload,proto3" json:"serialised_payload,omitempty"`       // optional; large bundles may omit.
	Provenance          *ToKBundleProvenance   `protobuf:"bytes,8,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToKBundle) Reset() {
	*x = ToKBundle{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToKBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToKBundle) ProtoMessage() {}

func (x *ToKBundle) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToKBundle.ProtoReflect.Descriptor instead.
func (*ToKBundle) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{4}
}

func (x *ToKBundle) GetSnapshotBlock() uint64 {
	if x != nil {
		return x.SnapshotBlock
	}
	return 0
}

func (x *ToKBundle) GetSnapshotRoot() []byte {
	if x != nil {
		return x.SnapshotRoot
	}
	return nil
}

func (x *ToKBundle) GetIncludedNodeIds() []string {
	if x != nil {
		return x.IncludedNodeIds
	}
	return nil
}

func (x *ToKBundle) GetIncludedEdges() []*ToKEdge {
	if x != nil {
		return x.IncludedEdges
	}
	return nil
}

func (x *ToKBundle) GetNodes() []*Fact {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ToKBundle) GetSerialisationFormat() string {
	if x != nil {
		return x.SerialisationFormat
	}
	return ""
}

func (x *ToKBundle) GetSerialisedPayload() []byte {
	if x != nil {
		return x.SerialisedPayload
	}
	return nil
}

func (x *ToKBundle) GetProvenance() *ToKBundleProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

// ToKEdge mirrors the existing relation-graph edges but ships them as
// first-class bundle entries (not nested under nodes), so trainers can
// load topology without touching node payloads.
type ToKEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromFactId    string                 `protobuf:"bytes,1,opt,name=from_fact_id,json=fromFactId,proto3" json:"from_fact_id,omitempty"`
	ToFactId      string                 `protobuf:"bytes,2,opt,name=to_fact_id,json=toFactId,proto3" json:"to_fact_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`   // SUPPORTS, CONTRADICTS, GENERALIZES, etc.
	Inference     string                 `protobuf:"bytes,4,opt,name=inference,proto3" json:"inference,omitempty"` // typed reasoning move (Wave 5 vocab).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToKEdge) Reset() {
	*x = ToKEdge{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToKEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToKEdge) ProtoMessage() {}

func (x *ToKEdge) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToKEdge.ProtoReflect.Descriptor instead.
func (*ToKEdge) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{5}
}

func (x *ToKEdge) GetFromFactId() string {
	if x != nil {
		return x.FromFactId
	}
	return ""
}

func (x *ToKEdge) GetToFactId() string {
	if x != nil {
		return x.ToFactId
	}
	return ""
}

func (x *ToKEdge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ToKEdge) GetInference() string {
	if x != nil {
		return x.Inference
	}
	return ""
}

// ToKBundleProvenance carries the version pins required by TC2.
type ToKBundleProvenance struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	ChainId                       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TraceSchemaVersion            string                 `protobuf:"bytes,2,opt,name=trace_schema_version,json=traceSchemaVersion,proto3" json:"trace_schema_version,omitempty"`
	CanonicalSerialisationVersion string                 `protobuf:"bytes,3,opt,name=canonical_serialisation_version,json=canonicalSerialisationVersion,proto3" json:"canonical_serialisation_version,omitempty"`
	TokenizerVersion              string                 `protobuf:"bytes,4,opt,name=tokenizer_version,json=tokenizerVersion,proto3" json:"tokenizer_version,omitempty"`
	SelectorUsed                  *ToKSelector           `protobuf:"bytes,5,opt,name=selector_used,json=selectorUsed,proto3" json:"selector_used,omitempty"`
	CapMaxDepth                   uint32                 `protobuf:"varint,6,opt,name=cap_max_depth,json=capMaxDepth,proto3" json:"cap_max_depth,omitempty"` // chain-side caps applied.
	CapMaxPaths                   uint32                 `protobuf:"varint,7,opt,name=cap_max_paths,json=capMaxPaths,proto3" json:"cap_max_paths,omitempty"`
	CapLimit                      uint32                 `protobuf:"varint,8,opt,name=cap_limit,json=capLimit,proto3" json:"cap_limit,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ToKBundleProvenance) Reset() {
	*x = ToKBundleProvenance{}
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToKBundleProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToKBundleProvenance) ProtoMessage() {}

func (x *ToKBundleProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_zerone_knowledge_v1_tok_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToKBundleProvenance.ProtoReflect.Descriptor instead.
func (*ToKBundleProvenance) Descriptor() ([]byte, []int) {
	return file_zerone_knowledge_v1_tok_proto_rawDescGZIP(), []int{6}
}

func (x *ToKBundleProvenance) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ToKBundleProvenance) GetTraceSchemaVersion() string {
	if x != nil {
		return x.TraceSchemaVersion
	}
	return ""
}

func (x *ToKBundleProvenance) GetCanonicalSerialisationVersion() string {
	if x != nil {
		return x.CanonicalSerialisationVersion
	}
	return ""
}

func (x *ToKBundleProvenance) GetTokenizerVersion() string {
	if x != nil {
		return x.TokenizerVersion
	}
	return ""
}

func (x *ToKBundleProvenance) GetSelectorUsed() *ToKSelector {
	if x != nil {
		return x.SelectorUsed
	}
	return nil
}

func (x *ToKBundleProvenance) GetCapMaxDepth() uint32 {
	if x != nil {
		return x.CapMaxDepth
	}
	return 0
}

func (x *ToKBundleProvenance) GetCapMaxPaths() uint32 {
	if x != nil {
		return x.CapMaxPaths
	}
	return 0
}

func (x *ToKBundleProvenance) GetCapLimit() uint32 {
	if x != nil {
		return x.CapLimit
	}
	return 0
}

var File_zerone_knowledge_v1_tok_proto protoreflect.FileDescriptor

const file_zerone_knowledge_v1_tok_proto_rawDesc = "" +
	"\n" +
	"\x1dzerone/knowledge/v1/tok.proto\x12\x13zerone.knowledge.v1\x1a\x1fzerone/knowledge/v1/types.proto\"\x84\x02\n" +
	"\vToKSelector\x12S\n" +
	"\x0erooted_subtree\x18\x01 \x01(\v2*.zerone.knowledge.v1.RootedSubtreeSelectorH\x00R\rrootedSubtree\x12P\n" +
	"\rancestor_cone\x18\x02 \x01(\v2).zerone.knowledge.v1.AncestorConeSelectorH\x00R\fancestorCone\x12C\n" +
	"\bfrontier\x18\x03 \x01(\v2%.zerone.knowledge.v1.FrontierSelectorH\x00R\bfrontierB\t\n" +
	"\avariant\"V\n" +
	"\x15RootedSubtreeSelector\x12 \n" +
	"\froot_fact_id\x18\x01 \x01(\tR\n" +
	"rootFactId\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\rR\bmaxDepth\"r\n" +
	"\x14AncestorConeSelector\x12 \n" +
	"\fleaf_fact_id\x18\x01 \x01(\tR\n" +
	"leafFactId\x12\x1b\n" +
	"\tmax_paths\x18\x02 \x01(\rR\bmaxPaths\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\rR\bmaxDepth\"a\n" +
	"\x10FrontierSelector\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vsince_block\x18\x02 \x01(\x04R\n" +
	"sinceBlock\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\xa5\x03\n" +
	"\tToKBundle\x12%\n" +
	"\x0esnapshot_block\x18\x01 \x01(\x04R\rsnapshotBlock\x12#\n" +
	"\rsnapshot_root\x18\x02 \x01(\fR\fsnapshotRoot\x12*\n" +
	"\x11included_node_ids\x18\x03 \x03(\tR\x0fincludedNodeIds\x12C\n" +
	"\x0eincluded_edges\x18\x04 \x03(\v2\x1c.zerone.knowledge.v1.ToKEdgeR\rincludedEdges\x12/\n" +
	"\x05nodes\x18\x05 \x03(\v2\x19.zerone.knowledge.v1.FactR\x05nodes\x121\n" +
	"\x14serialisation_format\x18\x06 \x01(\tR\x13serialisationFormat\x12-\n" +
	"\x12serialised_payload\x18\a \x01(\fR\x11serialisedPayload\x12H\n" +
	"\n" +
	"provenance\x18\b \x01(\v2(.zerone.knowledge.v1.ToKBundleProvenanceR\n" +
	"provenance\"\x83\x01\n" +
	"\aToKEdge\x12 \n" +
	"\ffrom_fact_id\x18\x01 \x01(\tR\n" +
	"fromFactId\x12\x1c\n" +
	"\n" +
	"to_fact_id\x18\x02 \x01(\tR\btoFactId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1c\n" +
	"\tinference\x18\x04 \x01(\tR\tinference\"\x83\x03\n" +
	"\x13ToKBundleProvenance\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x120\n" +
	"\x14trace_schema_version\x18\x02 \x01(\tR\x12traceSchemaVersion\x12F\n" +
	"\x1fcanonical_serialisation_version\x18\x03 \x01(\tR\x1dcanonicalSerialisationVersion\x12+\n" +
	"\x11tokenizer_version\x18\x04 \x01(\tR\x10tokenizerVersion\x12E\n" +
	"\rselector_used\x18\x05 \x01(\v2 .zerone.knowledge.v1.ToKSelectorR\fselectorUsed\x12\"\n" +
	"\rcap_max_depth\x18\x06 \x01(\rR\vcapMaxDepth\x12\"\n" +
	"\rcap_max_paths\x18\a \x01(\rR\vcapMaxPaths\x12\x1b\n" +
	"\tcap_limit\x18\b \x01(\rR\bcapLimitB2Z0github.com/zerone-chain/zerone/x/knowledge/typesb\x06proto3"

var (
	file_zerone_knowledge_v1_tok_proto_rawDescOnce sync.Once
	file_zerone_knowledge_v1_tok_proto_rawDescData []byte
)

func file_zerone_knowledge_v1_tok_proto_rawDescGZIP() []byte {
	file_zerone_knowledge_v1_tok_proto_rawDescOnce.Do(func() {
		file_zerone_knowledge_v1_tok_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerone_knowledge_v1_tok_proto_rawDesc), len(file_zerone_knowledge_v1_tok_proto_rawDesc)))
	})
	return file_zerone_knowledge_v1_tok_proto_rawDescData
}

var file_zerone_knowledge_v1_tok_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_zerone_knowledge_v1_tok_proto_goTypes = []any{
	(*ToKSelector)(nil),           // 0: zerone.knowledge.v1.ToKSelector
	(*RootedSubtreeSelector)(nil), // 1: zerone.knowledge.v1.RootedSubtreeSelector
	(*AncestorConeSelector)(nil),  // 2: zerone.knowledge.v1.AncestorConeSelector
	(*FrontierSelector)(nil),      // 3: zerone.knowledge.v1.FrontierSelector
	(*ToKBundle)(nil),             // 4: zerone.knowledge.v1.ToKBundle
	(*ToKEdge)(nil),               // 5: zerone.knowledge.v1.ToKEdge
	(*ToKBundleProvenance)(nil),   // 6: zerone.knowledge.v1.ToKBundleProvenance
	(*Fact)(nil),                  // 7: zerone.knowledge.v1.Fact
}
var file_zerone_knowledge_v1_tok_proto_depIdxs = []int32{
	1, // 0: zerone.knowledge.v1.ToKSelector.rooted_subtree:type_name -> zerone.knowledge.v1.RootedSubtreeSelector
	2, // 1: zerone.knowledge.v1.ToKSelector.ancestor_cone:type_name -> zerone.knowledge.v1.AncestorConeSelector
	3, // 2: zerone.knowledge.v1.ToKSelector.frontier:type_name -> zerone.knowledge.v1.FrontierSelector
	5, // 3: zerone.knowledge.v1.ToKBundle.included_edges:type_name -> zerone.knowledge.v1.ToKEdge
	7, // 4: zerone.knowledge.v1.ToKBundle.nodes:type_name -> zerone.knowledge.v1.Fact
	6, // 5: zerone.knowledge.v1.ToKBundle.provenance:type_name -> zerone.knowledge.v1.ToKBundleProvenance
	0, // 6: zerone.knowledge.v1.ToKBundleProvenance.selector_used:type_name -> zerone.knowledge.v1.ToKSelector
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_zerone_knowledge_v1_tok_proto_init() }
func file_zerone_knowledge_v1_tok_proto_init() {
	if File_zerone_knowledge_v1_tok_proto != nil {
		return
	}
	file_zerone_knowledge_v1_types_proto_init()
	file_zerone_knowledge_v1_tok_proto_msgTypes[0].OneofWrappers = []any{
		(*ToKSelector_RootedSubtree)(nil),
		(*ToKSelector_AncestorCone)(nil),
		(*ToKSelector_Frontier)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerone_knowledge_v1_tok_proto_rawDesc), len(file_zerone_knowledge_v1_tok_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zerone_knowledge_v1_tok_proto_goTypes,
		DependencyIndexes: file_zerone_knowledge_v1_tok_proto_depIdxs,
		MessageInfos:      file_zerone_knowledge_v1_tok_proto_msgTypes,
	}.Build()
	File_zerone_knowledge_v1_tok_proto = out.File
	file_zerone_knowledge_v1_tok_proto_goTypes = nil
	file_zerone_knowledge_v1_tok_proto_depIdxs = nil
}
